/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from './message-activity.component';
import * as import1 from '@angular/core/src/change_detection/change_detection_util';
import * as import2 from '@angular/core/src/linker/view';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/linker/debug_context';
import * as import5 from '@angular/core/src/render/api';
import * as import6 from '@angular/core/src/metadata/view';
import * as import7 from '@angular/core/src/linker/view_type';
import * as import8 from '@angular/core/src/change_detection/constants';
import * as import9 from '@angular/core/src/linker/component_factory';
import * as import10 from '@angular/router/src/router';
import * as import11 from '@angular/material/core/compatibility/compatibility';
import * as import12 from '@angular/material/card/card';
import * as import13 from '@angular/material/button/button';
import * as import14 from '@angular/material/icon/icon';
import * as import15 from '../../../../node_modules/@angular/material/core/compatibility/compatibility.ngfactory';
import * as import16 from '../../../../node_modules/@angular/material/card/card.ngfactory';
import * as import17 from '../../../../node_modules/@angular/material/button/button.ngfactory';
import * as import18 from '../../../../node_modules/@angular/material/icon/icon.ngfactory';
import * as import19 from '@angular/core/src/linker/element_ref';
import * as import20 from '@angular/material/icon/icon-registry';
export class Wrapper_MessageActivityComponent {
  /*private*/ _eventHandler:Function;
  context:import0.MessageActivityComponent;
  /*private*/ _changed:boolean;
  /*private*/ _expr_0:any;
  subscription0:any;
  subscription1:any;
  constructor(p0:any) {
    this._changed = false;
    this.context = new import0.MessageActivityComponent(p0);
    this._expr_0 = import1.UNINITIALIZED;
  }
  ngOnDetach(view:import2.AppView<any>,componentView:import2.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
    (this.subscription0 && this.subscription0.unsubscribe());
    (this.subscription1 && this.subscription1.unsubscribe());
  }
  check_activity(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_0,currValue))) {
      this._changed = true;
      this.context.activity = currValue;
      this._expr_0 = currValue;
    }
  }
  ngDoCheck(view:import2.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    return changed;
  }
  checkHost(view:import2.AppView<any>,componentView:import2.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import2.AppView<any>,_eventHandler:any,emit0:boolean,emit1:boolean):void {
    this._eventHandler = _eventHandler;
    if (emit0) { (this.subscription0 = this.context.remove.subscribe(_eventHandler.bind(view,'remove'))); }
    if (emit1) { (this.subscription1 = this.context.navigate.subscribe(_eventHandler.bind(view,'navigate'))); }
  }
}
const nodeDebugInfos_MessageActivityComponent_Host0:import4.StaticNodeDebugInfo[] = [new import4.StaticNodeDebugInfo([import0.MessageActivityComponent],import0.MessageActivityComponent,{})];
var renderType_MessageActivityComponent_Host:import5.RenderComponentType = import3.createRenderComponentType('',0,import6.ViewEncapsulation.None,([] as any[]),{});
class View_MessageActivityComponent_Host0 extends import2.DebugAppView<any> {
  _el_0:any;
  compView_0:import2.AppView<import0.MessageActivityComponent>;
  _MessageActivityComponent_0_3:Wrapper_MessageActivityComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_MessageActivityComponent_Host0,renderType_MessageActivityComponent_Host,import7.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import8.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_MessageActivityComponent_Host0);
  }
  createInternal(rootSelector:string):import9.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'message-activity',import3.EMPTY_INLINE_ARRAY,rootSelector,this.debug(0,0,0));
    this.compView_0 = new View_MessageActivityComponent0(this.viewUtils,this,0,this._el_0);
    this._MessageActivityComponent_0_3 = new Wrapper_MessageActivityComponent(this.injectorGet(import10.Router,this.parentIndex));
    this.compView_0.create(this._MessageActivityComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import9.ComponentRef_<any>(0,this,this._el_0,this._MessageActivityComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.MessageActivityComponent) && (0 === requestNodeIndex))) { return this._MessageActivityComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.debug(0,0,0);
    if (this._MessageActivityComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange)) { this.compView_0.markAsCheckOnce(); }
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
    this._MessageActivityComponent_0_3.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const MessageActivityComponentNgFactory:import9.ComponentFactory<import0.MessageActivityComponent> = new import9.ComponentFactory<import0.MessageActivityComponent>('message-activity',View_MessageActivityComponent_Host0,import0.MessageActivityComponent);
const styles_MessageActivityComponent:any[] = ([] as any[]);
const nodeDebugInfos_MessageActivityComponent0:import4.StaticNodeDebugInfo[] = [
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo([
    import11.MdPrefixRejector,
    import12.MdCard
  ]
  ,import12.MdCard,{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo([
    import11.MdPrefixRejector,
    import13.MdButton,
    import13.MdIconButtonCssMatStyler
  ]
  ,import13.MdButton,{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo([
    import11.MdPrefixRejector,
    import14.MdIcon
  ]
  ,import14.MdIcon,{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo([
    import11.MdPrefixRejector,
    import13.MdButton,
    import13.MdButtonCssMatStyler
  ]
  ,import13.MdButton,{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{})
]
;
var renderType_MessageActivityComponent:import5.RenderComponentType = import3.createRenderComponentType('/Users/jonoforbes/Developer/Ether/ether-app/src/activities/components/message-activity/message-activity.component.ts class MessageActivityComponent - inline template',0,import6.ViewEncapsulation.None,styles_MessageActivityComponent,{});
export class View_MessageActivityComponent0 extends import2.DebugAppView<import0.MessageActivityComponent> {
  _text_0:any;
  _el_1:any;
  compView_1:import2.AppView<import12.MdCard>;
  _MdPrefixRejector_1_3:import15.Wrapper_MdPrefixRejector;
  _MdCard_1_4:import16.Wrapper_MdCard;
  _text_2:any;
  _el_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _text_10:any;
  _el_11:any;
  compView_11:import2.AppView<import13.MdButton>;
  _MdPrefixRejector_11_3:import15.Wrapper_MdPrefixRejector;
  _MdButton_11_4:import17.Wrapper_MdButton;
  _MdIconButtonCssMatStyler_11_5:import17.Wrapper_MdIconButtonCssMatStyler;
  _text_12:any;
  _el_13:any;
  compView_13:import2.AppView<import14.MdIcon>;
  _MdPrefixRejector_13_3:import15.Wrapper_MdPrefixRejector;
  _MdIcon_13_4:import18.Wrapper_MdIcon;
  _text_14:any;
  _text_15:any;
  _text_16:any;
  _el_17:any;
  compView_17:import2.AppView<import13.MdButton>;
  _MdPrefixRejector_17_3:import15.Wrapper_MdPrefixRejector;
  _MdButton_17_4:import17.Wrapper_MdButton;
  _MdButtonCssMatStyler_17_5:import17.Wrapper_MdButtonCssMatStyler;
  _text_18:any;
  _el_19:any;
  _text_20:any;
  _text_21:any;
  _text_22:any;
  _text_23:any;
  _text_24:any;
  /*private*/ _expr_39:any;
  /*private*/ _expr_40:any;
  /*private*/ _expr_41:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_MessageActivityComponent0,renderType_MessageActivityComponent,import7.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import8.ChangeDetectorStatus.CheckOnce,nodeDebugInfos_MessageActivityComponent0);
    this._expr_39 = import1.UNINITIALIZED;
    this._expr_40 = import1.UNINITIALIZED;
    this._expr_41 = import1.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import9.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n    ',this.debug(0,0,0));
    this._el_1 = import3.createRenderElement(this.renderer,parentRenderNode,'md-card',import3.EMPTY_INLINE_ARRAY,this.debug(1,1,4));
    this.compView_1 = new import16.View_MdCard0(this.viewUtils,this,1,this._el_1);
    this._MdPrefixRejector_1_3 = new import15.Wrapper_MdPrefixRejector(this.parentView.injectorGet(import11.MATERIAL_COMPATIBILITY_MODE,this.parentIndex,(null as any)));
    this._MdCard_1_4 = new import16.Wrapper_MdCard();
    this._text_2 = this.renderer.createText((null as any),'\n    ',this.debug(2,1,13));
    this._el_3 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray2(2,'class','messageActivityCard'),this.debug(3,2,4));
    this._text_4 = this.renderer.createText(this._el_3,'\n  \n    ',this.debug(4,2,37));
    this._el_5 = import3.createRenderElement(this.renderer,this._el_3,'h1',import3.EMPTY_INLINE_ARRAY,this.debug(5,4,4));
    this._text_6 = this.renderer.createText(this._el_5,'',this.debug(6,4,8));
    this._text_7 = this.renderer.createText(this._el_3,'\n    ',this.debug(7,4,32));
    this._el_8 = import3.createRenderElement(this.renderer,this._el_3,'h2',import3.EMPTY_INLINE_ARRAY,this.debug(8,5,4));
    this._text_9 = this.renderer.createText(this._el_8,'',this.debug(9,5,8));
    this._text_10 = this.renderer.createText(this._el_3,'\n    ',this.debug(10,5,35));
    this._el_11 = import3.createRenderElement(this.renderer,this._el_3,'button',new import3.InlineArray4(4,'md-icon-button','','style','position: absolute; top: 10px; right: 10px'),this.debug(11,6,4));
    this.compView_11 = new import17.View_MdButton0(this.viewUtils,this,11,this._el_11);
    this._MdPrefixRejector_11_3 = new import15.Wrapper_MdPrefixRejector(this.parentView.injectorGet(import11.MATERIAL_COMPATIBILITY_MODE,this.parentIndex,(null as any)));
    this._MdButton_11_4 = new import17.Wrapper_MdButton(new import19.ElementRef(this._el_11),this.renderer);
    this._MdIconButtonCssMatStyler_11_5 = new import17.Wrapper_MdIconButtonCssMatStyler();
    this._text_12 = this.renderer.createText((null as any),'\n        ',this.debug(12,6,99));
    this._el_13 = import3.createRenderElement(this.renderer,(null as any),'md-icon',new import3.InlineArray4(4,'role','img','style','color: #5a5a5a; font-size: 12px !important;'),this.debug(13,7,8));
    this.compView_13 = new import18.View_MdIcon0(this.viewUtils,this,13,this._el_13);
    this._MdPrefixRejector_13_3 = new import15.Wrapper_MdPrefixRejector(this.parentView.injectorGet(import11.MATERIAL_COMPATIBILITY_MODE,this.parentIndex,(null as any)));
    this._MdIcon_13_4 = new import18.Wrapper_MdIcon(new import19.ElementRef(this._el_13),this.renderer,this.parentView.injectorGet(import20.MdIconRegistry,this.parentIndex));
    this._text_14 = this.renderer.createText((null as any),'close',this.debug(14,7,69));
    this.compView_13.create(this._MdIcon_13_4.context);
    this._text_15 = this.renderer.createText((null as any),'\n    ',this.debug(15,7,84));
    this.compView_11.create(this._MdButton_11_4.context);
    this._text_16 = this.renderer.createText(this._el_3,'\n    ',this.debug(16,8,13));
    this._el_17 = import3.createRenderElement(this.renderer,this._el_3,'button',new import3.InlineArray4(4,'class','messageActivityClick','md-button',''),this.debug(17,9,4));
    this.compView_17 = new import17.View_MdButton0(this.viewUtils,this,17,this._el_17);
    this._MdPrefixRejector_17_3 = new import15.Wrapper_MdPrefixRejector(this.parentView.injectorGet(import11.MATERIAL_COMPATIBILITY_MODE,this.parentIndex,(null as any)));
    this._MdButton_17_4 = new import17.Wrapper_MdButton(new import19.ElementRef(this._el_17),this.renderer);
    this._MdButtonCssMatStyler_17_5 = new import17.Wrapper_MdButtonCssMatStyler();
    this._text_18 = this.renderer.createText((null as any),'\n    ',this.debug(18,9,74));
    this._el_19 = import3.createRenderElement(this.renderer,(null as any),'p',import3.EMPTY_INLINE_ARRAY,this.debug(19,10,4));
    this._text_20 = this.renderer.createText(this._el_19,'',this.debug(20,10,7));
    this._text_21 = this.renderer.createText((null as any),'\n    ',this.debug(21,10,31));
    this.compView_17.create(this._MdButton_17_4.context);
    this._text_22 = this.renderer.createText(this._el_3,'\n    ',this.debug(22,11,13));
    this._text_23 = this.renderer.createText((null as any),'\n',this.debug(23,12,10));
    this.compView_1.create(this._MdCard_1_4.context);
    this._text_24 = this.renderer.createText(parentRenderNode,'\n\n  ',this.debug(24,13,10));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_11,new import3.InlineArray8(8,'click',(null as any),'mousedown',(null as any),'focus',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_11));
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_17,new import3.InlineArray8(8,'click',(null as any),'mousedown',(null as any),'focus',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_17));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._text_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._text_21,
      this._text_22,
      this._text_23,
      this._text_24
    ]
    ),[
      disposable_0,
      disposable_1
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import11.MdPrefixRejector) && ((13 <= requestNodeIndex) && (requestNodeIndex <= 14)))) { return this._MdPrefixRejector_13_3.context; }
    if (((token === import14.MdIcon) && ((13 <= requestNodeIndex) && (requestNodeIndex <= 14)))) { return this._MdIcon_13_4.context; }
    if (((token === import11.MdPrefixRejector) && ((11 <= requestNodeIndex) && (requestNodeIndex <= 15)))) { return this._MdPrefixRejector_11_3.context; }
    if (((token === import13.MdButton) && ((11 <= requestNodeIndex) && (requestNodeIndex <= 15)))) { return this._MdButton_11_4.context; }
    if (((token === import13.MdIconButtonCssMatStyler) && ((11 <= requestNodeIndex) && (requestNodeIndex <= 15)))) { return this._MdIconButtonCssMatStyler_11_5.context; }
    if (((token === import11.MdPrefixRejector) && ((17 <= requestNodeIndex) && (requestNodeIndex <= 21)))) { return this._MdPrefixRejector_17_3.context; }
    if (((token === import13.MdButton) && ((17 <= requestNodeIndex) && (requestNodeIndex <= 21)))) { return this._MdButton_17_4.context; }
    if (((token === import13.MdButtonCssMatStyler) && ((17 <= requestNodeIndex) && (requestNodeIndex <= 21)))) { return this._MdButtonCssMatStyler_17_5.context; }
    if (((token === import11.MdPrefixRejector) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 23)))) { return this._MdPrefixRejector_1_3.context; }
    if (((token === import12.MdCard) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 23)))) { return this._MdCard_1_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.debug(1,1,4);
    this._MdPrefixRejector_1_3.ngDoCheck(this,this._el_1,throwOnChange);
    if (this._MdCard_1_4.ngDoCheck(this,this._el_1,throwOnChange)) { this.compView_1.markAsCheckOnce(); }
    this.debug(11,6,4);
    this._MdPrefixRejector_11_3.ngDoCheck(this,this._el_11,throwOnChange);
    if (this._MdButton_11_4.ngDoCheck(this,this._el_11,throwOnChange)) { this.compView_11.markAsCheckOnce(); }
    this._MdIconButtonCssMatStyler_11_5.ngDoCheck(this,this._el_11,throwOnChange);
    this.debug(13,7,8);
    this._MdPrefixRejector_13_3.ngDoCheck(this,this._el_13,throwOnChange);
    if (this._MdIcon_13_4.ngDoCheck(this,this._el_13,throwOnChange)) { this.compView_13.markAsCheckOnce(); }
    this.debug(17,9,4);
    this._MdPrefixRejector_17_3.ngDoCheck(this,this._el_17,throwOnChange);
    if (this._MdButton_17_4.ngDoCheck(this,this._el_17,throwOnChange)) { this.compView_17.markAsCheckOnce(); }
    this._MdButtonCssMatStyler_17_5.ngDoCheck(this,this._el_17,throwOnChange);
    this._MdCard_1_4.checkHost(this,this.compView_1,this._el_1,throwOnChange);
    this.debug(6,4,8);
    const currVal_39:any = import3.inlineInterpolate(1,'',this.context.activity.header,'');
    if (import3.checkBinding(throwOnChange,this._expr_39,currVal_39)) {
      this.renderer.setText(this._text_6,currVal_39);
      this._expr_39 = currVal_39;
    }
    this.debug(9,5,8);
    const currVal_40:any = import3.inlineInterpolate(1,'',this.context.activity.createdAt,'');
    if (import3.checkBinding(throwOnChange,this._expr_40,currVal_40)) {
      this.renderer.setText(this._text_9,currVal_40);
      this._expr_40 = currVal_40;
    }
    this._MdButton_11_4.checkHost(this,this.compView_11,this._el_11,throwOnChange);
    this._MdIconButtonCssMatStyler_11_5.checkHost(this,this.compView_11,this._el_11,throwOnChange);
    this._MdIcon_13_4.checkHost(this,this.compView_13,this._el_13,throwOnChange);
    this._MdButton_17_4.checkHost(this,this.compView_17,this._el_17,throwOnChange);
    this._MdButtonCssMatStyler_17_5.checkHost(this,this.compView_17,this._el_17,throwOnChange);
    this.debug(20,10,7);
    const currVal_41:any = import3.inlineInterpolate(1,'',this.context.activity.content,'');
    if (import3.checkBinding(throwOnChange,this._expr_41,currVal_41)) {
      this.renderer.setText(this._text_20,currVal_41);
      this._expr_41 = currVal_41;
    }
    this.compView_1.internalDetectChanges(throwOnChange);
    this.compView_11.internalDetectChanges(throwOnChange);
    this.compView_13.internalDetectChanges(throwOnChange);
    this.compView_17.internalDetectChanges(throwOnChange);
    if (!throwOnChange) {
      this.debug(13,7,8);
      this._MdIcon_13_4.context.ngAfterViewChecked();
    }
  }
  destroyInternal():void {
    this.compView_1.destroy();
    this.compView_11.destroy();
    this.compView_13.destroy();
    this.compView_17.destroy();
    this.debug(13,7,8);
    this.debug(11,6,4);
    this.debug(17,9,4);
  }
  visitProjectableNodesInternal(nodeIndex:number,ngContentIndex:number,cb:any,ctx:any):void {
    if (((nodeIndex == 1) && (ngContentIndex == 0))) {
      cb(this._text_2,ctx);
      cb(this._el_3,ctx);
      cb(this._text_23,ctx);
    }
    if (((nodeIndex == 11) && (ngContentIndex == 0))) {
      cb(this._text_12,ctx);
      cb(this._el_13,ctx);
      cb(this._text_15,ctx);
    }
    if (((nodeIndex == 13) && (ngContentIndex == 0))) { cb(this._text_14,ctx); }
    if (((nodeIndex == 17) && (ngContentIndex == 0))) {
      cb(this._text_18,ctx);
      cb(this._el_19,ctx);
      cb(this._text_21,ctx);
    }
  }
  handleEvent_11(eventName:string,$event:any):boolean {
    this.debug(11,6,4);
    this.compView_11.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._MdButton_11_4.handleEvent(eventName,$event) && result);
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.onRemove()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_17(eventName:string,$event:any):boolean {
    this.debug(17,9,4);
    this.compView_17.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._MdButton_17_4.handleEvent(eventName,$event) && result);
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.onNavigate()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}