/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from './tasks-master.container';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/debug_context';
import * as import3 from '@angular/core/src/render/api';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/metadata/view';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/constants';
import * as import8 from '@angular/core/src/linker/component_factory';
import * as import9 from '../../tasks.sandbox';
import * as import10 from '@angular/router/src/router_state';
import * as import11 from '@angular/router/src/router';
import * as import12 from '@angular/material/core/compatibility/compatibility';
import * as import13 from '@angular/material/button/button';
import * as import14 from '@angular/flex-layout/flexbox/api/layout';
import * as import15 from '@angular/material/icon/icon';
import * as import16 from '../../../../node_modules/@angular/material/core/compatibility/compatibility.ngfactory';
import * as import17 from '../../../../node_modules/@angular/material/button/button.ngfactory';
import * as import18 from '../../../../node_modules/@angular/flex-layout/flexbox/api/layout.ngfactory';
import * as import19 from '../../../../node_modules/@angular/material/icon/icon.ngfactory';
import * as import20 from '@angular/core/src/linker/element_ref';
import * as import21 from '@angular/flex-layout/media-query/media-monitor';
import * as import22 from '@angular/material/icon/icon-registry';
export class Wrapper_TasksMasterContainer {
  /*private*/ _eventHandler:Function;
  context:import0.TasksMasterContainer;
  /*private*/ _changed:boolean;
  constructor(p0:any,p1:any,p2:any) {
    this._changed = false;
    this.context = new import0.TasksMasterContainer(p0,p1,p2);
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
const nodeDebugInfos_TasksMasterContainer_Host0:import2.StaticNodeDebugInfo[] = [new import2.StaticNodeDebugInfo([import0.TasksMasterContainer],import0.TasksMasterContainer,{})];
var renderType_TasksMasterContainer_Host:import3.RenderComponentType = import4.createRenderComponentType('',0,import5.ViewEncapsulation.None,([] as any[]),{});
class View_TasksMasterContainer_Host0 extends import1.DebugAppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.TasksMasterContainer>;
  _TasksMasterContainer_0_3:Wrapper_TasksMasterContainer;
  constructor(viewUtils:import4.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_TasksMasterContainer_Host0,renderType_TasksMasterContainer_Host,import6.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_TasksMasterContainer_Host0);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import4.selectOrCreateRenderHostElement(this.renderer,'tasks-master',import4.EMPTY_INLINE_ARRAY,rootSelector,this.debug(0,0,0));
    this.compView_0 = new View_TasksMasterContainer0(this.viewUtils,this,0,this._el_0);
    this._TasksMasterContainer_0_3 = new Wrapper_TasksMasterContainer(this.injectorGet(import9.TasksSandbox,this.parentIndex),this.injectorGet(import10.ActivatedRoute,this.parentIndex),this.injectorGet(import11.Router,this.parentIndex));
    this.compView_0.create(this._TasksMasterContainer_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import8.ComponentRef_<any>(0,this,this._el_0,this._TasksMasterContainer_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.TasksMasterContainer) && (0 === requestNodeIndex))) { return this._TasksMasterContainer_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.debug(0,0,0);
    if (this._TasksMasterContainer_0_3.ngDoCheck(this,this._el_0,throwOnChange)) { this.compView_0.markAsCheckOnce(); }
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const TasksMasterContainerNgFactory:import8.ComponentFactory<import0.TasksMasterContainer> = new import8.ComponentFactory<import0.TasksMasterContainer>('tasks-master',View_TasksMasterContainer_Host0,import0.TasksMasterContainer);
const styles_TasksMasterContainer:any[] = ([] as any[]);
const nodeDebugInfos_TasksMasterContainer0:import2.StaticNodeDebugInfo[] = [
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo([
    import12.MdPrefixRejector,
    import13.MdButton,
    import13.MdButtonCssMatStyler
  ]
  ,import13.MdButton,{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo([import14.LayoutDirective],(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo([
    import12.MdPrefixRejector,
    import15.MdIcon
  ]
  ,import15.MdIcon,{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo([
    import12.MdPrefixRejector,
    import13.MdButton,
    import13.MdButtonCssMatStyler
  ]
  ,import13.MdButton,{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo([import14.LayoutDirective],(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo([
    import12.MdPrefixRejector,
    import15.MdIcon
  ]
  ,import15.MdIcon,{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo([
    import12.MdPrefixRejector,
    import13.MdButton,
    import13.MdButtonCssMatStyler
  ]
  ,import13.MdButton,{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo([import14.LayoutDirective],(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo([
    import12.MdPrefixRejector,
    import15.MdIcon
  ]
  ,import15.MdIcon,{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo([
    import12.MdPrefixRejector,
    import13.MdButton,
    import13.MdButtonCssMatStyler
  ]
  ,import13.MdButton,{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo([import14.LayoutDirective],(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo([
    import12.MdPrefixRejector,
    import15.MdIcon
  ]
  ,import15.MdIcon,{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo([
    import12.MdPrefixRejector,
    import13.MdButton,
    import13.MdButtonCssMatStyler
  ]
  ,import13.MdButton,{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo([import14.LayoutDirective],(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo([
    import12.MdPrefixRejector,
    import15.MdIcon
  ]
  ,import15.MdIcon,{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{})
]
;
var renderType_TasksMasterContainer:import3.RenderComponentType = import4.createRenderComponentType('/Users/jonoforbes/Developer/Ether/ether-app/src/tasks/containers/tasks-master/tasks-master.container.ts class TasksMasterContainer - inline template',0,import5.ViewEncapsulation.None,styles_TasksMasterContainer,{});
export class View_TasksMasterContainer0 extends import1.DebugAppView<import0.TasksMasterContainer> {
  _text_0:any;
  _el_1:any;
  compView_1:import1.AppView<import13.MdButton>;
  _MdPrefixRejector_1_3:import16.Wrapper_MdPrefixRejector;
  _MdButton_1_4:import17.Wrapper_MdButton;
  _MdButtonCssMatStyler_1_5:import17.Wrapper_MdButtonCssMatStyler;
  _text_2:any;
  _el_3:any;
  _LayoutDirective_3_3:import18.Wrapper_LayoutDirective;
  _text_4:any;
  _el_5:any;
  compView_5:import1.AppView<import15.MdIcon>;
  _MdPrefixRejector_5_3:import16.Wrapper_MdPrefixRejector;
  _MdIcon_5_4:import19.Wrapper_MdIcon;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _text_9:any;
  _text_10:any;
  _text_11:any;
  _el_12:any;
  compView_12:import1.AppView<import13.MdButton>;
  _MdPrefixRejector_12_3:import16.Wrapper_MdPrefixRejector;
  _MdButton_12_4:import17.Wrapper_MdButton;
  _MdButtonCssMatStyler_12_5:import17.Wrapper_MdButtonCssMatStyler;
  _text_13:any;
  _el_14:any;
  _LayoutDirective_14_3:import18.Wrapper_LayoutDirective;
  _text_15:any;
  _el_16:any;
  compView_16:import1.AppView<import15.MdIcon>;
  _MdPrefixRejector_16_3:import16.Wrapper_MdPrefixRejector;
  _MdIcon_16_4:import19.Wrapper_MdIcon;
  _text_17:any;
  _el_18:any;
  _text_19:any;
  _text_20:any;
  _text_21:any;
  _text_22:any;
  _el_23:any;
  compView_23:import1.AppView<import13.MdButton>;
  _MdPrefixRejector_23_3:import16.Wrapper_MdPrefixRejector;
  _MdButton_23_4:import17.Wrapper_MdButton;
  _MdButtonCssMatStyler_23_5:import17.Wrapper_MdButtonCssMatStyler;
  _text_24:any;
  _el_25:any;
  _LayoutDirective_25_3:import18.Wrapper_LayoutDirective;
  _text_26:any;
  _el_27:any;
  compView_27:import1.AppView<import15.MdIcon>;
  _MdPrefixRejector_27_3:import16.Wrapper_MdPrefixRejector;
  _MdIcon_27_4:import19.Wrapper_MdIcon;
  _text_28:any;
  _el_29:any;
  _text_30:any;
  _text_31:any;
  _text_32:any;
  _text_33:any;
  _el_34:any;
  compView_34:import1.AppView<import13.MdButton>;
  _MdPrefixRejector_34_3:import16.Wrapper_MdPrefixRejector;
  _MdButton_34_4:import17.Wrapper_MdButton;
  _MdButtonCssMatStyler_34_5:import17.Wrapper_MdButtonCssMatStyler;
  _text_35:any;
  _el_36:any;
  _LayoutDirective_36_3:import18.Wrapper_LayoutDirective;
  _text_37:any;
  _el_38:any;
  compView_38:import1.AppView<import15.MdIcon>;
  _MdPrefixRejector_38_3:import16.Wrapper_MdPrefixRejector;
  _MdIcon_38_4:import19.Wrapper_MdIcon;
  _text_39:any;
  _el_40:any;
  _text_41:any;
  _text_42:any;
  _text_43:any;
  _text_44:any;
  _el_45:any;
  compView_45:import1.AppView<import13.MdButton>;
  _MdPrefixRejector_45_3:import16.Wrapper_MdPrefixRejector;
  _MdButton_45_4:import17.Wrapper_MdButton;
  _MdButtonCssMatStyler_45_5:import17.Wrapper_MdButtonCssMatStyler;
  _text_46:any;
  _el_47:any;
  _LayoutDirective_47_3:import18.Wrapper_LayoutDirective;
  _text_48:any;
  _el_49:any;
  compView_49:import1.AppView<import15.MdIcon>;
  _MdPrefixRejector_49_3:import16.Wrapper_MdPrefixRejector;
  _MdIcon_49_4:import19.Wrapper_MdIcon;
  _text_50:any;
  _el_51:any;
  _text_52:any;
  _text_53:any;
  _text_54:any;
  _text_55:any;
  constructor(viewUtils:import4.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_TasksMasterContainer0,renderType_TasksMasterContainer,import6.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckOnce,nodeDebugInfos_TasksMasterContainer0);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n\n        \n     \n        \n        ',this.debug(0,0,0));
    this._el_1 = import4.createRenderElement(this.renderer,parentRenderNode,'button',new import4.InlineArray4(4,'md-button','','style','text-align: left !important; height: 40px; width: 100%; margin-top: 20px'),this.debug(1,5,8));
    this.compView_1 = new import17.View_MdButton0(this.viewUtils,this,1,this._el_1);
    this._MdPrefixRejector_1_3 = new import16.Wrapper_MdPrefixRejector(this.parentView.injectorGet(import12.MATERIAL_COMPATIBILITY_MODE,this.parentIndex,(null as any)));
    this._MdButton_1_4 = new import17.Wrapper_MdButton(new import20.ElementRef(this._el_1),this.renderer);
    this._MdButtonCssMatStyler_1_5 = new import17.Wrapper_MdButtonCssMatStyler();
    this._text_2 = this.renderer.createText((null as any),'\n          ',this.debug(2,5,133));
    this._el_3 = import4.createRenderElement(this.renderer,(null as any),'div',new import4.InlineArray2(2,'fxLayout','row'),this.debug(3,6,10));
    this._LayoutDirective_3_3 = new import18.Wrapper_LayoutDirective(this.parentView.injectorGet(import21.MediaMonitor,this.parentIndex),new import20.ElementRef(this._el_3),this.renderer);
    this._text_4 = this.renderer.createText(this._el_3,'\n          ',this.debug(4,6,30));
    this._el_5 = import4.createRenderElement(this.renderer,this._el_3,'md-icon',new import4.InlineArray4(4,'role','img','style','color: #838383; margin-right: 10px; margin-top: -5px'),this.debug(5,7,10));
    this.compView_5 = new import19.View_MdIcon0(this.viewUtils,this,5,this._el_5);
    this._MdPrefixRejector_5_3 = new import16.Wrapper_MdPrefixRejector(this.parentView.injectorGet(import12.MATERIAL_COMPATIBILITY_MODE,this.parentIndex,(null as any)));
    this._MdIcon_5_4 = new import19.Wrapper_MdIcon(new import20.ElementRef(this._el_5),this.renderer,this.parentView.injectorGet(import22.MdIconRegistry,this.parentIndex));
    this._text_6 = this.renderer.createText((null as any),'view_day',this.debug(6,7,80));
    this.compView_5.create(this._MdIcon_5_4.context);
    this._el_7 = import4.createRenderElement(this.renderer,this._el_3,'p',import4.EMPTY_INLINE_ARRAY,this.debug(7,7,98));
    this._text_8 = this.renderer.createText(this._el_7,'Tasks for Today',this.debug(8,7,101));
    this._text_9 = this.renderer.createText(this._el_3,'\n          ',this.debug(9,7,120));
    this._text_10 = this.renderer.createText((null as any),'\n        ',this.debug(10,8,16));
    this.compView_1.create(this._MdButton_1_4.context);
    this._text_11 = this.renderer.createText(parentRenderNode,'\n        ',this.debug(11,9,17));
    this._el_12 = import4.createRenderElement(this.renderer,parentRenderNode,'button',new import4.InlineArray4(4,'md-button','','style','text-align: left !important; height: 40px; width: 100%'),this.debug(12,10,8));
    this.compView_12 = new import17.View_MdButton0(this.viewUtils,this,12,this._el_12);
    this._MdPrefixRejector_12_3 = new import16.Wrapper_MdPrefixRejector(this.parentView.injectorGet(import12.MATERIAL_COMPATIBILITY_MODE,this.parentIndex,(null as any)));
    this._MdButton_12_4 = new import17.Wrapper_MdButton(new import20.ElementRef(this._el_12),this.renderer);
    this._MdButtonCssMatStyler_12_5 = new import17.Wrapper_MdButtonCssMatStyler();
    this._text_13 = this.renderer.createText((null as any),'\n          ',this.debug(13,10,118));
    this._el_14 = import4.createRenderElement(this.renderer,(null as any),'div',new import4.InlineArray2(2,'fxLayout','row'),this.debug(14,11,10));
    this._LayoutDirective_14_3 = new import18.Wrapper_LayoutDirective(this.parentView.injectorGet(import21.MediaMonitor,this.parentIndex),new import20.ElementRef(this._el_14),this.renderer);
    this._text_15 = this.renderer.createText(this._el_14,'\n          ',this.debug(15,11,30));
    this._el_16 = import4.createRenderElement(this.renderer,this._el_14,'md-icon',new import4.InlineArray4(4,'role','img','style','color: #838383; margin-right: 10px; margin-top: -5px'),this.debug(16,12,10));
    this.compView_16 = new import19.View_MdIcon0(this.viewUtils,this,16,this._el_16);
    this._MdPrefixRejector_16_3 = new import16.Wrapper_MdPrefixRejector(this.parentView.injectorGet(import12.MATERIAL_COMPATIBILITY_MODE,this.parentIndex,(null as any)));
    this._MdIcon_16_4 = new import19.Wrapper_MdIcon(new import20.ElementRef(this._el_16),this.renderer,this.parentView.injectorGet(import22.MdIconRegistry,this.parentIndex));
    this._text_17 = this.renderer.createText((null as any),'view_week',this.debug(17,12,80));
    this.compView_16.create(this._MdIcon_16_4.context);
    this._el_18 = import4.createRenderElement(this.renderer,this._el_14,'p',import4.EMPTY_INLINE_ARRAY,this.debug(18,12,99));
    this._text_19 = this.renderer.createText(this._el_18,'Tasks for This Week',this.debug(19,12,102));
    this._text_20 = this.renderer.createText(this._el_14,'\n          ',this.debug(20,12,125));
    this._text_21 = this.renderer.createText((null as any),'\n        ',this.debug(21,13,16));
    this.compView_12.create(this._MdButton_12_4.context);
    this._text_22 = this.renderer.createText(parentRenderNode,'\n        ',this.debug(22,14,17));
    this._el_23 = import4.createRenderElement(this.renderer,parentRenderNode,'button',new import4.InlineArray4(4,'md-button','','style','text-align: left !important; height: 40px; width: 100%'),this.debug(23,15,8));
    this.compView_23 = new import17.View_MdButton0(this.viewUtils,this,23,this._el_23);
    this._MdPrefixRejector_23_3 = new import16.Wrapper_MdPrefixRejector(this.parentView.injectorGet(import12.MATERIAL_COMPATIBILITY_MODE,this.parentIndex,(null as any)));
    this._MdButton_23_4 = new import17.Wrapper_MdButton(new import20.ElementRef(this._el_23),this.renderer);
    this._MdButtonCssMatStyler_23_5 = new import17.Wrapper_MdButtonCssMatStyler();
    this._text_24 = this.renderer.createText((null as any),'\n          ',this.debug(24,15,118));
    this._el_25 = import4.createRenderElement(this.renderer,(null as any),'div',new import4.InlineArray2(2,'fxLayout','row'),this.debug(25,16,10));
    this._LayoutDirective_25_3 = new import18.Wrapper_LayoutDirective(this.parentView.injectorGet(import21.MediaMonitor,this.parentIndex),new import20.ElementRef(this._el_25),this.renderer);
    this._text_26 = this.renderer.createText(this._el_25,'\n          ',this.debug(26,16,30));
    this._el_27 = import4.createRenderElement(this.renderer,this._el_25,'md-icon',new import4.InlineArray4(4,'role','img','style','color: #838383; margin-right: 10px; margin-top: -5px'),this.debug(27,17,10));
    this.compView_27 = new import19.View_MdIcon0(this.viewUtils,this,27,this._el_27);
    this._MdPrefixRejector_27_3 = new import16.Wrapper_MdPrefixRejector(this.parentView.injectorGet(import12.MATERIAL_COMPATIBILITY_MODE,this.parentIndex,(null as any)));
    this._MdIcon_27_4 = new import19.Wrapper_MdIcon(new import20.ElementRef(this._el_27),this.renderer,this.parentView.injectorGet(import22.MdIconRegistry,this.parentIndex));
    this._text_28 = this.renderer.createText((null as any),'view_week',this.debug(28,17,80));
    this.compView_27.create(this._MdIcon_27_4.context);
    this._el_29 = import4.createRenderElement(this.renderer,this._el_25,'p',import4.EMPTY_INLINE_ARRAY,this.debug(29,17,99));
    this._text_30 = this.renderer.createText(this._el_29,'Tasks for Next Week',this.debug(30,17,102));
    this._text_31 = this.renderer.createText(this._el_25,'\n          ',this.debug(31,17,125));
    this._text_32 = this.renderer.createText((null as any),'\n        ',this.debug(32,18,16));
    this.compView_23.create(this._MdButton_23_4.context);
    this._text_33 = this.renderer.createText(parentRenderNode,'\n        ',this.debug(33,19,17));
    this._el_34 = import4.createRenderElement(this.renderer,parentRenderNode,'button',new import4.InlineArray4(4,'md-button','','style','text-align: left !important; height: 40px; width: 100%'),this.debug(34,20,8));
    this.compView_34 = new import17.View_MdButton0(this.viewUtils,this,34,this._el_34);
    this._MdPrefixRejector_34_3 = new import16.Wrapper_MdPrefixRejector(this.parentView.injectorGet(import12.MATERIAL_COMPATIBILITY_MODE,this.parentIndex,(null as any)));
    this._MdButton_34_4 = new import17.Wrapper_MdButton(new import20.ElementRef(this._el_34),this.renderer);
    this._MdButtonCssMatStyler_34_5 = new import17.Wrapper_MdButtonCssMatStyler();
    this._text_35 = this.renderer.createText((null as any),'\n          ',this.debug(35,20,115));
    this._el_36 = import4.createRenderElement(this.renderer,(null as any),'div',new import4.InlineArray2(2,'fxLayout','row'),this.debug(36,21,10));
    this._LayoutDirective_36_3 = new import18.Wrapper_LayoutDirective(this.parentView.injectorGet(import21.MediaMonitor,this.parentIndex),new import20.ElementRef(this._el_36),this.renderer);
    this._text_37 = this.renderer.createText(this._el_36,'\n          ',this.debug(37,21,30));
    this._el_38 = import4.createRenderElement(this.renderer,this._el_36,'md-icon',new import4.InlineArray4(4,'role','img','style','color: #838383; margin-right: 10px; margin-top: -5px'),this.debug(38,22,10));
    this.compView_38 = new import19.View_MdIcon0(this.viewUtils,this,38,this._el_38);
    this._MdPrefixRejector_38_3 = new import16.Wrapper_MdPrefixRejector(this.parentView.injectorGet(import12.MATERIAL_COMPATIBILITY_MODE,this.parentIndex,(null as any)));
    this._MdIcon_38_4 = new import19.Wrapper_MdIcon(new import20.ElementRef(this._el_38),this.renderer,this.parentView.injectorGet(import22.MdIconRegistry,this.parentIndex));
    this._text_39 = this.renderer.createText((null as any),'today',this.debug(39,22,80));
    this.compView_38.create(this._MdIcon_38_4.context);
    this._el_40 = import4.createRenderElement(this.renderer,this._el_36,'p',import4.EMPTY_INLINE_ARRAY,this.debug(40,22,95));
    this._text_41 = this.renderer.createText(this._el_40,'Tasks for This Month',this.debug(41,22,98));
    this._text_42 = this.renderer.createText(this._el_36,'\n          ',this.debug(42,22,122));
    this._text_43 = this.renderer.createText((null as any),'\n        ',this.debug(43,23,16));
    this.compView_34.create(this._MdButton_34_4.context);
    this._text_44 = this.renderer.createText(parentRenderNode,'\n        ',this.debug(44,24,17));
    this._el_45 = import4.createRenderElement(this.renderer,parentRenderNode,'button',new import4.InlineArray4(4,'md-button','','style','text-align: left !important; height: 40px; width: 100%'),this.debug(45,25,8));
    this.compView_45 = new import17.View_MdButton0(this.viewUtils,this,45,this._el_45);
    this._MdPrefixRejector_45_3 = new import16.Wrapper_MdPrefixRejector(this.parentView.injectorGet(import12.MATERIAL_COMPATIBILITY_MODE,this.parentIndex,(null as any)));
    this._MdButton_45_4 = new import17.Wrapper_MdButton(new import20.ElementRef(this._el_45),this.renderer);
    this._MdButtonCssMatStyler_45_5 = new import17.Wrapper_MdButtonCssMatStyler();
    this._text_46 = this.renderer.createText((null as any),'\n          ',this.debug(46,25,113));
    this._el_47 = import4.createRenderElement(this.renderer,(null as any),'div',new import4.InlineArray2(2,'fxLayout','row'),this.debug(47,26,10));
    this._LayoutDirective_47_3 = new import18.Wrapper_LayoutDirective(this.parentView.injectorGet(import21.MediaMonitor,this.parentIndex),new import20.ElementRef(this._el_47),this.renderer);
    this._text_48 = this.renderer.createText(this._el_47,'\n          ',this.debug(48,26,30));
    this._el_49 = import4.createRenderElement(this.renderer,this._el_47,'md-icon',new import4.InlineArray4(4,'role','img','style','color: #838383; margin-right: 10px; margin-top: -5px'),this.debug(49,27,10));
    this.compView_49 = new import19.View_MdIcon0(this.viewUtils,this,49,this._el_49);
    this._MdPrefixRejector_49_3 = new import16.Wrapper_MdPrefixRejector(this.parentView.injectorGet(import12.MATERIAL_COMPATIBILITY_MODE,this.parentIndex,(null as any)));
    this._MdIcon_49_4 = new import19.Wrapper_MdIcon(new import20.ElementRef(this._el_49),this.renderer,this.parentView.injectorGet(import22.MdIconRegistry,this.parentIndex));
    this._text_50 = this.renderer.createText((null as any),'chevron_right',this.debug(50,27,80));
    this.compView_49.create(this._MdIcon_49_4.context);
    this._el_51 = import4.createRenderElement(this.renderer,this._el_47,'p',import4.EMPTY_INLINE_ARRAY,this.debug(51,27,103));
    this._text_52 = this.renderer.createText(this._el_51,'All Tasks',this.debug(52,27,106));
    this._text_53 = this.renderer.createText(this._el_47,'\n          ',this.debug(53,27,119));
    this._text_54 = this.renderer.createText((null as any),'\n        ',this.debug(54,28,16));
    this.compView_45.create(this._MdButton_45_4.context);
    this._text_55 = this.renderer.createText(parentRenderNode,'\n\n       \n    \n    ',this.debug(55,29,17));
    var disposable_0:Function = import4.subscribeToRenderElement(this,this._el_1,new import4.InlineArray8(8,'click',(null as any),'mousedown',(null as any),'focus',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_1));
    var disposable_1:Function = import4.subscribeToRenderElement(this,this._el_12,new import4.InlineArray8(8,'click',(null as any),'mousedown',(null as any),'focus',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_12));
    var disposable_2:Function = import4.subscribeToRenderElement(this,this._el_23,new import4.InlineArray8(8,'click',(null as any),'mousedown',(null as any),'focus',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_23));
    var disposable_3:Function = import4.subscribeToRenderElement(this,this._el_34,new import4.InlineArray8(8,'click',(null as any),'mousedown',(null as any),'focus',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_34));
    var disposable_4:Function = import4.subscribeToRenderElement(this,this._el_45,new import4.InlineArray8(8,'click',(null as any),'mousedown',(null as any),'focus',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_45));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._text_9,
      this._text_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._text_20,
      this._text_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._el_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._text_31,
      this._text_32,
      this._text_33,
      this._el_34,
      this._text_35,
      this._el_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._el_40,
      this._text_41,
      this._text_42,
      this._text_43,
      this._text_44,
      this._el_45,
      this._text_46,
      this._el_47,
      this._text_48,
      this._el_49,
      this._text_50,
      this._el_51,
      this._text_52,
      this._text_53,
      this._text_54,
      this._text_55
    ]
    ),[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import12.MdPrefixRejector) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._MdPrefixRejector_5_3.context; }
    if (((token === import15.MdIcon) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._MdIcon_5_4.context; }
    if (((token === import14.LayoutDirective) && ((3 <= requestNodeIndex) && (requestNodeIndex <= 9)))) { return this._LayoutDirective_3_3.context; }
    if (((token === import12.MdPrefixRejector) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 10)))) { return this._MdPrefixRejector_1_3.context; }
    if (((token === import13.MdButton) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 10)))) { return this._MdButton_1_4.context; }
    if (((token === import13.MdButtonCssMatStyler) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 10)))) { return this._MdButtonCssMatStyler_1_5.context; }
    if (((token === import12.MdPrefixRejector) && ((16 <= requestNodeIndex) && (requestNodeIndex <= 17)))) { return this._MdPrefixRejector_16_3.context; }
    if (((token === import15.MdIcon) && ((16 <= requestNodeIndex) && (requestNodeIndex <= 17)))) { return this._MdIcon_16_4.context; }
    if (((token === import14.LayoutDirective) && ((14 <= requestNodeIndex) && (requestNodeIndex <= 20)))) { return this._LayoutDirective_14_3.context; }
    if (((token === import12.MdPrefixRejector) && ((12 <= requestNodeIndex) && (requestNodeIndex <= 21)))) { return this._MdPrefixRejector_12_3.context; }
    if (((token === import13.MdButton) && ((12 <= requestNodeIndex) && (requestNodeIndex <= 21)))) { return this._MdButton_12_4.context; }
    if (((token === import13.MdButtonCssMatStyler) && ((12 <= requestNodeIndex) && (requestNodeIndex <= 21)))) { return this._MdButtonCssMatStyler_12_5.context; }
    if (((token === import12.MdPrefixRejector) && ((27 <= requestNodeIndex) && (requestNodeIndex <= 28)))) { return this._MdPrefixRejector_27_3.context; }
    if (((token === import15.MdIcon) && ((27 <= requestNodeIndex) && (requestNodeIndex <= 28)))) { return this._MdIcon_27_4.context; }
    if (((token === import14.LayoutDirective) && ((25 <= requestNodeIndex) && (requestNodeIndex <= 31)))) { return this._LayoutDirective_25_3.context; }
    if (((token === import12.MdPrefixRejector) && ((23 <= requestNodeIndex) && (requestNodeIndex <= 32)))) { return this._MdPrefixRejector_23_3.context; }
    if (((token === import13.MdButton) && ((23 <= requestNodeIndex) && (requestNodeIndex <= 32)))) { return this._MdButton_23_4.context; }
    if (((token === import13.MdButtonCssMatStyler) && ((23 <= requestNodeIndex) && (requestNodeIndex <= 32)))) { return this._MdButtonCssMatStyler_23_5.context; }
    if (((token === import12.MdPrefixRejector) && ((38 <= requestNodeIndex) && (requestNodeIndex <= 39)))) { return this._MdPrefixRejector_38_3.context; }
    if (((token === import15.MdIcon) && ((38 <= requestNodeIndex) && (requestNodeIndex <= 39)))) { return this._MdIcon_38_4.context; }
    if (((token === import14.LayoutDirective) && ((36 <= requestNodeIndex) && (requestNodeIndex <= 42)))) { return this._LayoutDirective_36_3.context; }
    if (((token === import12.MdPrefixRejector) && ((34 <= requestNodeIndex) && (requestNodeIndex <= 43)))) { return this._MdPrefixRejector_34_3.context; }
    if (((token === import13.MdButton) && ((34 <= requestNodeIndex) && (requestNodeIndex <= 43)))) { return this._MdButton_34_4.context; }
    if (((token === import13.MdButtonCssMatStyler) && ((34 <= requestNodeIndex) && (requestNodeIndex <= 43)))) { return this._MdButtonCssMatStyler_34_5.context; }
    if (((token === import12.MdPrefixRejector) && ((49 <= requestNodeIndex) && (requestNodeIndex <= 50)))) { return this._MdPrefixRejector_49_3.context; }
    if (((token === import15.MdIcon) && ((49 <= requestNodeIndex) && (requestNodeIndex <= 50)))) { return this._MdIcon_49_4.context; }
    if (((token === import14.LayoutDirective) && ((47 <= requestNodeIndex) && (requestNodeIndex <= 53)))) { return this._LayoutDirective_47_3.context; }
    if (((token === import12.MdPrefixRejector) && ((45 <= requestNodeIndex) && (requestNodeIndex <= 54)))) { return this._MdPrefixRejector_45_3.context; }
    if (((token === import13.MdButton) && ((45 <= requestNodeIndex) && (requestNodeIndex <= 54)))) { return this._MdButton_45_4.context; }
    if (((token === import13.MdButtonCssMatStyler) && ((45 <= requestNodeIndex) && (requestNodeIndex <= 54)))) { return this._MdButtonCssMatStyler_45_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.debug(1,5,8);
    this._MdPrefixRejector_1_3.ngDoCheck(this,this._el_1,throwOnChange);
    if (this._MdButton_1_4.ngDoCheck(this,this._el_1,throwOnChange)) { this.compView_1.markAsCheckOnce(); }
    this._MdButtonCssMatStyler_1_5.ngDoCheck(this,this._el_1,throwOnChange);
    this.debug(3,6,15);
    const currVal_3_0_0:any = 'row';
    this._LayoutDirective_3_3.check_layout(currVal_3_0_0,throwOnChange,false);
    this._LayoutDirective_3_3.ngDoCheck(this,this._el_3,throwOnChange);
    this.debug(5,7,10);
    this._MdPrefixRejector_5_3.ngDoCheck(this,this._el_5,throwOnChange);
    if (this._MdIcon_5_4.ngDoCheck(this,this._el_5,throwOnChange)) { this.compView_5.markAsCheckOnce(); }
    this.debug(12,10,8);
    this._MdPrefixRejector_12_3.ngDoCheck(this,this._el_12,throwOnChange);
    if (this._MdButton_12_4.ngDoCheck(this,this._el_12,throwOnChange)) { this.compView_12.markAsCheckOnce(); }
    this._MdButtonCssMatStyler_12_5.ngDoCheck(this,this._el_12,throwOnChange);
    this.debug(14,11,15);
    const currVal_14_0_0:any = 'row';
    this._LayoutDirective_14_3.check_layout(currVal_14_0_0,throwOnChange,false);
    this._LayoutDirective_14_3.ngDoCheck(this,this._el_14,throwOnChange);
    this.debug(16,12,10);
    this._MdPrefixRejector_16_3.ngDoCheck(this,this._el_16,throwOnChange);
    if (this._MdIcon_16_4.ngDoCheck(this,this._el_16,throwOnChange)) { this.compView_16.markAsCheckOnce(); }
    this.debug(23,15,8);
    this._MdPrefixRejector_23_3.ngDoCheck(this,this._el_23,throwOnChange);
    if (this._MdButton_23_4.ngDoCheck(this,this._el_23,throwOnChange)) { this.compView_23.markAsCheckOnce(); }
    this._MdButtonCssMatStyler_23_5.ngDoCheck(this,this._el_23,throwOnChange);
    this.debug(25,16,15);
    const currVal_25_0_0:any = 'row';
    this._LayoutDirective_25_3.check_layout(currVal_25_0_0,throwOnChange,false);
    this._LayoutDirective_25_3.ngDoCheck(this,this._el_25,throwOnChange);
    this.debug(27,17,10);
    this._MdPrefixRejector_27_3.ngDoCheck(this,this._el_27,throwOnChange);
    if (this._MdIcon_27_4.ngDoCheck(this,this._el_27,throwOnChange)) { this.compView_27.markAsCheckOnce(); }
    this.debug(34,20,8);
    this._MdPrefixRejector_34_3.ngDoCheck(this,this._el_34,throwOnChange);
    if (this._MdButton_34_4.ngDoCheck(this,this._el_34,throwOnChange)) { this.compView_34.markAsCheckOnce(); }
    this._MdButtonCssMatStyler_34_5.ngDoCheck(this,this._el_34,throwOnChange);
    this.debug(36,21,15);
    const currVal_36_0_0:any = 'row';
    this._LayoutDirective_36_3.check_layout(currVal_36_0_0,throwOnChange,false);
    this._LayoutDirective_36_3.ngDoCheck(this,this._el_36,throwOnChange);
    this.debug(38,22,10);
    this._MdPrefixRejector_38_3.ngDoCheck(this,this._el_38,throwOnChange);
    if (this._MdIcon_38_4.ngDoCheck(this,this._el_38,throwOnChange)) { this.compView_38.markAsCheckOnce(); }
    this.debug(45,25,8);
    this._MdPrefixRejector_45_3.ngDoCheck(this,this._el_45,throwOnChange);
    if (this._MdButton_45_4.ngDoCheck(this,this._el_45,throwOnChange)) { this.compView_45.markAsCheckOnce(); }
    this._MdButtonCssMatStyler_45_5.ngDoCheck(this,this._el_45,throwOnChange);
    this.debug(47,26,15);
    const currVal_47_0_0:any = 'row';
    this._LayoutDirective_47_3.check_layout(currVal_47_0_0,throwOnChange,false);
    this._LayoutDirective_47_3.ngDoCheck(this,this._el_47,throwOnChange);
    this.debug(49,27,10);
    this._MdPrefixRejector_49_3.ngDoCheck(this,this._el_49,throwOnChange);
    if (this._MdIcon_49_4.ngDoCheck(this,this._el_49,throwOnChange)) { this.compView_49.markAsCheckOnce(); }
    this._MdButton_1_4.checkHost(this,this.compView_1,this._el_1,throwOnChange);
    this._MdButtonCssMatStyler_1_5.checkHost(this,this.compView_1,this._el_1,throwOnChange);
    this._MdIcon_5_4.checkHost(this,this.compView_5,this._el_5,throwOnChange);
    this._MdButton_12_4.checkHost(this,this.compView_12,this._el_12,throwOnChange);
    this._MdButtonCssMatStyler_12_5.checkHost(this,this.compView_12,this._el_12,throwOnChange);
    this._MdIcon_16_4.checkHost(this,this.compView_16,this._el_16,throwOnChange);
    this._MdButton_23_4.checkHost(this,this.compView_23,this._el_23,throwOnChange);
    this._MdButtonCssMatStyler_23_5.checkHost(this,this.compView_23,this._el_23,throwOnChange);
    this._MdIcon_27_4.checkHost(this,this.compView_27,this._el_27,throwOnChange);
    this._MdButton_34_4.checkHost(this,this.compView_34,this._el_34,throwOnChange);
    this._MdButtonCssMatStyler_34_5.checkHost(this,this.compView_34,this._el_34,throwOnChange);
    this._MdIcon_38_4.checkHost(this,this.compView_38,this._el_38,throwOnChange);
    this._MdButton_45_4.checkHost(this,this.compView_45,this._el_45,throwOnChange);
    this._MdButtonCssMatStyler_45_5.checkHost(this,this.compView_45,this._el_45,throwOnChange);
    this._MdIcon_49_4.checkHost(this,this.compView_49,this._el_49,throwOnChange);
    this.compView_1.internalDetectChanges(throwOnChange);
    this.compView_5.internalDetectChanges(throwOnChange);
    this.compView_12.internalDetectChanges(throwOnChange);
    this.compView_16.internalDetectChanges(throwOnChange);
    this.compView_23.internalDetectChanges(throwOnChange);
    this.compView_27.internalDetectChanges(throwOnChange);
    this.compView_34.internalDetectChanges(throwOnChange);
    this.compView_38.internalDetectChanges(throwOnChange);
    this.compView_45.internalDetectChanges(throwOnChange);
    this.compView_49.internalDetectChanges(throwOnChange);
    if (!throwOnChange) {
      this.debug(5,7,10);
      this._MdIcon_5_4.context.ngAfterViewChecked();
      this.debug(16,12,10);
      this._MdIcon_16_4.context.ngAfterViewChecked();
      this.debug(27,17,10);
      this._MdIcon_27_4.context.ngAfterViewChecked();
      this.debug(38,22,10);
      this._MdIcon_38_4.context.ngAfterViewChecked();
      this.debug(49,27,10);
      this._MdIcon_49_4.context.ngAfterViewChecked();
    }
  }
  destroyInternal():void {
    this.compView_1.destroy();
    this.compView_5.destroy();
    this.compView_12.destroy();
    this.compView_16.destroy();
    this.compView_23.destroy();
    this.compView_27.destroy();
    this.compView_34.destroy();
    this.compView_38.destroy();
    this.compView_45.destroy();
    this.compView_49.destroy();
    this.debug(5,7,10);
    this._LayoutDirective_3_3.ngOnDestroy();
    this.debug(3,6,10);
    this.debug(1,5,8);
    this.debug(16,12,10);
    this._LayoutDirective_14_3.ngOnDestroy();
    this.debug(14,11,10);
    this.debug(12,10,8);
    this.debug(27,17,10);
    this._LayoutDirective_25_3.ngOnDestroy();
    this.debug(25,16,10);
    this.debug(23,15,8);
    this.debug(38,22,10);
    this._LayoutDirective_36_3.ngOnDestroy();
    this.debug(36,21,10);
    this.debug(34,20,8);
    this.debug(49,27,10);
    this._LayoutDirective_47_3.ngOnDestroy();
    this.debug(47,26,10);
  }
  visitProjectableNodesInternal(nodeIndex:number,ngContentIndex:number,cb:any,ctx:any):void {
    if (((nodeIndex == 1) && (ngContentIndex == 0))) {
      cb(this._text_2,ctx);
      cb(this._el_3,ctx);
      cb(this._text_10,ctx);
    }
    if (((nodeIndex == 5) && (ngContentIndex == 0))) { cb(this._text_6,ctx); }
    if (((nodeIndex == 12) && (ngContentIndex == 0))) {
      cb(this._text_13,ctx);
      cb(this._el_14,ctx);
      cb(this._text_21,ctx);
    }
    if (((nodeIndex == 16) && (ngContentIndex == 0))) { cb(this._text_17,ctx); }
    if (((nodeIndex == 23) && (ngContentIndex == 0))) {
      cb(this._text_24,ctx);
      cb(this._el_25,ctx);
      cb(this._text_32,ctx);
    }
    if (((nodeIndex == 27) && (ngContentIndex == 0))) { cb(this._text_28,ctx); }
    if (((nodeIndex == 34) && (ngContentIndex == 0))) {
      cb(this._text_35,ctx);
      cb(this._el_36,ctx);
      cb(this._text_43,ctx);
    }
    if (((nodeIndex == 38) && (ngContentIndex == 0))) { cb(this._text_39,ctx); }
    if (((nodeIndex == 45) && (ngContentIndex == 0))) {
      cb(this._text_46,ctx);
      cb(this._el_47,ctx);
      cb(this._text_54,ctx);
    }
    if (((nodeIndex == 49) && (ngContentIndex == 0))) { cb(this._text_50,ctx); }
  }
  handleEvent_1(eventName:string,$event:any):boolean {
    this.debug(1,5,8);
    this.compView_1.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._MdButton_1_4.handleEvent(eventName,$event) && result);
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.navigateToday()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_12(eventName:string,$event:any):boolean {
    this.debug(12,10,8);
    this.compView_12.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._MdButton_12_4.handleEvent(eventName,$event) && result);
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.navigateThisWeek()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_23(eventName:string,$event:any):boolean {
    this.debug(23,15,8);
    this.compView_23.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._MdButton_23_4.handleEvent(eventName,$event) && result);
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.navigateNextWeek()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_34(eventName:string,$event:any):boolean {
    this.debug(34,20,8);
    this.compView_34.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._MdButton_34_4.handleEvent(eventName,$event) && result);
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.navigateMonth()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_45(eventName:string,$event:any):boolean {
    this.debug(45,25,8);
    this.compView_45.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._MdButton_45_4.handleEvent(eventName,$event) && result);
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.navigateAll()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}