/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from './prod.module';
import * as import2 from '@ngrx/store/src/ng2';
import * as import3 from 'ngrx-undo/src/storeUndo';
import * as import4 from '@angular/material/core/compatibility/compatibility';
import * as import5 from '@angular/material/core/ripple/ripple';
import * as import6 from '@angular/common/src/common_module';
import * as import7 from '@angular/material/core/option/option';
import * as import8 from '@angular/material/core/portal/portal-directives';
import * as import9 from '@angular/material/core/overlay/overlay-directives';
import * as import10 from '@angular/material/autocomplete/index';
import * as import11 from '@angular/material/button/button';
import * as import12 from '@angular/forms/src/directives';
import * as import13 from '@angular/forms/src/form_providers';
import * as import14 from '@angular/material/button-toggle/button-toggle';
import * as import15 from '@angular/material/card/card';
import * as import16 from '@angular/material/chips/chip-list';
import * as import17 from '@angular/material/checkbox/checkbox';
import * as import18 from '@angular/material/core/platform/index';
import * as import19 from '@angular/material/core/a11y/index';
import * as import20 from '@angular/material/dialog/index';
import * as import21 from '@angular/material/core/line/line';
import * as import22 from '@angular/material/grid-list/grid-list';
import * as import23 from '@angular/http/src/http_module';
import * as import24 from '@angular/material/icon/icon';
import * as import25 from '@angular/material/input/index';
import * as import26 from '@angular/material/list/list';
import * as import27 from '@angular/material/menu/menu';
import * as import28 from '@angular/material/progress-bar/progress-bar';
import * as import29 from '@angular/material/progress-spinner/progress-spinner';
import * as import30 from '@angular/material/radio/radio';
import * as import31 from '@angular/material/select/index';
import * as import32 from '@angular/material/sidenav/sidenav';
import * as import33 from '@angular/material/slider/slider';
import * as import34 from '@angular/material/slide-toggle/slide-toggle';
import * as import35 from '@angular/material/snack-bar/index';
import * as import36 from '@angular/material/core/observe-content/observe-content';
import * as import37 from '@angular/material/tabs/tab-group';
import * as import38 from '@angular/material/toolbar/toolbar';
import * as import39 from '@angular/material/tooltip/tooltip';
import * as import40 from '@angular/material/core/rtl/dir';
import * as import41 from '@angular/material/core/style/index';
import * as import42 from '@angular/material/core/projection/projection';
import * as import43 from '@angular/material/module';
import * as import44 from '@angular/flex-layout/media-query/_module';
import * as import45 from '@angular/flex-layout/flexbox/_module';
import * as import46 from '@angular/core/src/application_module';
import * as import47 from '@angular/platform-browser/src/browser';
import * as import48 from '@angular/router/src/router_module';
import * as import49 from 'ng2-date-picker/dp-date-picker.module';
import * as import50 from '@agm/core/core.module';
import * as import51 from 'angular2-froala-wysiwyg/editor/editor.module';
import * as import52 from 'angular2-froala-wysiwyg/view/view.module';
import * as import53 from 'ngx-popover/index';
import * as import54 from 'ng2-accordion/index';
import * as import55 from 'ng2-charts/charts/charts';
import * as import56 from 'ng2-page-scroll/src/ng2-page-scroll.module';
import * as import57 from '../common/index';
import * as import58 from '../authentication/index';
import * as import59 from '../app/index';
import * as import60 from '@angular/common/src/localization';
import * as import61 from '@angular/material/core/overlay/position/overlay-position-builder';
import * as import62 from '@angular/core/src/application_init';
import * as import63 from '@angular/core/src/testability/testability';
import * as import64 from '@angular/core/src/application_ref';
import * as import65 from '@angular/material/core/overlay/overlay';
import * as import66 from '@angular/forms/src/directives/radio_control_value_accessor';
import * as import67 from '@angular/material/core/platform/platform';
import * as import68 from '@angular/material/core/a11y/interactivity-checker';
import * as import69 from '@angular/material/dialog/dialog';
import * as import70 from '@angular/http/src/backends/browser_xhr';
import * as import71 from '@angular/http/src/base_response_options';
import * as import72 from '@angular/http/src/backends/xhr_backend';
import * as import73 from '@angular/http/src/base_request_options';
import * as import74 from '@ngrx/store/src/dispatcher';
import * as import75 from '@angular/platform-browser/src/security/dom_sanitization_service';
import * as import76 from '@angular/platform-browser/src/dom/events/hammer_gestures';
import * as import77 from '@angular/material/snack-bar/snack-bar';
import * as import78 from '@angular/flex-layout/media-query/match-media';
import * as import79 from '@angular/flex-layout/media-query/breakpoints/break-point-registry';
import * as import80 from '@angular/flex-layout/media-query/media-monitor';
import * as import81 from '@angular/flex-layout/media-query/observable-media-service';
import * as import82 from '@angular/core/src/linker/compiler';
import * as import83 from '@angular/platform-browser/src/dom/events/event_manager';
import * as import84 from '@angular/platform-browser/src/dom/shared_styles_host';
import * as import85 from '@angular/platform-browser/src/dom/dom_renderer';
import * as import86 from '@angular/core/src/animation/animation_queue';
import * as import87 from '@angular/core/src/linker/view_utils';
import * as import88 from '@angular/platform-browser/src/browser/title';
import * as import89 from '@angular/forms/src/form_builder';
import * as import90 from 'ng2-date-picker/common/services/dom-appender/dom-appender.service';
import * as import91 from 'ng2-date-picker/common/services/utils/utils.service';
import * as import92 from '../common/common.sandbox';
import * as import93 from '@angular/router/src/url_tree';
import * as import94 from '@angular/router/src/router_outlet_map';
import * as import95 from '@angular/common/src/location/location';
import * as import96 from '@angular/core/src/linker/system_js_ng_module_factory_loader';
import * as import97 from '../common/authenticated.guard';
import * as import98 from '../common/realtime';
import * as import99 from '../authentication/services/authentication.service';
import * as import100 from '../authentication/authentication.sandbox';
import * as import101 from '@agm/core/utils/browser-globals';
import * as import102 from '@agm/core/services/maps-api-loader/lazy-maps-api-loader';
import * as import103 from 'ng2-page-scroll/src/ng2-page-scroll.service';
import * as import104 from '@angular/router/src/router_preloader';
import * as import105 from '../contacts/services/contacts.service';
import * as import106 from '../notes/services/notes.service';
import * as import107 from '../team/services/user-data.service';
import * as import108 from '../messages/services/messages.service';
import * as import109 from '../addresses/services/addresses.service';
import * as import110 from '../client-accounts/services/client-accounts.service';
import * as import111 from '../client-documents/services/client-documents.service';
import * as import112 from '../sales/services/sales.service';
import * as import113 from '../tasks/services/tasks.service';
import * as import114 from '../activities/services/activities.service';
import * as import115 from '../xassets/services/xassets.service';
import * as import116 from '../xliabilities/services/xliabilities.service';
import * as import117 from '../xpensions/services/xpensions.service';
import * as import118 from '../xprotections/services/xprotections.service';
import * as import119 from '../bank-accounts/services/bank-accounts.service';
import * as import120 from '../app/app.sandbox';
import * as import121 from '../addresses/services/googlemaps.service';
import * as import122 from '../addresses/addresses.sandbox';
import * as import123 from '../client-accounts/client-accounts.sandbox';
import * as import124 from '../client-documents/services/box-api.service';
import * as import125 from '../client-documents/client-documents.sandbox';
import * as import126 from '../contacts/contacts.sandbox';
import * as import127 from '../messages/messages.sandbox';
import * as import128 from '../notes/notes.sandbox';
import * as import129 from '../activities/activities.sandbox';
import * as import130 from '../sales/sales.sandbox';
import * as import131 from '../tasks/tasks.sandbox';
import * as import132 from '../team/team.sandbox';
import * as import133 from '../xassets/xassets.sandbox';
import * as import134 from '../xliabilities/xliabilities.sandbox';
import * as import135 from '../xpensions/xpensions.sandbox';
import * as import136 from '../xprotections/xprotections.sandbox';
import * as import137 from '../bank-accounts/bank-accounts.sandbox';
import * as import138 from '@angular/core/src/di/injector';
import * as import139 from '../../node_modules/@angular/material/dialog/dialog-container.ngfactory';
import * as import140 from '../../node_modules/@angular/material/snack-bar/snack-bar-container.ngfactory';
import * as import141 from '../../node_modules/@angular/material/snack-bar/simple-snack-bar.ngfactory';
import * as import142 from '../../node_modules/@angular/material/tooltip/tooltip.ngfactory';
import * as import143 from '../../node_modules/ngx-popover/PopoverContent.ngfactory';
import * as import144 from '../authentication/containers/authentication/authentication.container.ngfactory';
import * as import145 from '../authentication/containers/register/register.container.ngfactory';
import * as import146 from '../contacts/containers/contacts-page/contacts-page.container.ngfactory';
import * as import147 from '../contacts/containers/contacts-master/contacts-master.container.ngfactory';
import * as import148 from '../contacts/containers/add-contact/add-contact.container.ngfactory';
import * as import149 from '../contacts/containers/contacts-detail/contacts-detail.container.ngfactory';
import * as import150 from '../client-accounts/containers/client-accounts-page/client-accounts-page.container.ngfactory';
import * as import151 from '../client-accounts/containers/client-accounts-master/client-accounts-master.container.ngfactory';
import * as import152 from '../client-accounts/containers/client-accounts-overview/client-accounts-overview.container.ngfactory';
import * as import153 from '../client-accounts/containers/client-accounts-detail/client-accounts-detail.container.ngfactory';
import * as import154 from '../notes/containers/notes-page/notes-page.container.ngfactory';
import * as import155 from '../notes/containers/notes-master/notes-master.container.ngfactory';
import * as import156 from '../notes/containers/add-note/add-note.container.ngfactory';
import * as import157 from '../notes/containers/notes-detail/notes-detail.container.ngfactory';
import * as import158 from '../messages/containers/messages-page/messages-page.container.ngfactory';
import * as import159 from '../messages/containers/messages-master/messages-master.container.ngfactory';
import * as import160 from '../messages/containers/messages-detail/messages-detail.container.ngfactory';
import * as import161 from '../team/containers/team-page/team-page.container.ngfactory';
import * as import162 from '../team/containers/team-master/team-master.container.ngfactory';
import * as import163 from '../common/components/default-page/default-page.component.ngfactory';
import * as import164 from '../client-documents/containers/client-documents-page/client-documents-page.container.ngfactory';
import * as import165 from '../client-documents/containers/client-documents-master/client-documents-master.container.ngfactory';
import * as import166 from '../client-documents/containers/client-documents-detail/client-documents-detail.container.ngfactory';
import * as import167 from '../tasks/containers/tasks-page/tasks-page.container.ngfactory';
import * as import168 from '../tasks/containers/tasks-master/tasks-master.container.ngfactory';
import * as import169 from '../tasks/containers/tasks-today/tasks-today.container.ngfactory';
import * as import170 from '../tasks/containers/tasks-week/tasks-week.container.ngfactory';
import * as import171 from '../tasks/containers/tasks-next-week/tasks-next-week.container.ngfactory';
import * as import172 from '../tasks/containers/tasks-month/tasks-month.container.ngfactory';
import * as import173 from '../tasks/containers/tasks-all/tasks-all.container.ngfactory';
import * as import174 from '@angular/material/core/overlay/scroll/scroll-dispatcher';
import * as import175 from '@angular/material/core/overlay/position/viewport-ruler';
import * as import176 from '@angular/core/src/i18n/tokens';
import * as import177 from '@angular/material/core/overlay/overlay-container';
import * as import178 from '@angular/core/src/zone/ng_zone';
import * as import179 from '@angular/material/core/coordination/unique-selection-dispatcher';
import * as import180 from '@angular/material/core/a11y/live-announcer';
import * as import181 from '../statemanagement/rootReducer';
import * as import182 from 'ngrx-undo/src/createReducer';
import * as import183 from '../app/customHttp';
import * as import184 from '@angular/material/icon/icon-registry';
import * as import185 from '@angular/material/core/style/focus-classes';
import * as import186 from '@angular/core/src/application_tokens';
import * as import187 from '@angular/platform-browser/src/dom/events/dom_events';
import * as import188 from '@angular/platform-browser/src/dom/events/key_events';
import * as import189 from '@angular/platform-browser/src/dom/debug/ng_probe';
import * as import190 from '@angular/common/src/location/platform_location';
import * as import191 from '@angular/common/src/location/location_strategy';
import * as import192 from '../authentication/containers/authentication/authentication.container';
import * as import193 from '../authentication/containers/register/register.container';
import * as import194 from '../contacts/containers/contacts-page/contacts-page.container';
import * as import195 from '../contacts/containers/contacts-master/contacts-master.container';
import * as import196 from '../contacts/containers/add-contact/add-contact.container';
import * as import197 from '../contacts/containers/contacts-detail/contacts-detail.container';
import * as import198 from '../client-accounts/containers/client-accounts-page/client-accounts-page.container';
import * as import199 from '../client-accounts/containers/client-accounts-master/client-accounts-master.container';
import * as import200 from '../client-accounts/containers/client-accounts-overview/client-accounts-overview.container';
import * as import201 from '../client-accounts/containers/client-accounts-detail/client-accounts-detail.container';
import * as import202 from '../notes/containers/notes-page/notes-page.container';
import * as import203 from '../notes/containers/notes-master/notes-master.container';
import * as import204 from '../notes/containers/add-note/add-note.container';
import * as import205 from '../notes/containers/notes-detail/notes-detail.container';
import * as import206 from '../messages/containers/messages-page/messages-page.container';
import * as import207 from '../messages/containers/messages-master/messages-master.container';
import * as import208 from '../messages/containers/messages-detail/messages-detail.container';
import * as import209 from '../team/containers/team-page/team-page.container';
import * as import210 from '../team/containers/team-master/team-master.container';
import * as import211 from '../common/components/default-page/default-page.component';
import * as import212 from '../client-documents/containers/client-documents-page/client-documents-page.container';
import * as import213 from '../client-documents/containers/client-documents-master/client-documents-master.container';
import * as import214 from '../client-documents/containers/client-documents-detail/client-documents-detail.container';
import * as import215 from '../tasks/containers/tasks-page/tasks-page.container';
import * as import216 from '../tasks/containers/tasks-master/tasks-master.container';
import * as import217 from '../tasks/containers/tasks-today/tasks-today.container';
import * as import218 from '../tasks/containers/tasks-week/tasks-week.container';
import * as import219 from '../tasks/containers/tasks-next-week/tasks-next-week.container';
import * as import220 from '../tasks/containers/tasks-month/tasks-month.container';
import * as import221 from '../tasks/containers/tasks-all/tasks-all.container';
import * as import222 from '@angular/router/src/url_handling_strategy';
import * as import223 from '@angular/router/src/route_reuse_strategy';
import * as import224 from '@angular/router/src/router';
import * as import225 from '@angular/core/src/console';
import * as import226 from '@angular/core/src/error_handler';
import * as import227 from '@angular/http/src/interfaces';
import * as import228 from '@ngrx/store/src/reducer';
import * as import229 from '@ngrx/store/src/state';
import * as import230 from '@ngrx/store/src/store';
import * as import231 from '@angular/http/src/http';
import * as import232 from '@angular/flex-layout/media-query/breakpoints/break-points';
import * as import233 from '@angular/platform-browser/src/dom/dom_tokens';
import * as import234 from '@angular/platform-browser/src/dom/animation_driver';
import * as import235 from '@angular/core/src/render/api';
import * as import236 from '@angular/core/src/security';
import * as import237 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import238 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import239 from '@angular/core/src/linker/ng_module_factory_loader';
import * as import240 from '@angular/router/src/router_config_loader';
import * as import241 from '@agm/core/services/maps-api-loader/maps-api-loader';
import * as import242 from '@angular/router/src/router_state';
import * as import243 from '@angular/core/src/linker/view';
import * as import244 from '@angular/core/src/linker/debug_context';
import * as import245 from '@angular/core/src/metadata/view';
import * as import246 from '@angular/core/src/linker/view_type';
import * as import247 from '@angular/core/src/change_detection/constants';
import * as import248 from '@angular/core/src/linker/component_factory';
import * as import249 from '../app/containers/application/application.container';
import * as import250 from '../app/containers/application/application.container.ngfactory';
class ProdModuleInjector extends import0.NgModuleInjector<import1.ProdModule> {
  _StoreModule_0:import2.StoreModule;
  _StoreUndoModule_1:import3.StoreUndoModule;
  _CompatibilityModule_2:import4.CompatibilityModule;
  _MdRippleModule_3:import5.MdRippleModule;
  _CommonModule_4:import6.CommonModule;
  _MdOptionModule_5:import7.MdOptionModule;
  _PortalModule_6:import8.PortalModule;
  _OverlayModule_7:import9.OverlayModule;
  _MdAutocompleteModule_8:import10.MdAutocompleteModule;
  _MdButtonModule_9:import11.MdButtonModule;
  _InternalFormsSharedModule_10:import12.InternalFormsSharedModule;
  _FormsModule_11:import13.FormsModule;
  _MdButtonToggleModule_12:import14.MdButtonToggleModule;
  _MdCardModule_13:import15.MdCardModule;
  _MdChipsModule_14:import16.MdChipsModule;
  _MdCheckboxModule_15:import17.MdCheckboxModule;
  _PlatformModule_16:import18.PlatformModule;
  _A11yModule_17:import19.A11yModule;
  _MdDialogModule_18:import20.MdDialogModule;
  _MdLineModule_19:import21.MdLineModule;
  _MdGridListModule_20:import22.MdGridListModule;
  _HttpModule_21:import23.HttpModule;
  _MdIconModule_22:import24.MdIconModule;
  _MdInputModule_23:import25.MdInputModule;
  _MdListModule_24:import26.MdListModule;
  _MdMenuModule_25:import27.MdMenuModule;
  _MdProgressBarModule_26:import28.MdProgressBarModule;
  _MdProgressSpinnerModule_27:import29.MdProgressSpinnerModule;
  _MdRadioModule_28:import30.MdRadioModule;
  _MdSelectModule_29:import31.MdSelectModule;
  _MdSidenavModule_30:import32.MdSidenavModule;
  _MdSliderModule_31:import33.MdSliderModule;
  _MdSlideToggleModule_32:import34.MdSlideToggleModule;
  _MdSnackBarModule_33:import35.MdSnackBarModule;
  _ObserveContentModule_34:import36.ObserveContentModule;
  _MdTabsModule_35:import37.MdTabsModule;
  _MdToolbarModule_36:import38.MdToolbarModule;
  _MdTooltipModule_37:import39.MdTooltipModule;
  _RtlModule_38:import40.RtlModule;
  _StyleModule_39:import41.StyleModule;
  _ProjectionModule_40:import42.ProjectionModule;
  _MaterialModule_41:import43.MaterialModule;
  _MediaQueriesModule_42:import44.MediaQueriesModule;
  _FlexLayoutModule_43:import45.FlexLayoutModule;
  _ApplicationModule_44:import46.ApplicationModule;
  _BrowserModule_45:import47.BrowserModule;
  _ReactiveFormsModule_46:import13.ReactiveFormsModule;
  _ROUTER_FORROOT_GUARD_47:any;
  _RouterModule_48:import48.RouterModule;
  _DpDatePickerModule_49:import49.DpDatePickerModule;
  _AgmCoreModule_50:import50.AgmCoreModule;
  _FroalaEditorModule_51:import51.FroalaEditorModule;
  _FroalaViewModule_52:import52.FroalaViewModule;
  _PopoverModule_53:import53.PopoverModule;
  _AccordionModule_54:import54.AccordionModule;
  _ChartsModule_55:import55.ChartsModule;
  _Ng2PageScrollModule_56:import56.Ng2PageScrollModule;
  _CommonLogicModule_57:import57.CommonLogicModule;
  _AuthenticationModule_58:import58.AuthenticationModule;
  _AppModule_59:import59.AppModule;
  _ProdModule_60:import1.ProdModule;
  __ScrollDispatcher_61:any;
  __ViewportRuler_62:any;
  __LOCALE_ID_63:any;
  __NgLocalization_64:import60.NgLocaleLocalization;
  __OverlayContainer_65:any;
  __OverlayPositionBuilder_66:import61.OverlayPositionBuilder;
  __ErrorHandler_67:any;
  __RouterInitializer_68:import48.RouterInitializer;
  __APP_INITIALIZER_69:any[];
  __ApplicationInitStatus_70:import62.ApplicationInitStatus;
  __Testability_71:import63.Testability;
  _ApplicationRef__72:import64.ApplicationRef_;
  __ApplicationRef_73:any;
  __Overlay_74:import65.Overlay;
  __RadioControlRegistry_75:import66.RadioControlRegistry;
  __UniqueSelectionDispatcher_76:any;
  __Platform_77:import67.Platform;
  __InteractivityChecker_78:import68.InteractivityChecker;
  __LiveAnnouncer_79:any;
  __MdDialog_80:import69.MdDialog;
  __BrowserXhr_81:import70.BrowserXhr;
  __ResponseOptions_82:import71.BaseResponseOptions;
  __XSRFStrategy_83:any;
  __XHRBackend_84:import72.XHRBackend;
  __RequestOptions_85:import73.BaseRequestOptions;
  __Dispatcher_86:import74.Dispatcher;
  ___INITIAL_REDUCER_87:any;
  __INITIAL_REDUCER_88:any;
  __UNDO_DEVTOOLS_CONFIG_89:any;
  __Reducer_90:any;
  ___INITIAL_STATE_91:any;
  __INITIAL_STATE_92:any;
  __State_93:any;
  __Store_94:any;
  __Http_95:any;
  __DomSanitizer_96:import75.DomSanitizerImpl;
  __MdIconRegistry_97:any;
  __HAMMER_GESTURE_CONFIG_98:import76.HammerGestureConfig;
  __MdSnackBar_99:import77.MdSnackBar;
  __FocusOriginMonitor_100:any;
  __DomProjection_101:import42.DomProjection;
  __MatchMedia_102:import78.MatchMedia;
  __BREAKPOINTS_103:any;
  __BreakPointRegistry_104:import79.BreakPointRegistry;
  __MediaMonitor_105:import80.MediaMonitor;
  __ObservableMedia_106:import81.MediaService;
  __Compiler_107:import82.Compiler;
  __APP_ID_108:any;
  __DOCUMENT_109:any;
  __EVENT_MANAGER_PLUGINS_110:any[];
  __EventManager_111:import83.EventManager;
  _DomSharedStylesHost_112:import84.DomSharedStylesHost;
  __AnimationDriver_113:any;
  __DomRootRenderer_114:import85.DomRootRenderer_;
  __NgProbeToken_115:any[];
  __RootRenderer_116:any;
  __Sanitizer_117:any;
  __AnimationQueue_118:import86.AnimationQueue;
  __ViewUtils_119:import87.ViewUtils;
  __IterableDiffers_120:any;
  __KeyValueDiffers_121:any;
  __SharedStylesHost_122:any;
  __Title_123:import88.Title;
  __FormBuilder_124:import89.FormBuilder;
  __DomHelper_125:import90.DomHelper;
  __UtilsService_126:import91.UtilsService;
  __CommonSandbox_127:import92.CommonSandbox;
  __UrlSerializer_128:import93.DefaultUrlSerializer;
  __RouterOutletMap_129:import94.RouterOutletMap;
  __ROUTER_CONFIGURATION_130:any;
  __LocationStrategy_131:any;
  __Location_132:import95.Location;
  __NgModuleFactoryLoader_133:import96.SystemJsNgModuleLoader;
  __ROUTES_134:any[];
  __Router_135:any;
  __AuthenticatedGuard_136:import97.AuthenticatedGuard;
  __RealTime_137:import98.RealTime;
  __AuthenticationService_138:import99.AuthenticationService;
  __AuthenticationSandbox_139:import100.AuthenticationSandbox;
  __WindowRef_140:import101.WindowRef;
  __DocumentRef_141:import101.DocumentRef;
  __LAZY_MAPS_API_CONFIG_142:any;
  __MapsAPILoader_143:import102.LazyMapsAPILoader;
  __PageScrollService_144:import103.PageScrollService;
  __ActivatedRoute_145:any;
  _NoPreloading_146:import104.NoPreloading;
  _PreloadingStrategy_147:any;
  _RouterPreloader_148:import104.RouterPreloader;
  __PreloadAllModules_149:import104.PreloadAllModules;
  __ROUTER_INITIALIZER_150:any;
  __APP_BOOTSTRAP_LISTENER_151:any[];
  _ContactsService_152:import105.ContactsService;
  _NotesService_153:import106.NotesService;
  _UserDataService_154:import107.UserDataService;
  _MessagesService_155:import108.MessagesService;
  _AddressesService_156:import109.AddressesService;
  _ClientAccountsService_157:import110.ClientAccountsService;
  _ClientDocumentsService_158:import111.ClientDocumentsService;
  __SalesService_159:import112.SalesService;
  _TasksService_160:import113.TasksService;
  _ActivitiesService_161:import114.ActivitiesService;
  _XAssetsService_162:import115.XAssetsService;
  _XLiabilitiesService_163:import116.XLiabilitiesService;
  _XPensionsService_164:import117.XPensionsService;
  _XProtectionsService_165:import118.XProtectionsService;
  _BankAccountsService_166:import119.BankAccountsService;
  __AppSandbox_167:import120.AppSandbox;
  _GoogleMapsService_168:import121.GoogleMapsService;
  _AddressesSandbox_169:import122.AddressesSandbox;
  _ClientAccountsSandbox_170:import123.ClientAccountsSandbox;
  _BoxAPIService_171:import124.BoxAPIService;
  _ClientDocumentsSandbox_172:import125.ClientDocumentsSandbox;
  _ContactsSandbox_173:import126.ContactsSandbox;
  _MessagesSandbox_174:import127.MessagesSandbox;
  _NotesSandbox_175:import128.NotesSandbox;
  _ActivitiesSandbox_176:import129.ActivitiesSandbox;
  __SalesSandbox_177:import130.SalesSandbox;
  _TasksSandbox_178:import131.TasksSandbox;
  _TeamSandbox_179:import132.TeamSandbox;
  _XAssetsSandbox_180:import133.XAssetsSandbox;
  _XLiabilitiesSandbox_181:import134.XLiabilitiesSandbox;
  _XPensionsSandbox_182:import135.XPensionsSandbox;
  _XProtectionsSandbox_183:import136.XProtectionsSandbox;
  _BankAccountsSandbox_184:import137.BankAccountsSandbox;
  constructor(parent:import138.Injector) {
    super(parent,[
      import139.MdDialogContainerNgFactory,
      import140.MdSnackBarContainerNgFactory,
      import141.SimpleSnackBarNgFactory,
      import142.TooltipComponentNgFactory,
      import143.PopoverContentNgFactory,
      import144.AuthenticationContainerNgFactory,
      import145.RegisterContainerNgFactory,
      import146.ContactsPageContainerNgFactory,
      import147.ContactsMasterContainerNgFactory,
      import148.AddContactContainerNgFactory,
      import149.ContactsDetailContainerNgFactory,
      import150.ClientAccountsPageContainerNgFactory,
      import151.ClientAccountsMasterContainerNgFactory,
      import152.ClientAccountsOverviewContainerNgFactory,
      import153.ClientAccountsDetailContainerNgFactory,
      import154.NotesPageContainerNgFactory,
      import155.NotesMasterContainerNgFactory,
      import156.AddNoteContainerNgFactory,
      import157.NotesDetailContainerNgFactory,
      import158.MessagesPageContainerNgFactory,
      import159.MessagesMasterContainerNgFactory,
      import160.MessagesDetailContainerNgFactory,
      import161.TeamPageContainerNgFactory,
      import162.TeamMasterContainerNgFactory,
      import163.DefaultPageComponentNgFactory,
      import164.ClientDocumentsPageContainerNgFactory,
      import165.ClientDocumentsMasterContainerNgFactory,
      import166.ClientDocumentsDetailContainerNgFactory,
      import167.TasksPageContainerNgFactory,
      import168.TasksMasterContainerNgFactory,
      import169.TasksTodayContainerNgFactory,
      import170.TasksWeekContainerNgFactory,
      import171.TasksNextWeekContainerNgFactory,
      import172.TasksMonthContainerNgFactory,
      import173.TasksAllContainerNgFactory,
      ApplicationWrapperContainerNgFactory
    ]
    ,[ApplicationWrapperContainerNgFactory]);
  }
  get _ScrollDispatcher_61():any {
    if ((this.__ScrollDispatcher_61 == null)) { (this.__ScrollDispatcher_61 = import174.SCROLL_DISPATCHER_PROVIDER_FACTORY(this.parent.get(import174.ScrollDispatcher,(null as any)))); }
    return this.__ScrollDispatcher_61;
  }
  get _ViewportRuler_62():any {
    if ((this.__ViewportRuler_62 == null)) { (this.__ViewportRuler_62 = import175.VIEWPORT_RULER_PROVIDER_FACTORY(this.parent.get(import175.ViewportRuler,(null as any)),this._ScrollDispatcher_61)); }
    return this.__ViewportRuler_62;
  }
  get _LOCALE_ID_63():any {
    if ((this.__LOCALE_ID_63 == null)) { (this.__LOCALE_ID_63 = import46._localeFactory(this.parent.get(import176.LOCALE_ID,(null as any)))); }
    return this.__LOCALE_ID_63;
  }
  get _NgLocalization_64():import60.NgLocaleLocalization {
    if ((this.__NgLocalization_64 == null)) { (this.__NgLocalization_64 = new import60.NgLocaleLocalization(this._LOCALE_ID_63)); }
    return this.__NgLocalization_64;
  }
  get _OverlayContainer_65():any {
    if ((this.__OverlayContainer_65 == null)) { (this.__OverlayContainer_65 = import177.OVERLAY_CONTAINER_PROVIDER_FACTORY(this.parent.get(import177.OverlayContainer,(null as any)))); }
    return this.__OverlayContainer_65;
  }
  get _OverlayPositionBuilder_66():import61.OverlayPositionBuilder {
    if ((this.__OverlayPositionBuilder_66 == null)) { (this.__OverlayPositionBuilder_66 = new import61.OverlayPositionBuilder(this._ViewportRuler_62)); }
    return this.__OverlayPositionBuilder_66;
  }
  get _ErrorHandler_67():any {
    if ((this.__ErrorHandler_67 == null)) { (this.__ErrorHandler_67 = import47.errorHandler()); }
    return this.__ErrorHandler_67;
  }
  get _RouterInitializer_68():import48.RouterInitializer {
    if ((this.__RouterInitializer_68 == null)) { (this.__RouterInitializer_68 = new import48.RouterInitializer(this)); }
    return this.__RouterInitializer_68;
  }
  get _APP_INITIALIZER_69():any[] {
    if ((this.__APP_INITIALIZER_69 == null)) { (this.__APP_INITIALIZER_69 = [import48.getAppInitializer(this._RouterInitializer_68)]); }
    return this.__APP_INITIALIZER_69;
  }
  get _ApplicationInitStatus_70():import62.ApplicationInitStatus {
    if ((this.__ApplicationInitStatus_70 == null)) { (this.__ApplicationInitStatus_70 = new import62.ApplicationInitStatus(this._APP_INITIALIZER_69)); }
    return this.__ApplicationInitStatus_70;
  }
  get _Testability_71():import63.Testability {
    if ((this.__Testability_71 == null)) { (this.__Testability_71 = new import63.Testability(this.parent.get(import178.NgZone))); }
    return this.__Testability_71;
  }
  get _ApplicationRef_73():any {
    if ((this.__ApplicationRef_73 == null)) { (this.__ApplicationRef_73 = this._ApplicationRef__72); }
    return this.__ApplicationRef_73;
  }
  get _Overlay_74():import65.Overlay {
    if ((this.__Overlay_74 == null)) { (this.__Overlay_74 = new import65.Overlay(this._OverlayContainer_65,this,this._OverlayPositionBuilder_66,this._ApplicationRef_73,this,this.parent.get(import178.NgZone))); }
    return this.__Overlay_74;
  }
  get _RadioControlRegistry_75():import66.RadioControlRegistry {
    if ((this.__RadioControlRegistry_75 == null)) { (this.__RadioControlRegistry_75 = new import66.RadioControlRegistry()); }
    return this.__RadioControlRegistry_75;
  }
  get _UniqueSelectionDispatcher_76():any {
    if ((this.__UniqueSelectionDispatcher_76 == null)) { (this.__UniqueSelectionDispatcher_76 = import179.UNIQUE_SELECTION_DISPATCHER_PROVIDER_FACTORY(this.parent.get(import179.UniqueSelectionDispatcher,(null as any)))); }
    return this.__UniqueSelectionDispatcher_76;
  }
  get _Platform_77():import67.Platform {
    if ((this.__Platform_77 == null)) { (this.__Platform_77 = new import67.Platform()); }
    return this.__Platform_77;
  }
  get _InteractivityChecker_78():import68.InteractivityChecker {
    if ((this.__InteractivityChecker_78 == null)) { (this.__InteractivityChecker_78 = new import68.InteractivityChecker(this._Platform_77)); }
    return this.__InteractivityChecker_78;
  }
  get _LiveAnnouncer_79():any {
    if ((this.__LiveAnnouncer_79 == null)) { (this.__LiveAnnouncer_79 = import180.LIVE_ANNOUNCER_PROVIDER_FACTORY(this.parent.get(import180.LiveAnnouncer,(null as any)),this.parent.get(import180.LIVE_ANNOUNCER_ELEMENT_TOKEN,(null as any)))); }
    return this.__LiveAnnouncer_79;
  }
  get _MdDialog_80():import69.MdDialog {
    if ((this.__MdDialog_80 == null)) { (this.__MdDialog_80 = new import69.MdDialog(this._Overlay_74,this,this.parent.get(import69.MdDialog,(null as any)))); }
    return this.__MdDialog_80;
  }
  get _BrowserXhr_81():import70.BrowserXhr {
    if ((this.__BrowserXhr_81 == null)) { (this.__BrowserXhr_81 = new import70.BrowserXhr()); }
    return this.__BrowserXhr_81;
  }
  get _ResponseOptions_82():import71.BaseResponseOptions {
    if ((this.__ResponseOptions_82 == null)) { (this.__ResponseOptions_82 = new import71.BaseResponseOptions()); }
    return this.__ResponseOptions_82;
  }
  get _XSRFStrategy_83():any {
    if ((this.__XSRFStrategy_83 == null)) { (this.__XSRFStrategy_83 = import23._createDefaultCookieXSRFStrategy()); }
    return this.__XSRFStrategy_83;
  }
  get _XHRBackend_84():import72.XHRBackend {
    if ((this.__XHRBackend_84 == null)) { (this.__XHRBackend_84 = new import72.XHRBackend(this._BrowserXhr_81,this._ResponseOptions_82,this._XSRFStrategy_83)); }
    return this.__XHRBackend_84;
  }
  get _RequestOptions_85():import73.BaseRequestOptions {
    if ((this.__RequestOptions_85 == null)) { (this.__RequestOptions_85 = new import73.BaseRequestOptions()); }
    return this.__RequestOptions_85;
  }
  get _Dispatcher_86():import74.Dispatcher {
    if ((this.__Dispatcher_86 == null)) { (this.__Dispatcher_86 = new import74.Dispatcher()); }
    return this.__Dispatcher_86;
  }
  get __INITIAL_REDUCER_87():any {
    if ((this.___INITIAL_REDUCER_87 == null)) { (this.___INITIAL_REDUCER_87 = import181.rootReducer); }
    return this.___INITIAL_REDUCER_87;
  }
  get _INITIAL_REDUCER_88():any {
    if ((this.__INITIAL_REDUCER_88 == null)) { (this.__INITIAL_REDUCER_88 = import2._initialReducerFactory(this.__INITIAL_REDUCER_87)); }
    return this.__INITIAL_REDUCER_88;
  }
  get _UNDO_DEVTOOLS_CONFIG_89():any {
    if ((this.__UNDO_DEVTOOLS_CONFIG_89 == null)) { (this.__UNDO_DEVTOOLS_CONFIG_89 = {bufferSize: 100}); }
    return this.__UNDO_DEVTOOLS_CONFIG_89;
  }
  get _Reducer_90():any {
    if ((this.__Reducer_90 == null)) { (this.__Reducer_90 = import182.createReducer(this._Dispatcher_86,this._INITIAL_REDUCER_88,this._UNDO_DEVTOOLS_CONFIG_89)); }
    return this.__Reducer_90;
  }
  get __INITIAL_STATE_91():any {
    if ((this.___INITIAL_STATE_91 == null)) { (this.___INITIAL_STATE_91 = (undefined as any)); }
    return this.___INITIAL_STATE_91;
  }
  get _INITIAL_STATE_92():any {
    if ((this.__INITIAL_STATE_92 == null)) { (this.__INITIAL_STATE_92 = import2._initialStateFactory(this.__INITIAL_STATE_91,this._INITIAL_REDUCER_88)); }
    return this.__INITIAL_STATE_92;
  }
  get _State_93():any {
    if ((this.__State_93 == null)) { (this.__State_93 = import2._stateFactory(this._INITIAL_STATE_92,this._Dispatcher_86,this._Reducer_90)); }
    return this.__State_93;
  }
  get _Store_94():any {
    if ((this.__Store_94 == null)) { (this.__Store_94 = import2._storeFactory(this._Dispatcher_86,this._Reducer_90,this._State_93)); }
    return this.__Store_94;
  }
  get _Http_95():any {
    if ((this.__Http_95 == null)) { (this.__Http_95 = import183.customHttpFactory(this._XHRBackend_84,this._RequestOptions_85,this._Store_94)); }
    return this.__Http_95;
  }
  get _DomSanitizer_96():import75.DomSanitizerImpl {
    if ((this.__DomSanitizer_96 == null)) { (this.__DomSanitizer_96 = new import75.DomSanitizerImpl()); }
    return this.__DomSanitizer_96;
  }
  get _MdIconRegistry_97():any {
    if ((this.__MdIconRegistry_97 == null)) { (this.__MdIconRegistry_97 = import24.ICON_REGISTRY_PROVIDER_FACTORY(this.parent.get(import184.MdIconRegistry,(null as any)),this._Http_95,this._DomSanitizer_96)); }
    return this.__MdIconRegistry_97;
  }
  get _HAMMER_GESTURE_CONFIG_98():import76.HammerGestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_98 == null)) { (this.__HAMMER_GESTURE_CONFIG_98 = new import76.HammerGestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_98;
  }
  get _MdSnackBar_99():import77.MdSnackBar {
    if ((this.__MdSnackBar_99 == null)) { (this.__MdSnackBar_99 = new import77.MdSnackBar(this._Overlay_74,this._LiveAnnouncer_79,this.parent.get(import77.MdSnackBar,(null as any)))); }
    return this.__MdSnackBar_99;
  }
  get _FocusOriginMonitor_100():any {
    if ((this.__FocusOriginMonitor_100 == null)) { (this.__FocusOriginMonitor_100 = import185.FOCUS_ORIGIN_MONITOR_PROVIDER_FACTORY(this.parent.get(import185.FocusOriginMonitor,(null as any)))); }
    return this.__FocusOriginMonitor_100;
  }
  get _DomProjection_101():import42.DomProjection {
    if ((this.__DomProjection_101 == null)) { (this.__DomProjection_101 = new import42.DomProjection()); }
    return this.__DomProjection_101;
  }
  get _MatchMedia_102():import78.MatchMedia {
    if ((this.__MatchMedia_102 == null)) { (this.__MatchMedia_102 = new import78.MatchMedia(this.parent.get(import178.NgZone))); }
    return this.__MatchMedia_102;
  }
  get _BREAKPOINTS_103():any {
    if ((this.__BREAKPOINTS_103 == null)) { (this.__BREAKPOINTS_103 = [
      {
        alias: 'xs',
        suffix: 'Xs',
        overlapping: false,
        mediaQuery: 'screen and (max-width: 599px)'
      }
      ,
      {
        alias: 'gt-xs',
        suffix: 'GtXs',
        overlapping: true,
        mediaQuery: 'screen and (min-width: 600px)'
      }
      ,
      {
        alias: 'sm',
        suffix: 'Sm',
        overlapping: false,
        mediaQuery: 'screen and (min-width: 600px) and (max-width: 959px)'
      }
      ,
      {
        alias: 'gt-sm',
        suffix: 'GtSm',
        overlapping: true,
        mediaQuery: 'screen and (min-width: 960px)'
      }
      ,
      {
        alias: 'md',
        suffix: 'Md',
        overlapping: false,
        mediaQuery: 'screen and (min-width: 960px) and (max-width: 1279px)'
      }
      ,
      {
        alias: 'gt-md',
        suffix: 'GtMd',
        overlapping: true,
        mediaQuery: 'screen and (min-width: 1280px)'
      }
      ,
      {
        alias: 'lg',
        suffix: 'Lg',
        overlapping: false,
        mediaQuery: 'screen and (min-width: 1280px) and (max-width: 1919px)'
      }
      ,
      {
        alias: 'gt-lg',
        suffix: 'GtLg',
        overlapping: true,
        mediaQuery: 'screen and (min-width: 1920px)'
      }
      ,
      {
        alias: 'xl',
        suffix: 'Xl',
        overlapping: false,
        mediaQuery: 'screen and (min-width: 1920px) and (max-width: 5000px)'
      }

    ]
    ); }
    return this.__BREAKPOINTS_103;
  }
  get _BreakPointRegistry_104():import79.BreakPointRegistry {
    if ((this.__BreakPointRegistry_104 == null)) { (this.__BreakPointRegistry_104 = new import79.BreakPointRegistry(this._BREAKPOINTS_103)); }
    return this.__BreakPointRegistry_104;
  }
  get _MediaMonitor_105():import80.MediaMonitor {
    if ((this.__MediaMonitor_105 == null)) { (this.__MediaMonitor_105 = new import80.MediaMonitor(this._BreakPointRegistry_104,this._MatchMedia_102)); }
    return this.__MediaMonitor_105;
  }
  get _ObservableMedia_106():import81.MediaService {
    if ((this.__ObservableMedia_106 == null)) { (this.__ObservableMedia_106 = new import81.MediaService(this._MatchMedia_102,this._BreakPointRegistry_104)); }
    return this.__ObservableMedia_106;
  }
  get _Compiler_107():import82.Compiler {
    if ((this.__Compiler_107 == null)) { (this.__Compiler_107 = new import82.Compiler()); }
    return this.__Compiler_107;
  }
  get _APP_ID_108():any {
    if ((this.__APP_ID_108 == null)) { (this.__APP_ID_108 = import186._appIdRandomProviderFactory()); }
    return this.__APP_ID_108;
  }
  get _DOCUMENT_109():any {
    if ((this.__DOCUMENT_109 == null)) { (this.__DOCUMENT_109 = import47._document()); }
    return this.__DOCUMENT_109;
  }
  get _EVENT_MANAGER_PLUGINS_110():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_110 == null)) { (this.__EVENT_MANAGER_PLUGINS_110 = [
      new import187.DomEventsPlugin(),
      new import188.KeyEventsPlugin(),
      new import76.HammerGesturesPlugin(this._HAMMER_GESTURE_CONFIG_98)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_110;
  }
  get _EventManager_111():import83.EventManager {
    if ((this.__EventManager_111 == null)) { (this.__EventManager_111 = new import83.EventManager(this._EVENT_MANAGER_PLUGINS_110,this.parent.get(import178.NgZone))); }
    return this.__EventManager_111;
  }
  get _AnimationDriver_113():any {
    if ((this.__AnimationDriver_113 == null)) { (this.__AnimationDriver_113 = import47._resolveDefaultAnimationDriver()); }
    return this.__AnimationDriver_113;
  }
  get _DomRootRenderer_114():import85.DomRootRenderer_ {
    if ((this.__DomRootRenderer_114 == null)) { (this.__DomRootRenderer_114 = new import85.DomRootRenderer_(this._DOCUMENT_109,this._EventManager_111,this._DomSharedStylesHost_112,this._AnimationDriver_113,this._APP_ID_108)); }
    return this.__DomRootRenderer_114;
  }
  get _NgProbeToken_115():any[] {
    if ((this.__NgProbeToken_115 == null)) { (this.__NgProbeToken_115 = [import48.routerNgProbeToken()]); }
    return this.__NgProbeToken_115;
  }
  get _RootRenderer_116():any {
    if ((this.__RootRenderer_116 == null)) { (this.__RootRenderer_116 = import189._createConditionalRootRenderer(this._DomRootRenderer_114,this.parent.get(import189.NgProbeToken,(null as any)),this._NgProbeToken_115)); }
    return this.__RootRenderer_116;
  }
  get _Sanitizer_117():any {
    if ((this.__Sanitizer_117 == null)) { (this.__Sanitizer_117 = this._DomSanitizer_96); }
    return this.__Sanitizer_117;
  }
  get _AnimationQueue_118():import86.AnimationQueue {
    if ((this.__AnimationQueue_118 == null)) { (this.__AnimationQueue_118 = new import86.AnimationQueue(this.parent.get(import178.NgZone))); }
    return this.__AnimationQueue_118;
  }
  get _ViewUtils_119():import87.ViewUtils {
    if ((this.__ViewUtils_119 == null)) { (this.__ViewUtils_119 = new import87.ViewUtils(this._RootRenderer_116,this._Sanitizer_117,this._AnimationQueue_118)); }
    return this.__ViewUtils_119;
  }
  get _IterableDiffers_120():any {
    if ((this.__IterableDiffers_120 == null)) { (this.__IterableDiffers_120 = import46._iterableDiffersFactory()); }
    return this.__IterableDiffers_120;
  }
  get _KeyValueDiffers_121():any {
    if ((this.__KeyValueDiffers_121 == null)) { (this.__KeyValueDiffers_121 = import46._keyValueDiffersFactory()); }
    return this.__KeyValueDiffers_121;
  }
  get _SharedStylesHost_122():any {
    if ((this.__SharedStylesHost_122 == null)) { (this.__SharedStylesHost_122 = this._DomSharedStylesHost_112); }
    return this.__SharedStylesHost_122;
  }
  get _Title_123():import88.Title {
    if ((this.__Title_123 == null)) { (this.__Title_123 = new import88.Title()); }
    return this.__Title_123;
  }
  get _FormBuilder_124():import89.FormBuilder {
    if ((this.__FormBuilder_124 == null)) { (this.__FormBuilder_124 = new import89.FormBuilder()); }
    return this.__FormBuilder_124;
  }
  get _DomHelper_125():import90.DomHelper {
    if ((this.__DomHelper_125 == null)) { (this.__DomHelper_125 = new import90.DomHelper()); }
    return this.__DomHelper_125;
  }
  get _UtilsService_126():import91.UtilsService {
    if ((this.__UtilsService_126 == null)) { (this.__UtilsService_126 = new import91.UtilsService()); }
    return this.__UtilsService_126;
  }
  get _CommonSandbox_127():import92.CommonSandbox {
    if ((this.__CommonSandbox_127 == null)) { (this.__CommonSandbox_127 = new import92.CommonSandbox(this._Store_94)); }
    return this.__CommonSandbox_127;
  }
  get _UrlSerializer_128():import93.DefaultUrlSerializer {
    if ((this.__UrlSerializer_128 == null)) { (this.__UrlSerializer_128 = new import93.DefaultUrlSerializer()); }
    return this.__UrlSerializer_128;
  }
  get _RouterOutletMap_129():import94.RouterOutletMap {
    if ((this.__RouterOutletMap_129 == null)) { (this.__RouterOutletMap_129 = new import94.RouterOutletMap()); }
    return this.__RouterOutletMap_129;
  }
  get _ROUTER_CONFIGURATION_130():any {
    if ((this.__ROUTER_CONFIGURATION_130 == null)) { (this.__ROUTER_CONFIGURATION_130 = {}); }
    return this.__ROUTER_CONFIGURATION_130;
  }
  get _LocationStrategy_131():any {
    if ((this.__LocationStrategy_131 == null)) { (this.__LocationStrategy_131 = import48.provideLocationStrategy(this.parent.get(import190.PlatformLocation),this.parent.get(import191.APP_BASE_HREF,(null as any)),this._ROUTER_CONFIGURATION_130)); }
    return this.__LocationStrategy_131;
  }
  get _Location_132():import95.Location {
    if ((this.__Location_132 == null)) { (this.__Location_132 = new import95.Location(this._LocationStrategy_131)); }
    return this.__Location_132;
  }
  get _NgModuleFactoryLoader_133():import96.SystemJsNgModuleLoader {
    if ((this.__NgModuleFactoryLoader_133 == null)) { (this.__NgModuleFactoryLoader_133 = new import96.SystemJsNgModuleLoader(this._Compiler_107,this.parent.get(import96.SystemJsNgModuleLoaderConfig,(null as any)))); }
    return this.__NgModuleFactoryLoader_133;
  }
  get _ROUTES_134():any[] {
      if ((this.__ROUTES_134 == null)) { (this.__ROUTES_134 = [[
        {
          path: '',
          redirectTo: '/accounts',
          pathMatch: 'full',
          canActivate: [import97.AuthenticatedGuard]
        }
        ,
        {
          path: 'authentication',
          component: import192.AuthenticationContainer
        }
        ,
        {
          path: 'authenticationregisterhiddencomponenttemp',
          component: import193.RegisterContainer
        }
        ,
        {
          path: 'contacts',
          component: import194.ContactsPageContainer,
          canActivate: [import97.AuthenticatedGuard],
          children: [
            {
              path: 'list',
              component: import195.ContactsMasterContainer,
              outlet: 'm'
            }
            ,
            {
              path: 'add',
              component: import196.AddContactContainer,
              outlet: 'd'
            }
            ,
            {
              path: ':id',
              component: import197.ContactsDetailContainer,
              outlet: 'd'
            }

          ]

        }
        ,
        {
          path: 'accounts',
          component: import198.ClientAccountsPageContainer,
          canActivate: [import97.AuthenticatedGuard],
          children: [
            {
              path: 'list',
              component: import199.ClientAccountsMasterContainer,
              outlet: 'm'
            }
            ,
            {
              path: 'overview',
              component: import200.ClientAccountsOverviewContainer,
              outlet: 'd'
            }
            ,
            {
              path: ':id',
              component: import201.ClientAccountsDetailContainer,
              outlet: 'd'
            }

          ]

        }
        ,
        {
          path: 'notes',
          component: import202.NotesPageContainer,
          canActivate: [import97.AuthenticatedGuard],
          children: [
            {
              path: 'list',
              component: import203.NotesMasterContainer,
              outlet: 'm'
            }
            ,
            {
              path: 'add',
              component: import204.AddNoteContainer,
              outlet: 'd'
            }
            ,
            {
              path: ':id',
              component: import205.NotesDetailContainer,
              outlet: 'd'
            }

          ]

        }
        ,
        {
          path: 'messages',
          component: import206.MessagesPageContainer,
          canActivate: [import97.AuthenticatedGuard],
          children: [
            {
              path: 'list',
              component: import207.MessagesMasterContainer,
              outlet: 'm'
            }
            ,
            {
              path: 'add',
              component: import208.MessagesDetailContainer,
              outlet: 'd'
            }
            ,
            {
              path: ':id',
              component: import208.MessagesDetailContainer,
              outlet: 'd'
            }

          ]

        }
        ,
        {
          path: 'team',
          component: import209.TeamPageContainer,
          canActivate: [import97.AuthenticatedGuard],
          children: [
            {
              path: 'list',
              component: import210.TeamMasterContainer,
              outlet: 'm'
            }
            ,
            {
              path: 'add',
              component: import211.DefaultPageComponent,
              outlet: 'd'
            }
            ,
            {
              path: ':id',
              component: import211.DefaultPageComponent,
              outlet: 'd'
            }

          ]

        }
        ,
        {
          path: 'documents',
          component: import212.ClientDocumentsPageContainer,
          canActivate: [import97.AuthenticatedGuard],
          children: [
            {
              path: 'list',
              component: import213.ClientDocumentsMasterContainer,
              outlet: 'm'
            }
            ,
            {
              path: 'add',
              component: import214.ClientDocumentsDetailContainer,
              outlet: 'd'
            }
            ,
            {
              path: ':id',
              component: import214.ClientDocumentsDetailContainer,
              outlet: 'd'
            }

          ]

        }
        ,
        {
          path: 'tasks',
          component: import215.TasksPageContainer,
          canActivate: [import97.AuthenticatedGuard],
          children: [
            {
              path: 'list',
              component: import216.TasksMasterContainer,
              outlet: 'm'
            }
            ,
            {
              path: 'today',
              component: import217.TasksTodayContainer,
              outlet: 'd'
            }
            ,
            {
              path: 'week',
              component: import218.TasksWeekContainer,
              outlet: 'd'
            }
            ,
            {
              path: 'nextweek',
              component: import219.TasksNextWeekContainer,
              outlet: 'd'
            }
            ,
            {
              path: 'month',
              component: import220.TasksMonthContainer,
              outlet: 'd'
            }
            ,
            {
              path: 'assigned',
              component: import217.TasksTodayContainer,
              outlet: 'd'
            }
            ,
            {
              path: 'all',
              component: import221.TasksAllContainer,
              outlet: 'd'
            }

          ]

        }

      ]
    ]); }
    return this.__ROUTES_134;
  }
  get _Router_135():any {
    if ((this.__Router_135 == null)) { (this.__Router_135 = import48.setupRouter(this._ApplicationRef_73,this._UrlSerializer_128,this._RouterOutletMap_129,this._Location_132,this,this._NgModuleFactoryLoader_133,this._Compiler_107,this._ROUTES_134,this._ROUTER_CONFIGURATION_130,this.parent.get(import222.UrlHandlingStrategy,(null as any)),this.parent.get(import223.RouteReuseStrategy,(null as any)))); }
    return this.__Router_135;
  }
  get _AuthenticatedGuard_136():import97.AuthenticatedGuard {
    if ((this.__AuthenticatedGuard_136 == null)) { (this.__AuthenticatedGuard_136 = new import97.AuthenticatedGuard(this._Router_135)); }
    return this.__AuthenticatedGuard_136;
  }
  get _RealTime_137():import98.RealTime {
    if ((this.__RealTime_137 == null)) { (this.__RealTime_137 = new import98.RealTime(this._Store_94,this._Router_135)); }
    return this.__RealTime_137;
  }
  get _AuthenticationService_138():import99.AuthenticationService {
    if ((this.__AuthenticationService_138 == null)) { (this.__AuthenticationService_138 = new import99.AuthenticationService(this._Http_95)); }
    return this.__AuthenticationService_138;
  }
  get _AuthenticationSandbox_139():import100.AuthenticationSandbox {
    if ((this.__AuthenticationSandbox_139 == null)) { (this.__AuthenticationSandbox_139 = new import100.AuthenticationSandbox(this._AuthenticationService_138,this._Store_94)); }
    return this.__AuthenticationSandbox_139;
  }
  get _WindowRef_140():import101.WindowRef {
    if ((this.__WindowRef_140 == null)) { (this.__WindowRef_140 = new import101.WindowRef()); }
    return this.__WindowRef_140;
  }
  get _DocumentRef_141():import101.DocumentRef {
    if ((this.__DocumentRef_141 == null)) { (this.__DocumentRef_141 = new import101.DocumentRef()); }
    return this.__DocumentRef_141;
  }
  get _LAZY_MAPS_API_CONFIG_142():any {
    if ((this.__LAZY_MAPS_API_CONFIG_142 == null)) { (this.__LAZY_MAPS_API_CONFIG_142 = {apiKey: 'AIzaSyAqkrkJ74JFbCXlZO0l7xm_1uHlJebs7B4'}); }
    return this.__LAZY_MAPS_API_CONFIG_142;
  }
  get _MapsAPILoader_143():import102.LazyMapsAPILoader {
    if ((this.__MapsAPILoader_143 == null)) { (this.__MapsAPILoader_143 = new import102.LazyMapsAPILoader(this._LAZY_MAPS_API_CONFIG_142,this._WindowRef_140,this._DocumentRef_141)); }
    return this.__MapsAPILoader_143;
  }
  get _PageScrollService_144():import103.PageScrollService {
    if ((this.__PageScrollService_144 == null)) { (this.__PageScrollService_144 = new import103.PageScrollService()); }
    return this.__PageScrollService_144;
  }
  get _ActivatedRoute_145():any {
    if ((this.__ActivatedRoute_145 == null)) { (this.__ActivatedRoute_145 = import48.rootRoute(this._Router_135)); }
    return this.__ActivatedRoute_145;
  }
  get _PreloadAllModules_149():import104.PreloadAllModules {
    if ((this.__PreloadAllModules_149 == null)) { (this.__PreloadAllModules_149 = new import104.PreloadAllModules()); }
    return this.__PreloadAllModules_149;
  }
  get _ROUTER_INITIALIZER_150():any {
    if ((this.__ROUTER_INITIALIZER_150 == null)) { (this.__ROUTER_INITIALIZER_150 = import48.getBootstrapListener(this._RouterInitializer_68)); }
    return this.__ROUTER_INITIALIZER_150;
  }
  get _APP_BOOTSTRAP_LISTENER_151():any[] {
    if ((this.__APP_BOOTSTRAP_LISTENER_151 == null)) { (this.__APP_BOOTSTRAP_LISTENER_151 = [this._ROUTER_INITIALIZER_150]); }
    return this.__APP_BOOTSTRAP_LISTENER_151;
  }
  get _SalesService_159():import112.SalesService {
    if ((this.__SalesService_159 == null)) { (this.__SalesService_159 = new import112.SalesService(this._Store_94,this._Http_95)); }
    return this.__SalesService_159;
  }
  get _AppSandbox_167():import120.AppSandbox {
    if ((this.__AppSandbox_167 == null)) { (this.__AppSandbox_167 = new import120.AppSandbox(this._Store_94,this._AuthenticationService_138,this._ContactsService_152,this._NotesService_153,this._UserDataService_154,this._MessagesService_155,this._AddressesService_156,this._ClientAccountsService_157,this._ClientDocumentsService_158,this._SalesService_159,this._TasksService_160,this._ActivitiesService_161,this._XAssetsService_162,this._XLiabilitiesService_163,this._XPensionsService_164,this._XProtectionsService_165,this._BankAccountsService_166,this._RealTime_137)); }
    return this.__AppSandbox_167;
  }
  get _SalesSandbox_177():import130.SalesSandbox {
    if ((this.__SalesSandbox_177 == null)) { (this.__SalesSandbox_177 = new import130.SalesSandbox(this._Store_94,this._SalesService_159)); }
    return this.__SalesSandbox_177;
  }
  createInternal():import1.ProdModule {
    this._StoreModule_0 = new import2.StoreModule();
    this._StoreUndoModule_1 = new import3.StoreUndoModule();
    this._CompatibilityModule_2 = new import4.CompatibilityModule();
    this._MdRippleModule_3 = new import5.MdRippleModule();
    this._CommonModule_4 = new import6.CommonModule();
    this._MdOptionModule_5 = new import7.MdOptionModule();
    this._PortalModule_6 = new import8.PortalModule();
    this._OverlayModule_7 = new import9.OverlayModule();
    this._MdAutocompleteModule_8 = new import10.MdAutocompleteModule();
    this._MdButtonModule_9 = new import11.MdButtonModule();
    this._InternalFormsSharedModule_10 = new import12.InternalFormsSharedModule();
    this._FormsModule_11 = new import13.FormsModule();
    this._MdButtonToggleModule_12 = new import14.MdButtonToggleModule();
    this._MdCardModule_13 = new import15.MdCardModule();
    this._MdChipsModule_14 = new import16.MdChipsModule();
    this._MdCheckboxModule_15 = new import17.MdCheckboxModule();
    this._PlatformModule_16 = new import18.PlatformModule();
    this._A11yModule_17 = new import19.A11yModule();
    this._MdDialogModule_18 = new import20.MdDialogModule();
    this._MdLineModule_19 = new import21.MdLineModule();
    this._MdGridListModule_20 = new import22.MdGridListModule();
    this._HttpModule_21 = new import23.HttpModule();
    this._MdIconModule_22 = new import24.MdIconModule();
    this._MdInputModule_23 = new import25.MdInputModule();
    this._MdListModule_24 = new import26.MdListModule();
    this._MdMenuModule_25 = new import27.MdMenuModule();
    this._MdProgressBarModule_26 = new import28.MdProgressBarModule();
    this._MdProgressSpinnerModule_27 = new import29.MdProgressSpinnerModule();
    this._MdRadioModule_28 = new import30.MdRadioModule();
    this._MdSelectModule_29 = new import31.MdSelectModule();
    this._MdSidenavModule_30 = new import32.MdSidenavModule();
    this._MdSliderModule_31 = new import33.MdSliderModule();
    this._MdSlideToggleModule_32 = new import34.MdSlideToggleModule();
    this._MdSnackBarModule_33 = new import35.MdSnackBarModule();
    this._ObserveContentModule_34 = new import36.ObserveContentModule();
    this._MdTabsModule_35 = new import37.MdTabsModule();
    this._MdToolbarModule_36 = new import38.MdToolbarModule();
    this._MdTooltipModule_37 = new import39.MdTooltipModule();
    this._RtlModule_38 = new import40.RtlModule();
    this._StyleModule_39 = new import41.StyleModule();
    this._ProjectionModule_40 = new import42.ProjectionModule();
    this._MaterialModule_41 = new import43.MaterialModule();
    this._MediaQueriesModule_42 = new import44.MediaQueriesModule();
    this._FlexLayoutModule_43 = new import45.FlexLayoutModule();
    this._ApplicationModule_44 = new import46.ApplicationModule();
    this._BrowserModule_45 = new import47.BrowserModule(this.parent.get(import47.BrowserModule,(null as any)));
    this._ReactiveFormsModule_46 = new import13.ReactiveFormsModule();
    this._ROUTER_FORROOT_GUARD_47 = import48.provideForRootGuard(this.parent.get(import224.Router,(null as any)));
    this._RouterModule_48 = new import48.RouterModule(this._ROUTER_FORROOT_GUARD_47);
    this._DpDatePickerModule_49 = new import49.DpDatePickerModule();
    this._AgmCoreModule_50 = new import50.AgmCoreModule();
    this._FroalaEditorModule_51 = new import51.FroalaEditorModule();
    this._FroalaViewModule_52 = new import52.FroalaViewModule();
    this._PopoverModule_53 = new import53.PopoverModule();
    this._AccordionModule_54 = new import54.AccordionModule();
    this._ChartsModule_55 = new import55.ChartsModule();
    this._Ng2PageScrollModule_56 = new import56.Ng2PageScrollModule();
    this._CommonLogicModule_57 = new import57.CommonLogicModule();
    this._AuthenticationModule_58 = new import58.AuthenticationModule();
    this._AppModule_59 = new import59.AppModule();
    this._ProdModule_60 = new import1.ProdModule();
    this._ApplicationRef__72 = new import64.ApplicationRef_(this.parent.get(import178.NgZone),this.parent.get(import225.Console),this,this._ErrorHandler_67,this,this._ApplicationInitStatus_70,this.parent.get(import63.TestabilityRegistry,(null as any)),this._Testability_71);
    this._DomSharedStylesHost_112 = new import84.DomSharedStylesHost(this._DOCUMENT_109);
    this._NoPreloading_146 = new import104.NoPreloading();
    this._PreloadingStrategy_147 = this._NoPreloading_146;
    this._RouterPreloader_148 = new import104.RouterPreloader(this._Router_135,this._NgModuleFactoryLoader_133,this._Compiler_107,this,this._PreloadingStrategy_147);
    this._ContactsService_152 = new import105.ContactsService(this._Store_94,this._Http_95);
    this._NotesService_153 = new import106.NotesService(this._Store_94,this._Http_95);
    this._UserDataService_154 = new import107.UserDataService(this._Store_94,this._Http_95);
    this._MessagesService_155 = new import108.MessagesService(this._Store_94,this._Http_95);
    this._AddressesService_156 = new import109.AddressesService(this._Store_94,this._Http_95);
    this._ClientAccountsService_157 = new import110.ClientAccountsService(this._Store_94,this._Http_95);
    this._ClientDocumentsService_158 = new import111.ClientDocumentsService(this._Store_94,this._Http_95);
    this._TasksService_160 = new import113.TasksService(this._Store_94,this._Http_95);
    this._ActivitiesService_161 = new import114.ActivitiesService(this._Store_94,this._Http_95);
    this._XAssetsService_162 = new import115.XAssetsService(this._Store_94,this._Http_95);
    this._XLiabilitiesService_163 = new import116.XLiabilitiesService(this._Store_94,this._Http_95);
    this._XPensionsService_164 = new import117.XPensionsService(this._Store_94,this._Http_95);
    this._XProtectionsService_165 = new import118.XProtectionsService(this._Store_94,this._Http_95);
    this._BankAccountsService_166 = new import119.BankAccountsService(this._Store_94,this._Http_95);
    this._GoogleMapsService_168 = new import121.GoogleMapsService(this._Http_95);
    this._AddressesSandbox_169 = new import122.AddressesSandbox(this._Store_94,this._AddressesService_156,this._GoogleMapsService_168);
    this._ClientAccountsSandbox_170 = new import123.ClientAccountsSandbox(this._Store_94,this._ClientAccountsService_157);
    this._BoxAPIService_171 = new import124.BoxAPIService(this._Http_95);
    this._ClientDocumentsSandbox_172 = new import125.ClientDocumentsSandbox(this._Store_94,this._ClientDocumentsService_158,this._BoxAPIService_171);
    this._ContactsSandbox_173 = new import126.ContactsSandbox(this._Store_94,this._ContactsService_152);
    this._MessagesSandbox_174 = new import127.MessagesSandbox(this._Store_94,this._MessagesService_155);
    this._NotesSandbox_175 = new import128.NotesSandbox(this._Store_94,this._NotesService_153);
    this._ActivitiesSandbox_176 = new import129.ActivitiesSandbox(this._Store_94,this._ActivitiesService_161);
    this._TasksSandbox_178 = new import131.TasksSandbox(this._Store_94,this._TasksService_160);
    this._TeamSandbox_179 = new import132.TeamSandbox(this._Store_94,this._UserDataService_154);
    this._XAssetsSandbox_180 = new import133.XAssetsSandbox(this._Store_94,this._XAssetsService_162);
    this._XLiabilitiesSandbox_181 = new import134.XLiabilitiesSandbox(this._Store_94,this._XLiabilitiesService_163);
    this._XPensionsSandbox_182 = new import135.XPensionsSandbox(this._Store_94,this._XPensionsService_164);
    this._XProtectionsSandbox_183 = new import136.XProtectionsSandbox(this._Store_94,this._XProtectionsService_165);
    this._BankAccountsSandbox_184 = new import137.BankAccountsSandbox(this._Store_94,this._BankAccountsService_166);
    return this._ProdModule_60;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.StoreModule)) { return this._StoreModule_0; }
    if ((token === import3.StoreUndoModule)) { return this._StoreUndoModule_1; }
    if ((token === import4.CompatibilityModule)) { return this._CompatibilityModule_2; }
    if ((token === import5.MdRippleModule)) { return this._MdRippleModule_3; }
    if ((token === import6.CommonModule)) { return this._CommonModule_4; }
    if ((token === import7.MdOptionModule)) { return this._MdOptionModule_5; }
    if ((token === import8.PortalModule)) { return this._PortalModule_6; }
    if ((token === import9.OverlayModule)) { return this._OverlayModule_7; }
    if ((token === import10.MdAutocompleteModule)) { return this._MdAutocompleteModule_8; }
    if ((token === import11.MdButtonModule)) { return this._MdButtonModule_9; }
    if ((token === import12.InternalFormsSharedModule)) { return this._InternalFormsSharedModule_10; }
    if ((token === import13.FormsModule)) { return this._FormsModule_11; }
    if ((token === import14.MdButtonToggleModule)) { return this._MdButtonToggleModule_12; }
    if ((token === import15.MdCardModule)) { return this._MdCardModule_13; }
    if ((token === import16.MdChipsModule)) { return this._MdChipsModule_14; }
    if ((token === import17.MdCheckboxModule)) { return this._MdCheckboxModule_15; }
    if ((token === import18.PlatformModule)) { return this._PlatformModule_16; }
    if ((token === import19.A11yModule)) { return this._A11yModule_17; }
    if ((token === import20.MdDialogModule)) { return this._MdDialogModule_18; }
    if ((token === import21.MdLineModule)) { return this._MdLineModule_19; }
    if ((token === import22.MdGridListModule)) { return this._MdGridListModule_20; }
    if ((token === import23.HttpModule)) { return this._HttpModule_21; }
    if ((token === import24.MdIconModule)) { return this._MdIconModule_22; }
    if ((token === import25.MdInputModule)) { return this._MdInputModule_23; }
    if ((token === import26.MdListModule)) { return this._MdListModule_24; }
    if ((token === import27.MdMenuModule)) { return this._MdMenuModule_25; }
    if ((token === import28.MdProgressBarModule)) { return this._MdProgressBarModule_26; }
    if ((token === import29.MdProgressSpinnerModule)) { return this._MdProgressSpinnerModule_27; }
    if ((token === import30.MdRadioModule)) { return this._MdRadioModule_28; }
    if ((token === import31.MdSelectModule)) { return this._MdSelectModule_29; }
    if ((token === import32.MdSidenavModule)) { return this._MdSidenavModule_30; }
    if ((token === import33.MdSliderModule)) { return this._MdSliderModule_31; }
    if ((token === import34.MdSlideToggleModule)) { return this._MdSlideToggleModule_32; }
    if ((token === import35.MdSnackBarModule)) { return this._MdSnackBarModule_33; }
    if ((token === import36.ObserveContentModule)) { return this._ObserveContentModule_34; }
    if ((token === import37.MdTabsModule)) { return this._MdTabsModule_35; }
    if ((token === import38.MdToolbarModule)) { return this._MdToolbarModule_36; }
    if ((token === import39.MdTooltipModule)) { return this._MdTooltipModule_37; }
    if ((token === import40.RtlModule)) { return this._RtlModule_38; }
    if ((token === import41.StyleModule)) { return this._StyleModule_39; }
    if ((token === import42.ProjectionModule)) { return this._ProjectionModule_40; }
    if ((token === import43.MaterialModule)) { return this._MaterialModule_41; }
    if ((token === import44.MediaQueriesModule)) { return this._MediaQueriesModule_42; }
    if ((token === import45.FlexLayoutModule)) { return this._FlexLayoutModule_43; }
    if ((token === import46.ApplicationModule)) { return this._ApplicationModule_44; }
    if ((token === import47.BrowserModule)) { return this._BrowserModule_45; }
    if ((token === import13.ReactiveFormsModule)) { return this._ReactiveFormsModule_46; }
    if ((token === import48.ROUTER_FORROOT_GUARD)) { return this._ROUTER_FORROOT_GUARD_47; }
    if ((token === import48.RouterModule)) { return this._RouterModule_48; }
    if ((token === import49.DpDatePickerModule)) { return this._DpDatePickerModule_49; }
    if ((token === import50.AgmCoreModule)) { return this._AgmCoreModule_50; }
    if ((token === import51.FroalaEditorModule)) { return this._FroalaEditorModule_51; }
    if ((token === import52.FroalaViewModule)) { return this._FroalaViewModule_52; }
    if ((token === import53.PopoverModule)) { return this._PopoverModule_53; }
    if ((token === import54.AccordionModule)) { return this._AccordionModule_54; }
    if ((token === import55.ChartsModule)) { return this._ChartsModule_55; }
    if ((token === import56.Ng2PageScrollModule)) { return this._Ng2PageScrollModule_56; }
    if ((token === import57.CommonLogicModule)) { return this._CommonLogicModule_57; }
    if ((token === import58.AuthenticationModule)) { return this._AuthenticationModule_58; }
    if ((token === import59.AppModule)) { return this._AppModule_59; }
    if ((token === import1.ProdModule)) { return this._ProdModule_60; }
    if ((token === import174.ScrollDispatcher)) { return this._ScrollDispatcher_61; }
    if ((token === import175.ViewportRuler)) { return this._ViewportRuler_62; }
    if ((token === import176.LOCALE_ID)) { return this._LOCALE_ID_63; }
    if ((token === import60.NgLocalization)) { return this._NgLocalization_64; }
    if ((token === import177.OverlayContainer)) { return this._OverlayContainer_65; }
    if ((token === import61.OverlayPositionBuilder)) { return this._OverlayPositionBuilder_66; }
    if ((token === import226.ErrorHandler)) { return this._ErrorHandler_67; }
    if ((token === import48.RouterInitializer)) { return this._RouterInitializer_68; }
    if ((token === import62.APP_INITIALIZER)) { return this._APP_INITIALIZER_69; }
    if ((token === import62.ApplicationInitStatus)) { return this._ApplicationInitStatus_70; }
    if ((token === import63.Testability)) { return this._Testability_71; }
    if ((token === import64.ApplicationRef_)) { return this._ApplicationRef__72; }
    if ((token === import64.ApplicationRef)) { return this._ApplicationRef_73; }
    if ((token === import65.Overlay)) { return this._Overlay_74; }
    if ((token === import66.RadioControlRegistry)) { return this._RadioControlRegistry_75; }
    if ((token === import179.UniqueSelectionDispatcher)) { return this._UniqueSelectionDispatcher_76; }
    if ((token === import67.Platform)) { return this._Platform_77; }
    if ((token === import68.InteractivityChecker)) { return this._InteractivityChecker_78; }
    if ((token === import180.LiveAnnouncer)) { return this._LiveAnnouncer_79; }
    if ((token === import69.MdDialog)) { return this._MdDialog_80; }
    if ((token === import70.BrowserXhr)) { return this._BrowserXhr_81; }
    if ((token === import71.ResponseOptions)) { return this._ResponseOptions_82; }
    if ((token === import227.XSRFStrategy)) { return this._XSRFStrategy_83; }
    if ((token === import72.XHRBackend)) { return this._XHRBackend_84; }
    if ((token === import73.RequestOptions)) { return this._RequestOptions_85; }
    if ((token === import74.Dispatcher)) { return this._Dispatcher_86; }
    if ((token === import2._INITIAL_REDUCER)) { return this.__INITIAL_REDUCER_87; }
    if ((token === import2.INITIAL_REDUCER)) { return this._INITIAL_REDUCER_88; }
    if ((token === import3.UNDO_DEVTOOLS_CONFIG)) { return this._UNDO_DEVTOOLS_CONFIG_89; }
    if ((token === import228.Reducer)) { return this._Reducer_90; }
    if ((token === import2._INITIAL_STATE)) { return this.__INITIAL_STATE_91; }
    if ((token === import2.INITIAL_STATE)) { return this._INITIAL_STATE_92; }
    if ((token === import229.State)) { return this._State_93; }
    if ((token === import230.Store)) { return this._Store_94; }
    if ((token === import231.Http)) { return this._Http_95; }
    if ((token === import75.DomSanitizer)) { return this._DomSanitizer_96; }
    if ((token === import184.MdIconRegistry)) { return this._MdIconRegistry_97; }
    if ((token === import76.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_98; }
    if ((token === import77.MdSnackBar)) { return this._MdSnackBar_99; }
    if ((token === import185.FocusOriginMonitor)) { return this._FocusOriginMonitor_100; }
    if ((token === import42.DomProjection)) { return this._DomProjection_101; }
    if ((token === import78.MatchMedia)) { return this._MatchMedia_102; }
    if ((token === import232.BREAKPOINTS)) { return this._BREAKPOINTS_103; }
    if ((token === import79.BreakPointRegistry)) { return this._BreakPointRegistry_104; }
    if ((token === import80.MediaMonitor)) { return this._MediaMonitor_105; }
    if ((token === import81.ObservableMedia)) { return this._ObservableMedia_106; }
    if ((token === import82.Compiler)) { return this._Compiler_107; }
    if ((token === import186.APP_ID)) { return this._APP_ID_108; }
    if ((token === import233.DOCUMENT)) { return this._DOCUMENT_109; }
    if ((token === import83.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_110; }
    if ((token === import83.EventManager)) { return this._EventManager_111; }
    if ((token === import84.DomSharedStylesHost)) { return this._DomSharedStylesHost_112; }
    if ((token === import234.AnimationDriver)) { return this._AnimationDriver_113; }
    if ((token === import85.DomRootRenderer)) { return this._DomRootRenderer_114; }
    if ((token === import64.NgProbeToken)) { return this._NgProbeToken_115; }
    if ((token === import235.RootRenderer)) { return this._RootRenderer_116; }
    if ((token === import236.Sanitizer)) { return this._Sanitizer_117; }
    if ((token === import86.AnimationQueue)) { return this._AnimationQueue_118; }
    if ((token === import87.ViewUtils)) { return this._ViewUtils_119; }
    if ((token === import237.IterableDiffers)) { return this._IterableDiffers_120; }
    if ((token === import238.KeyValueDiffers)) { return this._KeyValueDiffers_121; }
    if ((token === import84.SharedStylesHost)) { return this._SharedStylesHost_122; }
    if ((token === import88.Title)) { return this._Title_123; }
    if ((token === import89.FormBuilder)) { return this._FormBuilder_124; }
    if ((token === import90.DomHelper)) { return this._DomHelper_125; }
    if ((token === import91.UtilsService)) { return this._UtilsService_126; }
    if ((token === import92.CommonSandbox)) { return this._CommonSandbox_127; }
    if ((token === import93.UrlSerializer)) { return this._UrlSerializer_128; }
    if ((token === import94.RouterOutletMap)) { return this._RouterOutletMap_129; }
    if ((token === import48.ROUTER_CONFIGURATION)) { return this._ROUTER_CONFIGURATION_130; }
    if ((token === import191.LocationStrategy)) { return this._LocationStrategy_131; }
    if ((token === import95.Location)) { return this._Location_132; }
    if ((token === import239.NgModuleFactoryLoader)) { return this._NgModuleFactoryLoader_133; }
    if ((token === import240.ROUTES)) { return this._ROUTES_134; }
    if ((token === import224.Router)) { return this._Router_135; }
    if ((token === import97.AuthenticatedGuard)) { return this._AuthenticatedGuard_136; }
    if ((token === import98.RealTime)) { return this._RealTime_137; }
    if ((token === import99.AuthenticationService)) { return this._AuthenticationService_138; }
    if ((token === import100.AuthenticationSandbox)) { return this._AuthenticationSandbox_139; }
    if ((token === import101.WindowRef)) { return this._WindowRef_140; }
    if ((token === import101.DocumentRef)) { return this._DocumentRef_141; }
    if ((token === import102.LAZY_MAPS_API_CONFIG)) { return this._LAZY_MAPS_API_CONFIG_142; }
    if ((token === import241.MapsAPILoader)) { return this._MapsAPILoader_143; }
    if ((token === import103.PageScrollService)) { return this._PageScrollService_144; }
    if ((token === import242.ActivatedRoute)) { return this._ActivatedRoute_145; }
    if ((token === import104.NoPreloading)) { return this._NoPreloading_146; }
    if ((token === import104.PreloadingStrategy)) { return this._PreloadingStrategy_147; }
    if ((token === import104.RouterPreloader)) { return this._RouterPreloader_148; }
    if ((token === import104.PreloadAllModules)) { return this._PreloadAllModules_149; }
    if ((token === import48.ROUTER_INITIALIZER)) { return this._ROUTER_INITIALIZER_150; }
    if ((token === import186.APP_BOOTSTRAP_LISTENER)) { return this._APP_BOOTSTRAP_LISTENER_151; }
    if ((token === import105.ContactsService)) { return this._ContactsService_152; }
    if ((token === import106.NotesService)) { return this._NotesService_153; }
    if ((token === import107.UserDataService)) { return this._UserDataService_154; }
    if ((token === import108.MessagesService)) { return this._MessagesService_155; }
    if ((token === import109.AddressesService)) { return this._AddressesService_156; }
    if ((token === import110.ClientAccountsService)) { return this._ClientAccountsService_157; }
    if ((token === import111.ClientDocumentsService)) { return this._ClientDocumentsService_158; }
    if ((token === import112.SalesService)) { return this._SalesService_159; }
    if ((token === import113.TasksService)) { return this._TasksService_160; }
    if ((token === import114.ActivitiesService)) { return this._ActivitiesService_161; }
    if ((token === import115.XAssetsService)) { return this._XAssetsService_162; }
    if ((token === import116.XLiabilitiesService)) { return this._XLiabilitiesService_163; }
    if ((token === import117.XPensionsService)) { return this._XPensionsService_164; }
    if ((token === import118.XProtectionsService)) { return this._XProtectionsService_165; }
    if ((token === import119.BankAccountsService)) { return this._BankAccountsService_166; }
    if ((token === import120.AppSandbox)) { return this._AppSandbox_167; }
    if ((token === import121.GoogleMapsService)) { return this._GoogleMapsService_168; }
    if ((token === import122.AddressesSandbox)) { return this._AddressesSandbox_169; }
    if ((token === import123.ClientAccountsSandbox)) { return this._ClientAccountsSandbox_170; }
    if ((token === import124.BoxAPIService)) { return this._BoxAPIService_171; }
    if ((token === import125.ClientDocumentsSandbox)) { return this._ClientDocumentsSandbox_172; }
    if ((token === import126.ContactsSandbox)) { return this._ContactsSandbox_173; }
    if ((token === import127.MessagesSandbox)) { return this._MessagesSandbox_174; }
    if ((token === import128.NotesSandbox)) { return this._NotesSandbox_175; }
    if ((token === import129.ActivitiesSandbox)) { return this._ActivitiesSandbox_176; }
    if ((token === import130.SalesSandbox)) { return this._SalesSandbox_177; }
    if ((token === import131.TasksSandbox)) { return this._TasksSandbox_178; }
    if ((token === import132.TeamSandbox)) { return this._TeamSandbox_179; }
    if ((token === import133.XAssetsSandbox)) { return this._XAssetsSandbox_180; }
    if ((token === import134.XLiabilitiesSandbox)) { return this._XLiabilitiesSandbox_181; }
    if ((token === import135.XPensionsSandbox)) { return this._XPensionsSandbox_182; }
    if ((token === import136.XProtectionsSandbox)) { return this._XProtectionsSandbox_183; }
    if ((token === import137.BankAccountsSandbox)) { return this._BankAccountsSandbox_184; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ApplicationRef__72.ngOnDestroy();
    this._DomSharedStylesHost_112.ngOnDestroy();
    this._RouterPreloader_148.ngOnDestroy();
    this._ContactsService_152.ngOnDestroy();
    this._NotesService_153.ngOnDestroy();
    this._UserDataService_154.ngOnDestroy();
    this._MessagesService_155.ngOnDestroy();
    this._AddressesService_156.ngOnDestroy();
    this._ClientAccountsService_157.ngOnDestroy();
    this._ClientDocumentsService_158.ngOnDestroy();
    this._TasksService_160.ngOnDestroy();
    this._ActivitiesService_161.ngOnDestroy();
    this._XAssetsService_162.ngOnDestroy();
    this._XLiabilitiesService_163.ngOnDestroy();
    this._XPensionsService_164.ngOnDestroy();
    this._XProtectionsService_165.ngOnDestroy();
    this._BankAccountsService_166.ngOnDestroy();
    this._AddressesSandbox_169.ngOnDestroy();
    this._ClientAccountsSandbox_170.ngOnDestroy();
    this._ClientDocumentsSandbox_172.ngOnDestroy();
    this._ContactsSandbox_173.ngOnDestroy();
    this._MessagesSandbox_174.ngOnDestroy();
    this._NotesSandbox_175.ngOnDestroy();
    this._ActivitiesSandbox_176.ngOnDestroy();
    this._TasksSandbox_178.ngOnDestroy();
    this._TeamSandbox_179.ngOnDestroy();
    this._XAssetsSandbox_180.ngOnDestroy();
    this._XLiabilitiesSandbox_181.ngOnDestroy();
    this._XPensionsSandbox_182.ngOnDestroy();
    this._XProtectionsSandbox_183.ngOnDestroy();
    this._BankAccountsSandbox_184.ngOnDestroy();
  }
}
export const ProdModuleNgFactory:import0.NgModuleFactory<import1.ProdModule> = new import0.NgModuleFactory(ProdModuleInjector,import1.ProdModule);
export class Wrapper_ApplicationWrapperContainer {
  /*private*/ _eventHandler:Function;
  context:import1.ApplicationWrapperContainer;
  /*private*/ _changed:boolean;
  constructor() {
    this._changed = false;
    this.context = new import1.ApplicationWrapperContainer();
  }
  ngOnDetach(view:import243.AppView<any>,componentView:import243.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import243.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    return changed;
  }
  checkHost(view:import243.AppView<any>,componentView:import243.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import243.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
const nodeDebugInfos_ApplicationWrapperContainer_Host0:import244.StaticNodeDebugInfo[] = [new import244.StaticNodeDebugInfo([import1.ApplicationWrapperContainer],import1.ApplicationWrapperContainer,{})];
var renderType_ApplicationWrapperContainer_Host:import235.RenderComponentType = import87.createRenderComponentType('',0,import245.ViewEncapsulation.None,([] as any[]),{});
class View_ApplicationWrapperContainer_Host0 extends import243.DebugAppView<any> {
  _el_0:any;
  compView_0:import243.AppView<import1.ApplicationWrapperContainer>;
  _ApplicationWrapperContainer_0_3:Wrapper_ApplicationWrapperContainer;
  constructor(viewUtils:import87.ViewUtils,parentView:import243.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_ApplicationWrapperContainer_Host0,renderType_ApplicationWrapperContainer_Host,import246.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import247.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_ApplicationWrapperContainer_Host0);
  }
  createInternal(rootSelector:string):import248.ComponentRef<any> {
    this._el_0 = import87.selectOrCreateRenderHostElement(this.renderer,'application-wrapper',import87.EMPTY_INLINE_ARRAY,rootSelector,this.debug(0,0,0));
    this.compView_0 = new View_ApplicationWrapperContainer0(this.viewUtils,this,0,this._el_0);
    this._ApplicationWrapperContainer_0_3 = new Wrapper_ApplicationWrapperContainer();
    this.compView_0.create(this._ApplicationWrapperContainer_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import248.ComponentRef_<any>(0,this,this._el_0,this._ApplicationWrapperContainer_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import1.ApplicationWrapperContainer) && (0 === requestNodeIndex))) { return this._ApplicationWrapperContainer_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.debug(0,0,0);
    this._ApplicationWrapperContainer_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const ApplicationWrapperContainerNgFactory:import248.ComponentFactory<import1.ApplicationWrapperContainer> = new import248.ComponentFactory<import1.ApplicationWrapperContainer>('application-wrapper',View_ApplicationWrapperContainer_Host0,import1.ApplicationWrapperContainer);
const styles_ApplicationWrapperContainer:any[] = ([] as any[]);
const nodeDebugInfos_ApplicationWrapperContainer0:import244.StaticNodeDebugInfo[] = [
  new import244.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import244.StaticNodeDebugInfo([
    import88.Title,
    import249.ApplicationContainer
  ]
  ,import249.ApplicationContainer,{}),
  new import244.StaticNodeDebugInfo(([] as any[]),(null as any),{})
]
;
var renderType_ApplicationWrapperContainer:import235.RenderComponentType = import87.createRenderComponentType('/Users/jonoforbes/Developer/Ether/winecellar/src/setup/prod.module.ts class ApplicationWrapperContainer - inline template',0,import245.ViewEncapsulation.None,styles_ApplicationWrapperContainer,{});
export class View_ApplicationWrapperContainer0 extends import243.DebugAppView<import1.ApplicationWrapperContainer> {
  _text_0:any;
  _el_1:any;
  compView_1:import243.AppView<import249.ApplicationContainer>;
  _Title_1_3:import88.Title;
  _ApplicationContainer_1_4:import250.Wrapper_ApplicationContainer;
  _text_2:any;
  constructor(viewUtils:import87.ViewUtils,parentView:import243.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_ApplicationWrapperContainer0,renderType_ApplicationWrapperContainer,import246.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import247.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_ApplicationWrapperContainer0);
  }
  createInternal(rootSelector:string):import248.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'   \n        ',this.debug(0,0,0));
    this._el_1 = import87.createRenderElement(this.renderer,parentRenderNode,'application',import87.EMPTY_INLINE_ARRAY,this.debug(1,1,8));
    this.compView_1 = new import250.View_ApplicationContainer0(this.viewUtils,this,1,this._el_1);
    this._Title_1_3 = new import88.Title();
    this._ApplicationContainer_1_4 = new import250.Wrapper_ApplicationContainer(this._Title_1_3,this.parentView.injectorGet(import120.AppSandbox,this.parentIndex),this.parentView.injectorGet(import224.Router,this.parentIndex));
    this.compView_1.create(this._ApplicationContainer_1_4.context);
    this._text_2 = this.renderer.createText(parentRenderNode,'\n',this.debug(2,1,35));
    var disposable_0:Function = import87.subscribeToRenderElement(this,this._el_1,new import87.InlineArray4(4,'beforeunload','window','resize','window'),this.eventHandler(this.handleEvent_1));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._text_0,
      this._el_1,
      this._text_2
    ]
    ),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import88.Title) && (1 === requestNodeIndex))) { return this._Title_1_3; }
    if (((token === import249.ApplicationContainer) && (1 === requestNodeIndex))) { return this._ApplicationContainer_1_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.debug(1,1,8);
    if (this._ApplicationContainer_1_4.ngDoCheck(this,this._el_1,throwOnChange)) { this.compView_1.markAsCheckOnce(); }
    this.compView_1.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_1.destroy();
    this._ApplicationContainer_1_4.ngOnDestroy();
  }
  handleEvent_1(eventName:string,$event:any):boolean {
    this.debug(1,1,8);
    this.compView_1.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._ApplicationContainer_1_4.handleEvent(eventName,$event) && result);
    return result;
  }
}