/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from './bank-account-tab.component';
import * as import1 from '@angular/core/src/change_detection/change_detection_util';
import * as import2 from '@angular/core/src/linker/view';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/linker/debug_context';
import * as import5 from '@angular/core/src/render/api';
import * as import6 from '@angular/core/src/metadata/view';
import * as import7 from '@angular/core/src/linker/view_type';
import * as import8 from '@angular/core/src/change_detection/constants';
import * as import9 from '@angular/core/src/linker/component_factory';
import * as import10 from '@angular/forms/src/form_builder';
import * as import11 from '@angular/material/core/option/option';
import * as import12 from '@angular/material/core/compatibility/compatibility';
import * as import13 from '../../../../node_modules/@angular/material/core/option/option.ngfactory';
import * as import14 from '../../../../node_modules/@angular/material/core/compatibility/compatibility.ngfactory';
import * as import15 from '@angular/core/src/linker/view_container';
import * as import16 from '@angular/core/src/linker/element_ref';
import * as import17 from '@angular/forms/src/directives/reactive_directives/form_group_directive';
import * as import18 from '@angular/forms/src/directives/control_container';
import * as import19 from '@angular/forms/src/directives/ng_control_status';
import * as import20 from '@angular/material/input/input-container';
import * as import21 from '@angular/forms/src/directives/default_value_accessor';
import * as import22 from '@angular/forms/src/directives/control_value_accessor';
import * as import23 from '@angular/forms/src/directives/reactive_directives/form_control_name';
import * as import24 from '@angular/forms/src/directives/ng_control';
import * as import25 from '../../../../node_modules/@angular/forms/src/directives/reactive_directives/form_group_directive.ngfactory';
import * as import26 from '../../../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import27 from '../../../../node_modules/@angular/material/input/input-container.ngfactory';
import * as import28 from '@angular/core/src/linker/query_list';
import * as import29 from '../../../../node_modules/@angular/forms/src/directives/default_value_accessor.ngfactory';
import * as import30 from '../../../../node_modules/@angular/forms/src/directives/reactive_directives/form_control_name.ngfactory';
import * as import31 from '@angular/material/autocomplete/autocomplete-trigger';
import * as import32 from '@angular/material/autocomplete/autocomplete';
import * as import33 from '@angular/core/src/linker/template_ref';
import * as import34 from '@angular/common/src/directives/ng_for';
import * as import35 from '@angular/common/src/directives/ng_if';
import * as import36 from '@angular/material/button/button';
import * as import37 from '../../../../node_modules/@angular/material/autocomplete/autocomplete-trigger.ngfactory';
import * as import38 from '../../../../node_modules/@angular/material/autocomplete/autocomplete.ngfactory';
import * as import39 from '../../../../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import40 from '../../../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import41 from '../../../../node_modules/@angular/material/button/button.ngfactory';
import * as import42 from '@angular/material/core/overlay/overlay';
import * as import43 from '@angular/material/core/rtl/dir';
import * as import44 from '@angular/core/src/zone/ng_zone';
import * as import45 from '@angular/core/src/change_detection/differs/iterable_differs';
export class Wrapper_BankAccountTabComponent {
  /*private*/ _eventHandler:Function;
  context:import0.BankAccountTabComponent;
  /*private*/ _changed:boolean;
  /*private*/ _expr_0:any;
  subscription0:any;
  constructor(p0:any) {
    this._changed = false;
    this.context = new import0.BankAccountTabComponent(p0);
    this._expr_0 = import1.UNINITIALIZED;
  }
  ngOnDetach(view:import2.AppView<any>,componentView:import2.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
    (this.subscription0 && this.subscription0.unsubscribe());
  }
  check_bankAccount(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_0,currValue))) {
      this._changed = true;
      this.context.bankAccount = currValue;
      this._expr_0 = currValue;
    }
  }
  ngDoCheck(view:import2.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import2.AppView<any>,componentView:import2.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import2.AppView<any>,_eventHandler:any,emit0:boolean):void {
    this._eventHandler = _eventHandler;
    if (emit0) { (this.subscription0 = this.context.updateBankAccount.subscribe(_eventHandler.bind(view,'updateBankAccount'))); }
  }
}
const nodeDebugInfos_BankAccountTabComponent_Host0:import4.StaticNodeDebugInfo[] = [new import4.StaticNodeDebugInfo([import0.BankAccountTabComponent],import0.BankAccountTabComponent,{})];
var renderType_BankAccountTabComponent_Host:import5.RenderComponentType = import3.createRenderComponentType('',0,import6.ViewEncapsulation.None,([] as any[]),{});
class View_BankAccountTabComponent_Host0 extends import2.DebugAppView<any> {
  _el_0:any;
  compView_0:import2.AppView<import0.BankAccountTabComponent>;
  _BankAccountTabComponent_0_3:Wrapper_BankAccountTabComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_BankAccountTabComponent_Host0,renderType_BankAccountTabComponent_Host,import7.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import8.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_BankAccountTabComponent_Host0);
  }
  createInternal(rootSelector:string):import9.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'bank-account-tab',import3.EMPTY_INLINE_ARRAY,rootSelector,this.debug(0,0,0));
    this.compView_0 = new View_BankAccountTabComponent0(this.viewUtils,this,0,this._el_0);
    this._BankAccountTabComponent_0_3 = new Wrapper_BankAccountTabComponent(this.injectorGet(import10.FormBuilder,this.parentIndex));
    this.compView_0.create(this._BankAccountTabComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import9.ComponentRef_<any>(0,this,this._el_0,this._BankAccountTabComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.BankAccountTabComponent) && (0 === requestNodeIndex))) { return this._BankAccountTabComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.debug(0,0,0);
    if (this._BankAccountTabComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange)) { this.compView_0.markAsCheckOnce(); }
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
    this._BankAccountTabComponent_0_3.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const BankAccountTabComponentNgFactory:import9.ComponentFactory<import0.BankAccountTabComponent> = new import9.ComponentFactory<import0.BankAccountTabComponent>('bank-account-tab',View_BankAccountTabComponent_Host0,import0.BankAccountTabComponent);
const styles_BankAccountTabComponent:any[] = ([] as any[]);
const nodeDebugInfos_BankAccountTabComponent1:import4.StaticNodeDebugInfo[] = [
  new import4.StaticNodeDebugInfo([
    import11.MdOption,
    import12.MdPrefixRejector
  ]
  ,import11.MdOption,{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{})
]
;
class View_BankAccountTabComponent1 extends import2.DebugAppView<any> {
  _el_0:any;
  compView_0:import2.AppView<import11.MdOption>;
  _MdOption_0_3:import13.Wrapper_MdOption;
  _MdPrefixRejector_0_4:import14.Wrapper_MdPrefixRejector;
  _text_1:any;
  /*private*/ _expr_5:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import15.ViewContainer) {
    super(View_BankAccountTabComponent1,renderType_BankAccountTabComponent,import7.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import8.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_BankAccountTabComponent1,declaredViewContainer);
    this._expr_5 = import1.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import9.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'md-option',new import3.InlineArray4(4,'role','option','style','overflow: hidden !important'),this.debug(0,10,12));
    this.compView_0 = new import13.View_MdOption0(this.viewUtils,this,0,this._el_0);
    this._MdOption_0_3 = new import13.Wrapper_MdOption(new import16.ElementRef(this._el_0),this.renderer);
    this._MdPrefixRejector_0_4 = new import14.Wrapper_MdPrefixRejector(this.parentView.parentView.injectorGet(import12.MATERIAL_COMPATIBILITY_MODE,this.parentView.parentIndex,(null as any)));
    this._text_1 = this.renderer.createText((null as any),'',this.debug(1,10,108));
    this.compView_0.create(this._MdOption_0_3.context);
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_0,new import3.InlineArray4(4,'click',(null as any),'keydown',(null as any)),this.eventHandler(this.handleEvent_0));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import11.MdOption) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._MdOption_0_3.context; }
    if (((token === import12.MdPrefixRejector) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._MdPrefixRejector_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.debug(0,10,93);
    const currVal_0_0_0:any = this.context.$implicit;
    this._MdOption_0_3.check_value(currVal_0_0_0,throwOnChange,false);
    this._MdOption_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.debug(0,10,12);
    this._MdPrefixRejector_0_4.ngDoCheck(this,this._el_0,throwOnChange);
    this._MdOption_0_3.checkHost(this,this.compView_0,this._el_0,throwOnChange);
    this.debug(1,10,108);
    const currVal_5:any = import3.inlineInterpolate(1,'\n                ',this.context.$implicit,'\n            ');
    if (import3.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setText(this._text_1,currVal_5);
      this._expr_5 = currVal_5;
    }
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  dirtyParentQueriesInternal():void {
    (<View_BankAccountTabComponent0>this.parentView)._query_MdOption_14_0.setDirty();
  }
  destroyInternal():void {
    this.compView_0.destroy();
    this._MdOption_0_3.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  visitProjectableNodesInternal(nodeIndex:number,ngContentIndex:number,cb:any,ctx:any):void {
    if (((nodeIndex == 0) && (ngContentIndex == 0))) { cb(this._text_1,ctx); }
  }
  handleEvent_0(eventName:string,$event:any):boolean {
    this.debug(0,10,12);
    this.compView_0.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._MdOption_0_3.handleEvent(eventName,$event) && result);
    return result;
  }
}
const nodeDebugInfos_BankAccountTabComponent2:import4.StaticNodeDebugInfo[] = [
  new import4.StaticNodeDebugInfo([
    import17.FormGroupDirective,
    import18.ControlContainer,
    import19.NgControlStatusGroup
  ]
  ,(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo([import20.MdInputContainer],import20.MdInputContainer,{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo([
    import21.DefaultValueAccessor,
    import22.NG_VALUE_ACCESSOR,
    import23.FormControlName,
    import24.NgControl,
    import20.MdInputDirective,
    import19.NgControlStatus
  ]
  ,(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo([import20.MdInputContainer],import20.MdInputContainer,{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo([
    import21.DefaultValueAccessor,
    import22.NG_VALUE_ACCESSOR,
    import23.FormControlName,
    import24.NgControl,
    import20.MdInputDirective,
    import19.NgControlStatus
  ]
  ,(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{})
]
;
class View_BankAccountTabComponent2 extends import2.DebugAppView<any> {
  _el_0:any;
  _FormGroupDirective_0_3:import25.Wrapper_FormGroupDirective;
  _ControlContainer_0_4:any;
  _NgControlStatusGroup_0_5:import26.Wrapper_NgControlStatusGroup;
  _text_1:any;
  _el_2:any;
  compView_2:import2.AppView<import20.MdInputContainer>;
  _MdInputContainer_2_3:import27.Wrapper_MdInputContainer;
  _query_MdInputDirective_2_0:import28.QueryList<any>;
  _query_MdPlaceholder_2_1:import28.QueryList<any>;
  _query_MdHint_2_2:import28.QueryList<any>;
  _text_3:any;
  _el_4:any;
  _DefaultValueAccessor_4_3:import29.Wrapper_DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_4_4:any[];
  _FormControlName_4_5:import30.Wrapper_FormControlName;
  _NgControl_4_6:any;
  _MdInputDirective_4_7:import27.Wrapper_MdInputDirective;
  _NgControlStatus_4_8:import26.Wrapper_NgControlStatus;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  compView_7:import2.AppView<import20.MdInputContainer>;
  _MdInputContainer_7_3:import27.Wrapper_MdInputContainer;
  _query_MdInputDirective_7_0:import28.QueryList<any>;
  _query_MdPlaceholder_7_1:import28.QueryList<any>;
  _query_MdHint_7_2:import28.QueryList<any>;
  _text_8:any;
  _el_9:any;
  _DefaultValueAccessor_9_3:import29.Wrapper_DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_9_4:any[];
  _FormControlName_9_5:import30.Wrapper_FormControlName;
  _NgControl_9_6:any;
  _MdInputDirective_9_7:import27.Wrapper_MdInputDirective;
  _NgControlStatus_9_8:import26.Wrapper_NgControlStatus;
  _text_10:any;
  _text_11:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import15.ViewContainer) {
    super(View_BankAccountTabComponent2,renderType_BankAccountTabComponent,import7.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import8.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_BankAccountTabComponent2,declaredViewContainer);
  }
  createInternal(rootSelector:string):import9.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray2(2,'class','contact-form-row'),this.debug(0,22,8));
    this._FormGroupDirective_0_3 = new import25.Wrapper_FormGroupDirective((null as any),(null as any));
    this._ControlContainer_0_4 = this._FormGroupDirective_0_3.context;
    this._NgControlStatusGroup_0_5 = new import26.Wrapper_NgControlStatusGroup(this._ControlContainer_0_4);
    this._text_1 = this.renderer.createText(this._el_0,'\n          ',this.debug(1,22,140));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'md-input-container',new import3.InlineArray2(2,'floatPlaceholder','always'),this.debug(2,23,10));
    this.compView_2 = new import27.View_MdInputContainer0(this.viewUtils,this,2,this._el_2);
    this._MdInputContainer_2_3 = new import27.Wrapper_MdInputContainer();
    this._query_MdInputDirective_2_0 = new import28.QueryList<any>();
    this._query_MdPlaceholder_2_1 = new import28.QueryList<any>();
    this._query_MdHint_2_2 = new import28.QueryList<any>();
    this._text_3 = this.renderer.createText((null as any),'\n            ',this.debug(3,23,56));
    this._el_4 = import3.createRenderElement(this.renderer,(null as any),'input',new import3.InlineArray8(6,'formControlName','accountNumber','mdInput','','placeholder','Account Number'),this.debug(4,24,12));
    this._DefaultValueAccessor_4_3 = new import29.Wrapper_DefaultValueAccessor(this.renderer,new import16.ElementRef(this._el_4));
    this._NG_VALUE_ACCESSOR_4_4 = [this._DefaultValueAccessor_4_3.context];
    this._FormControlName_4_5 = new import30.Wrapper_FormControlName(this._ControlContainer_0_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_4_4);
    this._NgControl_4_6 = this._FormControlName_4_5.context;
    this._MdInputDirective_4_7 = new import27.Wrapper_MdInputDirective(new import16.ElementRef(this._el_4),this.renderer,this._NgControl_4_6);
    this._NgControlStatus_4_8 = new import26.Wrapper_NgControlStatus(this._NgControl_4_6);
    this._text_5 = this.renderer.createText((null as any),'         \n          ',this.debug(5,24,88));
    this.compView_2.create(this._MdInputContainer_2_3.context);
    this._text_6 = this.renderer.createText(this._el_0,'\n          ',this.debug(6,25,31));
    this._el_7 = import3.createRenderElement(this.renderer,this._el_0,'md-input-container',new import3.InlineArray2(2,'floatPlaceholder','always'),this.debug(7,26,10));
    this.compView_7 = new import27.View_MdInputContainer0(this.viewUtils,this,7,this._el_7);
    this._MdInputContainer_7_3 = new import27.Wrapper_MdInputContainer();
    this._query_MdInputDirective_7_0 = new import28.QueryList<any>();
    this._query_MdPlaceholder_7_1 = new import28.QueryList<any>();
    this._query_MdHint_7_2 = new import28.QueryList<any>();
    this._text_8 = this.renderer.createText((null as any),'\n            ',this.debug(8,26,56));
    this._el_9 = import3.createRenderElement(this.renderer,(null as any),'input',new import3.InlineArray8(6,'formControlName','sortCode','mdInput','','placeholder','Sort Code'),this.debug(9,27,12));
    this._DefaultValueAccessor_9_3 = new import29.Wrapper_DefaultValueAccessor(this.renderer,new import16.ElementRef(this._el_9));
    this._NG_VALUE_ACCESSOR_9_4 = [this._DefaultValueAccessor_9_3.context];
    this._FormControlName_9_5 = new import30.Wrapper_FormControlName(this._ControlContainer_0_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_9_4);
    this._NgControl_9_6 = this._FormControlName_9_5.context;
    this._MdInputDirective_9_7 = new import27.Wrapper_MdInputDirective(new import16.ElementRef(this._el_9),this.renderer,this._NgControl_9_6);
    this._NgControlStatus_9_8 = new import26.Wrapper_NgControlStatus(this._NgControl_9_6);
    this._text_10 = this.renderer.createText((null as any),'         \n          ',this.debug(10,27,78));
    this.compView_7.create(this._MdInputContainer_7_3.context);
    this._text_11 = this.renderer.createText(this._el_0,'\n        ',this.debug(11,28,31));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_0,new import3.InlineArray4(4,'submit',(null as any),'reset',(null as any)),this.eventHandler(this.handleEvent_0));
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_2,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_2));
    var disposable_2:Function = import3.subscribeToRenderElement(this,this._el_4,new import3.InlineArray8(6,'input',(null as any),'blur',(null as any),'focus',(null as any)),this.eventHandler(this.handleEvent_4));
    var disposable_3:Function = import3.subscribeToRenderElement(this,this._el_7,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_7));
    var disposable_4:Function = import3.subscribeToRenderElement(this,this._el_9,new import3.InlineArray8(6,'input',(null as any),'blur',(null as any),'focus',(null as any)),this.eventHandler(this.handleEvent_9));
    this._query_MdInputDirective_2_0.reset([this._MdInputDirective_4_7.context]);
    this._MdInputContainer_2_3.context._mdInputChild = this._query_MdInputDirective_2_0.first;
    this._query_MdPlaceholder_2_1.reset(([] as any[]));
    this._MdInputContainer_2_3.context._placeholderChild = this._query_MdPlaceholder_2_1.first;
    this._query_MdInputDirective_7_0.reset([this._MdInputDirective_9_7.context]);
    this._MdInputContainer_7_3.context._mdInputChild = this._query_MdInputDirective_7_0.first;
    this._query_MdPlaceholder_7_1.reset(([] as any[]));
    this._MdInputContainer_7_3.context._placeholderChild = this._query_MdPlaceholder_7_1.first;
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11
    ]
    ),[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import21.DefaultValueAccessor) && (4 === requestNodeIndex))) { return this._DefaultValueAccessor_4_3.context; }
    if (((token === import22.NG_VALUE_ACCESSOR) && (4 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_4_4; }
    if (((token === import23.FormControlName) && (4 === requestNodeIndex))) { return this._FormControlName_4_5.context; }
    if (((token === import24.NgControl) && (4 === requestNodeIndex))) { return this._NgControl_4_6; }
    if (((token === import20.MdInputDirective) && (4 === requestNodeIndex))) { return this._MdInputDirective_4_7.context; }
    if (((token === import19.NgControlStatus) && (4 === requestNodeIndex))) { return this._NgControlStatus_4_8.context; }
    if (((token === import20.MdInputContainer) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 5)))) { return this._MdInputContainer_2_3.context; }
    if (((token === import21.DefaultValueAccessor) && (9 === requestNodeIndex))) { return this._DefaultValueAccessor_9_3.context; }
    if (((token === import22.NG_VALUE_ACCESSOR) && (9 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_9_4; }
    if (((token === import23.FormControlName) && (9 === requestNodeIndex))) { return this._FormControlName_9_5.context; }
    if (((token === import24.NgControl) && (9 === requestNodeIndex))) { return this._NgControl_9_6; }
    if (((token === import20.MdInputDirective) && (9 === requestNodeIndex))) { return this._MdInputDirective_9_7.context; }
    if (((token === import19.NgControlStatus) && (9 === requestNodeIndex))) { return this._NgControlStatus_9_8.context; }
    if (((token === import20.MdInputContainer) && ((7 <= requestNodeIndex) && (requestNodeIndex <= 10)))) { return this._MdInputContainer_7_3.context; }
    if (((token === import17.FormGroupDirective) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._FormGroupDirective_0_3.context; }
    if (((token === import18.ControlContainer) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._ControlContainer_0_4; }
    if (((token === import19.NgControlStatusGroup) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._NgControlStatusGroup_0_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.debug(0,22,107);
    const currVal_0_0_0:any = this.parentView.context.bankAccountTabForm;
    this._FormGroupDirective_0_3.check_form(currVal_0_0_0,throwOnChange,false);
    this._FormGroupDirective_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.debug(0,22,8);
    this._NgControlStatusGroup_0_5.ngDoCheck(this,this._el_0,throwOnChange);
    this.debug(2,23,30);
    const currVal_2_0_0:any = 'always';
    this._MdInputContainer_2_3.check_floatPlaceholder(currVal_2_0_0,throwOnChange,false);
    this._MdInputContainer_2_3.ngDoCheck(this,this._el_2,throwOnChange);
    this.debug(4,24,12);
    this._DefaultValueAccessor_4_3.ngDoCheck(this,this._el_4,throwOnChange);
    this.debug(4,24,56);
    const currVal_4_1_0:any = 'accountNumber';
    this._FormControlName_4_5.check_name(currVal_4_1_0,throwOnChange,false);
    this._FormControlName_4_5.ngDoCheck(this,this._el_4,throwOnChange);
    this.debug(4,24,27);
    const currVal_4_2_0:any = 'Account Number';
    this._MdInputDirective_4_7.check_placeholder(currVal_4_2_0,throwOnChange,false);
    this._MdInputDirective_4_7.ngDoCheck(this,this._el_4,throwOnChange);
    this.debug(4,24,12);
    this._NgControlStatus_4_8.ngDoCheck(this,this._el_4,throwOnChange);
    this.debug(7,26,30);
    const currVal_7_0_0:any = 'always';
    this._MdInputContainer_7_3.check_floatPlaceholder(currVal_7_0_0,throwOnChange,false);
    this._MdInputContainer_7_3.ngDoCheck(this,this._el_7,throwOnChange);
    this.debug(9,27,12);
    this._DefaultValueAccessor_9_3.ngDoCheck(this,this._el_9,throwOnChange);
    this.debug(9,27,51);
    const currVal_9_1_0:any = 'sortCode';
    this._FormControlName_9_5.check_name(currVal_9_1_0,throwOnChange,false);
    this._FormControlName_9_5.ngDoCheck(this,this._el_9,throwOnChange);
    this.debug(9,27,27);
    const currVal_9_2_0:any = 'Sort Code';
    this._MdInputDirective_9_7.check_placeholder(currVal_9_2_0,throwOnChange,false);
    this._MdInputDirective_9_7.ngDoCheck(this,this._el_9,throwOnChange);
    this.debug(9,27,12);
    this._NgControlStatus_9_8.ngDoCheck(this,this._el_9,throwOnChange);
    if (!throwOnChange) {
      if (this._query_MdHint_2_2.dirty) {
        this._query_MdHint_2_2.reset(([] as any[]));
        this._MdInputContainer_2_3.context._hintChildren = this._query_MdHint_2_2;
        this._query_MdHint_2_2.notifyOnChanges();
      }
      if (this._query_MdHint_7_2.dirty) {
        this._query_MdHint_7_2.reset(([] as any[]));
        this._MdInputContainer_7_3.context._hintChildren = this._query_MdHint_7_2;
        this._query_MdHint_7_2.notifyOnChanges();
      }
      this.debug(2,23,10);
      if ((this.numberOfChecks === 0)) { this._MdInputContainer_2_3.context.ngAfterContentInit(); }
      this.debug(7,26,10);
      if ((this.numberOfChecks === 0)) { this._MdInputContainer_7_3.context.ngAfterContentInit(); }
    }
    this._NgControlStatusGroup_0_5.checkHost(this,this,this._el_0,throwOnChange);
    this._MdInputContainer_2_3.checkHost(this,this.compView_2,this._el_2,throwOnChange);
    this._MdInputDirective_4_7.checkHost(this,this,this._el_4,throwOnChange);
    this._NgControlStatus_4_8.checkHost(this,this,this._el_4,throwOnChange);
    this._MdInputContainer_7_3.checkHost(this,this.compView_7,this._el_7,throwOnChange);
    this._MdInputDirective_9_7.checkHost(this,this,this._el_9,throwOnChange);
    this._NgControlStatus_9_8.checkHost(this,this,this._el_9,throwOnChange);
    this.compView_2.internalDetectChanges(throwOnChange);
    this.compView_7.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_2.destroy();
    this.compView_7.destroy();
    this._FormControlName_4_5.ngOnDestroy();
    this._MdInputDirective_4_7.ngOnDestroy();
    this.debug(4,24,12);
    this.debug(2,23,10);
    this._FormControlName_9_5.ngOnDestroy();
    this._MdInputDirective_9_7.ngOnDestroy();
    this.debug(9,27,12);
    this.debug(7,26,10);
    this._FormGroupDirective_0_3.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  visitProjectableNodesInternal(nodeIndex:number,ngContentIndex:number,cb:any,ctx:any):void {
    if (((nodeIndex == 2) && (ngContentIndex == 0))) {  }
    if (((nodeIndex == 2) && (ngContentIndex == 1))) {
      cb(this._text_3,ctx);
      cb(this._el_4,ctx);
      cb(this._text_5,ctx);
    }
    if (((nodeIndex == 2) && (ngContentIndex == 2))) {  }
    if (((nodeIndex == 2) && (ngContentIndex == 3))) {  }
    if (((nodeIndex == 2) && (ngContentIndex == 4))) {  }
    if (((nodeIndex == 7) && (ngContentIndex == 0))) {  }
    if (((nodeIndex == 7) && (ngContentIndex == 1))) {
      cb(this._text_8,ctx);
      cb(this._el_9,ctx);
      cb(this._text_10,ctx);
    }
    if (((nodeIndex == 7) && (ngContentIndex == 2))) {  }
    if (((nodeIndex == 7) && (ngContentIndex == 3))) {  }
    if (((nodeIndex == 7) && (ngContentIndex == 4))) {  }
  }
  handleEvent_0(eventName:string,$event:any):boolean {
    this.debug(0,22,8);
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._FormGroupDirective_0_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_2(eventName:string,$event:any):boolean {
    this.debug(2,23,10);
    this.compView_2.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._MdInputContainer_2_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_4(eventName:string,$event:any):boolean {
    this.debug(4,24,12);
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_4_3.handleEvent(eventName,$event) && result);
    result = (this._MdInputDirective_4_7.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_7(eventName:string,$event:any):boolean {
    this.debug(7,26,10);
    this.compView_7.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._MdInputContainer_7_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_9(eventName:string,$event:any):boolean {
    this.debug(9,27,12);
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_9_3.handleEvent(eventName,$event) && result);
    result = (this._MdInputDirective_9_7.handleEvent(eventName,$event) && result);
    return result;
  }
}
const nodeDebugInfos_BankAccountTabComponent3:import4.StaticNodeDebugInfo[] = [
  new import4.StaticNodeDebugInfo([
    import17.FormGroupDirective,
    import18.ControlContainer,
    import19.NgControlStatusGroup
  ]
  ,(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo([import20.MdInputContainer],import20.MdInputContainer,{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo([
    import21.DefaultValueAccessor,
    import22.NG_VALUE_ACCESSOR,
    import23.FormControlName,
    import24.NgControl,
    import20.MdInputDirective,
    import19.NgControlStatus
  ]
  ,(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo([import20.MdInputContainer],import20.MdInputContainer,{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo([
    import21.DefaultValueAccessor,
    import22.NG_VALUE_ACCESSOR,
    import23.FormControlName,
    import24.NgControl,
    import20.MdInputDirective,
    import19.NgControlStatus
  ]
  ,(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{})
]
;
class View_BankAccountTabComponent3 extends import2.DebugAppView<any> {
  _el_0:any;
  _FormGroupDirective_0_3:import25.Wrapper_FormGroupDirective;
  _ControlContainer_0_4:any;
  _NgControlStatusGroup_0_5:import26.Wrapper_NgControlStatusGroup;
  _text_1:any;
  _el_2:any;
  compView_2:import2.AppView<import20.MdInputContainer>;
  _MdInputContainer_2_3:import27.Wrapper_MdInputContainer;
  _query_MdInputDirective_2_0:import28.QueryList<any>;
  _query_MdPlaceholder_2_1:import28.QueryList<any>;
  _query_MdHint_2_2:import28.QueryList<any>;
  _text_3:any;
  _el_4:any;
  _DefaultValueAccessor_4_3:import29.Wrapper_DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_4_4:any[];
  _FormControlName_4_5:import30.Wrapper_FormControlName;
  _NgControl_4_6:any;
  _MdInputDirective_4_7:import27.Wrapper_MdInputDirective;
  _NgControlStatus_4_8:import26.Wrapper_NgControlStatus;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  compView_7:import2.AppView<import20.MdInputContainer>;
  _MdInputContainer_7_3:import27.Wrapper_MdInputContainer;
  _query_MdInputDirective_7_0:import28.QueryList<any>;
  _query_MdPlaceholder_7_1:import28.QueryList<any>;
  _query_MdHint_7_2:import28.QueryList<any>;
  _text_8:any;
  _el_9:any;
  _DefaultValueAccessor_9_3:import29.Wrapper_DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_9_4:any[];
  _FormControlName_9_5:import30.Wrapper_FormControlName;
  _NgControl_9_6:any;
  _MdInputDirective_9_7:import27.Wrapper_MdInputDirective;
  _NgControlStatus_9_8:import26.Wrapper_NgControlStatus;
  _text_10:any;
  _text_11:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import15.ViewContainer) {
    super(View_BankAccountTabComponent3,renderType_BankAccountTabComponent,import7.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import8.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_BankAccountTabComponent3,declaredViewContainer);
  }
  createInternal(rootSelector:string):import9.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray2(2,'class','contact-form-row'),this.debug(0,31,8));
    this._FormGroupDirective_0_3 = new import25.Wrapper_FormGroupDirective((null as any),(null as any));
    this._ControlContainer_0_4 = this._FormGroupDirective_0_3.context;
    this._NgControlStatusGroup_0_5 = new import26.Wrapper_NgControlStatusGroup(this._ControlContainer_0_4);
    this._text_1 = this.renderer.createText(this._el_0,'\n          ',this.debug(1,31,144));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'md-input-container',new import3.InlineArray2(2,'floatPlaceholder','always'),this.debug(2,32,10));
    this.compView_2 = new import27.View_MdInputContainer0(this.viewUtils,this,2,this._el_2);
    this._MdInputContainer_2_3 = new import27.Wrapper_MdInputContainer();
    this._query_MdInputDirective_2_0 = new import28.QueryList<any>();
    this._query_MdPlaceholder_2_1 = new import28.QueryList<any>();
    this._query_MdHint_2_2 = new import28.QueryList<any>();
    this._text_3 = this.renderer.createText((null as any),'\n            ',this.debug(3,32,56));
    this._el_4 = import3.createRenderElement(this.renderer,(null as any),'input',new import3.InlineArray8(6,'formControlName','iban','mdInput','','placeholder','IBAN'),this.debug(4,33,12));
    this._DefaultValueAccessor_4_3 = new import29.Wrapper_DefaultValueAccessor(this.renderer,new import16.ElementRef(this._el_4));
    this._NG_VALUE_ACCESSOR_4_4 = [this._DefaultValueAccessor_4_3.context];
    this._FormControlName_4_5 = new import30.Wrapper_FormControlName(this._ControlContainer_0_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_4_4);
    this._NgControl_4_6 = this._FormControlName_4_5.context;
    this._MdInputDirective_4_7 = new import27.Wrapper_MdInputDirective(new import16.ElementRef(this._el_4),this.renderer,this._NgControl_4_6);
    this._NgControlStatus_4_8 = new import26.Wrapper_NgControlStatus(this._NgControl_4_6);
    this._text_5 = this.renderer.createText((null as any),'         \n          ',this.debug(5,33,69));
    this.compView_2.create(this._MdInputContainer_2_3.context);
    this._text_6 = this.renderer.createText(this._el_0,'\n          ',this.debug(6,34,31));
    this._el_7 = import3.createRenderElement(this.renderer,this._el_0,'md-input-container',new import3.InlineArray2(2,'floatPlaceholder','always'),this.debug(7,35,10));
    this.compView_7 = new import27.View_MdInputContainer0(this.viewUtils,this,7,this._el_7);
    this._MdInputContainer_7_3 = new import27.Wrapper_MdInputContainer();
    this._query_MdInputDirective_7_0 = new import28.QueryList<any>();
    this._query_MdPlaceholder_7_1 = new import28.QueryList<any>();
    this._query_MdHint_7_2 = new import28.QueryList<any>();
    this._text_8 = this.renderer.createText((null as any),'\n            ',this.debug(8,35,56));
    this._el_9 = import3.createRenderElement(this.renderer,(null as any),'input',new import3.InlineArray8(6,'formControlName','swiftCode','mdInput','','placeholder','Swift Code'),this.debug(9,36,12));
    this._DefaultValueAccessor_9_3 = new import29.Wrapper_DefaultValueAccessor(this.renderer,new import16.ElementRef(this._el_9));
    this._NG_VALUE_ACCESSOR_9_4 = [this._DefaultValueAccessor_9_3.context];
    this._FormControlName_9_5 = new import30.Wrapper_FormControlName(this._ControlContainer_0_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_9_4);
    this._NgControl_9_6 = this._FormControlName_9_5.context;
    this._MdInputDirective_9_7 = new import27.Wrapper_MdInputDirective(new import16.ElementRef(this._el_9),this.renderer,this._NgControl_9_6);
    this._NgControlStatus_9_8 = new import26.Wrapper_NgControlStatus(this._NgControl_9_6);
    this._text_10 = this.renderer.createText((null as any),'         \n          ',this.debug(10,36,80));
    this.compView_7.create(this._MdInputContainer_7_3.context);
    this._text_11 = this.renderer.createText(this._el_0,'\n        ',this.debug(11,37,31));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_0,new import3.InlineArray4(4,'submit',(null as any),'reset',(null as any)),this.eventHandler(this.handleEvent_0));
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_2,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_2));
    var disposable_2:Function = import3.subscribeToRenderElement(this,this._el_4,new import3.InlineArray8(6,'input',(null as any),'blur',(null as any),'focus',(null as any)),this.eventHandler(this.handleEvent_4));
    var disposable_3:Function = import3.subscribeToRenderElement(this,this._el_7,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_7));
    var disposable_4:Function = import3.subscribeToRenderElement(this,this._el_9,new import3.InlineArray8(6,'input',(null as any),'blur',(null as any),'focus',(null as any)),this.eventHandler(this.handleEvent_9));
    this._query_MdInputDirective_2_0.reset([this._MdInputDirective_4_7.context]);
    this._MdInputContainer_2_3.context._mdInputChild = this._query_MdInputDirective_2_0.first;
    this._query_MdPlaceholder_2_1.reset(([] as any[]));
    this._MdInputContainer_2_3.context._placeholderChild = this._query_MdPlaceholder_2_1.first;
    this._query_MdInputDirective_7_0.reset([this._MdInputDirective_9_7.context]);
    this._MdInputContainer_7_3.context._mdInputChild = this._query_MdInputDirective_7_0.first;
    this._query_MdPlaceholder_7_1.reset(([] as any[]));
    this._MdInputContainer_7_3.context._placeholderChild = this._query_MdPlaceholder_7_1.first;
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11
    ]
    ),[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import21.DefaultValueAccessor) && (4 === requestNodeIndex))) { return this._DefaultValueAccessor_4_3.context; }
    if (((token === import22.NG_VALUE_ACCESSOR) && (4 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_4_4; }
    if (((token === import23.FormControlName) && (4 === requestNodeIndex))) { return this._FormControlName_4_5.context; }
    if (((token === import24.NgControl) && (4 === requestNodeIndex))) { return this._NgControl_4_6; }
    if (((token === import20.MdInputDirective) && (4 === requestNodeIndex))) { return this._MdInputDirective_4_7.context; }
    if (((token === import19.NgControlStatus) && (4 === requestNodeIndex))) { return this._NgControlStatus_4_8.context; }
    if (((token === import20.MdInputContainer) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 5)))) { return this._MdInputContainer_2_3.context; }
    if (((token === import21.DefaultValueAccessor) && (9 === requestNodeIndex))) { return this._DefaultValueAccessor_9_3.context; }
    if (((token === import22.NG_VALUE_ACCESSOR) && (9 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_9_4; }
    if (((token === import23.FormControlName) && (9 === requestNodeIndex))) { return this._FormControlName_9_5.context; }
    if (((token === import24.NgControl) && (9 === requestNodeIndex))) { return this._NgControl_9_6; }
    if (((token === import20.MdInputDirective) && (9 === requestNodeIndex))) { return this._MdInputDirective_9_7.context; }
    if (((token === import19.NgControlStatus) && (9 === requestNodeIndex))) { return this._NgControlStatus_9_8.context; }
    if (((token === import20.MdInputContainer) && ((7 <= requestNodeIndex) && (requestNodeIndex <= 10)))) { return this._MdInputContainer_7_3.context; }
    if (((token === import17.FormGroupDirective) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._FormGroupDirective_0_3.context; }
    if (((token === import18.ControlContainer) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._ControlContainer_0_4; }
    if (((token === import19.NgControlStatusGroup) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._NgControlStatusGroup_0_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.debug(0,31,111);
    const currVal_0_0_0:any = this.parentView.context.bankAccountTabForm;
    this._FormGroupDirective_0_3.check_form(currVal_0_0_0,throwOnChange,false);
    this._FormGroupDirective_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.debug(0,31,8);
    this._NgControlStatusGroup_0_5.ngDoCheck(this,this._el_0,throwOnChange);
    this.debug(2,32,30);
    const currVal_2_0_0:any = 'always';
    this._MdInputContainer_2_3.check_floatPlaceholder(currVal_2_0_0,throwOnChange,false);
    this._MdInputContainer_2_3.ngDoCheck(this,this._el_2,throwOnChange);
    this.debug(4,33,12);
    this._DefaultValueAccessor_4_3.ngDoCheck(this,this._el_4,throwOnChange);
    this.debug(4,33,46);
    const currVal_4_1_0:any = 'iban';
    this._FormControlName_4_5.check_name(currVal_4_1_0,throwOnChange,false);
    this._FormControlName_4_5.ngDoCheck(this,this._el_4,throwOnChange);
    this.debug(4,33,27);
    const currVal_4_2_0:any = 'IBAN';
    this._MdInputDirective_4_7.check_placeholder(currVal_4_2_0,throwOnChange,false);
    this._MdInputDirective_4_7.ngDoCheck(this,this._el_4,throwOnChange);
    this.debug(4,33,12);
    this._NgControlStatus_4_8.ngDoCheck(this,this._el_4,throwOnChange);
    this.debug(7,35,30);
    const currVal_7_0_0:any = 'always';
    this._MdInputContainer_7_3.check_floatPlaceholder(currVal_7_0_0,throwOnChange,false);
    this._MdInputContainer_7_3.ngDoCheck(this,this._el_7,throwOnChange);
    this.debug(9,36,12);
    this._DefaultValueAccessor_9_3.ngDoCheck(this,this._el_9,throwOnChange);
    this.debug(9,36,52);
    const currVal_9_1_0:any = 'swiftCode';
    this._FormControlName_9_5.check_name(currVal_9_1_0,throwOnChange,false);
    this._FormControlName_9_5.ngDoCheck(this,this._el_9,throwOnChange);
    this.debug(9,36,27);
    const currVal_9_2_0:any = 'Swift Code';
    this._MdInputDirective_9_7.check_placeholder(currVal_9_2_0,throwOnChange,false);
    this._MdInputDirective_9_7.ngDoCheck(this,this._el_9,throwOnChange);
    this.debug(9,36,12);
    this._NgControlStatus_9_8.ngDoCheck(this,this._el_9,throwOnChange);
    if (!throwOnChange) {
      if (this._query_MdHint_2_2.dirty) {
        this._query_MdHint_2_2.reset(([] as any[]));
        this._MdInputContainer_2_3.context._hintChildren = this._query_MdHint_2_2;
        this._query_MdHint_2_2.notifyOnChanges();
      }
      if (this._query_MdHint_7_2.dirty) {
        this._query_MdHint_7_2.reset(([] as any[]));
        this._MdInputContainer_7_3.context._hintChildren = this._query_MdHint_7_2;
        this._query_MdHint_7_2.notifyOnChanges();
      }
      this.debug(2,32,10);
      if ((this.numberOfChecks === 0)) { this._MdInputContainer_2_3.context.ngAfterContentInit(); }
      this.debug(7,35,10);
      if ((this.numberOfChecks === 0)) { this._MdInputContainer_7_3.context.ngAfterContentInit(); }
    }
    this._NgControlStatusGroup_0_5.checkHost(this,this,this._el_0,throwOnChange);
    this._MdInputContainer_2_3.checkHost(this,this.compView_2,this._el_2,throwOnChange);
    this._MdInputDirective_4_7.checkHost(this,this,this._el_4,throwOnChange);
    this._NgControlStatus_4_8.checkHost(this,this,this._el_4,throwOnChange);
    this._MdInputContainer_7_3.checkHost(this,this.compView_7,this._el_7,throwOnChange);
    this._MdInputDirective_9_7.checkHost(this,this,this._el_9,throwOnChange);
    this._NgControlStatus_9_8.checkHost(this,this,this._el_9,throwOnChange);
    this.compView_2.internalDetectChanges(throwOnChange);
    this.compView_7.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_2.destroy();
    this.compView_7.destroy();
    this._FormControlName_4_5.ngOnDestroy();
    this._MdInputDirective_4_7.ngOnDestroy();
    this.debug(4,33,12);
    this.debug(2,32,10);
    this._FormControlName_9_5.ngOnDestroy();
    this._MdInputDirective_9_7.ngOnDestroy();
    this.debug(9,36,12);
    this.debug(7,35,10);
    this._FormGroupDirective_0_3.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  visitProjectableNodesInternal(nodeIndex:number,ngContentIndex:number,cb:any,ctx:any):void {
    if (((nodeIndex == 2) && (ngContentIndex == 0))) {  }
    if (((nodeIndex == 2) && (ngContentIndex == 1))) {
      cb(this._text_3,ctx);
      cb(this._el_4,ctx);
      cb(this._text_5,ctx);
    }
    if (((nodeIndex == 2) && (ngContentIndex == 2))) {  }
    if (((nodeIndex == 2) && (ngContentIndex == 3))) {  }
    if (((nodeIndex == 2) && (ngContentIndex == 4))) {  }
    if (((nodeIndex == 7) && (ngContentIndex == 0))) {  }
    if (((nodeIndex == 7) && (ngContentIndex == 1))) {
      cb(this._text_8,ctx);
      cb(this._el_9,ctx);
      cb(this._text_10,ctx);
    }
    if (((nodeIndex == 7) && (ngContentIndex == 2))) {  }
    if (((nodeIndex == 7) && (ngContentIndex == 3))) {  }
    if (((nodeIndex == 7) && (ngContentIndex == 4))) {  }
  }
  handleEvent_0(eventName:string,$event:any):boolean {
    this.debug(0,31,8);
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._FormGroupDirective_0_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_2(eventName:string,$event:any):boolean {
    this.debug(2,32,10);
    this.compView_2.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._MdInputContainer_2_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_4(eventName:string,$event:any):boolean {
    this.debug(4,33,12);
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_4_3.handleEvent(eventName,$event) && result);
    result = (this._MdInputDirective_4_7.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_7(eventName:string,$event:any):boolean {
    this.debug(7,35,10);
    this.compView_7.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._MdInputContainer_7_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_9(eventName:string,$event:any):boolean {
    this.debug(9,36,12);
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_9_3.handleEvent(eventName,$event) && result);
    result = (this._MdInputDirective_9_7.handleEvent(eventName,$event) && result);
    return result;
  }
}
const nodeDebugInfos_BankAccountTabComponent0:import4.StaticNodeDebugInfo[] = [
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo([
    import17.FormGroupDirective,
    import18.ControlContainer,
    import19.NgControlStatusGroup
  ]
  ,(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo([
    import17.FormGroupDirective,
    import18.ControlContainer,
    import19.NgControlStatusGroup
  ]
  ,(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo([import20.MdInputContainer],import20.MdInputContainer,{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo([
    import31.MdAutocompleteTrigger,
    import21.DefaultValueAccessor,
    import22.NG_VALUE_ACCESSOR,
    import23.FormControlName,
    import24.NgControl,
    import20.MdInputDirective,
    import19.NgControlStatus
  ]
  ,(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo([
    import12.MdPrefixRejector,
    import32.MdAutocomplete
  ]
  ,import32.MdAutocomplete,{accountTypeSelect: import32.MdAutocomplete}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo([
    import33.TemplateRef,
    import34.NgFor
  ]
  ,(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo([import20.MdInputContainer],import20.MdInputContainer,{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo([
    import21.DefaultValueAccessor,
    import22.NG_VALUE_ACCESSOR,
    import23.FormControlName,
    import24.NgControl,
    import20.MdInputDirective,
    import19.NgControlStatus
  ]
  ,(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo([import20.MdInputContainer],import20.MdInputContainer,{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo([
    import21.DefaultValueAccessor,
    import22.NG_VALUE_ACCESSOR,
    import23.FormControlName,
    import24.NgControl,
    import20.MdInputDirective,
    import19.NgControlStatus
  ]
  ,(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo([
    import33.TemplateRef,
    import35.NgIf
  ]
  ,(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo([
    import33.TemplateRef,
    import35.NgIf
  ]
  ,(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo([
    import12.MdPrefixRejector,
    import36.MdButton,
    import36.MdButtonCssMatStyler
  ]
  ,import36.MdButton,{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{})
]
;
var renderType_BankAccountTabComponent:import5.RenderComponentType = import3.createRenderComponentType('/Users/jonoforbes/Developer/Ether/winecellar/src/bank-accounts/components/bank-account-tab/bank-account-tab.component.ts class BankAccountTabComponent - inline template',0,import6.ViewEncapsulation.None,styles_BankAccountTabComponent,{});
export class View_BankAccountTabComponent0 extends import2.DebugAppView<import0.BankAccountTabComponent> {
  _text_0:any;
  _el_1:any;
  _text_2:any;
  _el_3:any;
  _text_4:any;
  _el_5:any;
  _FormGroupDirective_5_3:import25.Wrapper_FormGroupDirective;
  _ControlContainer_5_4:any;
  _NgControlStatusGroup_5_5:import26.Wrapper_NgControlStatusGroup;
  _text_6:any;
  _el_7:any;
  _FormGroupDirective_7_3:import25.Wrapper_FormGroupDirective;
  _ControlContainer_7_4:any;
  _NgControlStatusGroup_7_5:import26.Wrapper_NgControlStatusGroup;
  _text_8:any;
  _el_9:any;
  compView_9:import2.AppView<import20.MdInputContainer>;
  _MdInputContainer_9_3:import27.Wrapper_MdInputContainer;
  _query_MdInputDirective_9_0:import28.QueryList<any>;
  _query_MdPlaceholder_9_1:import28.QueryList<any>;
  _query_MdHint_9_2:import28.QueryList<any>;
  _text_10:any;
  _el_11:any;
  /*private*/ _vc_11:import15.ViewContainer;
  _MdAutocompleteTrigger_11_5:import37.Wrapper_MdAutocompleteTrigger;
  _DefaultValueAccessor_11_6:import29.Wrapper_DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_11_7:any[];
  _FormControlName_11_8:import30.Wrapper_FormControlName;
  _NgControl_11_9:any;
  _MdInputDirective_11_10:import27.Wrapper_MdInputDirective;
  _NgControlStatus_11_11:import26.Wrapper_NgControlStatus;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  compView_14:import2.AppView<import32.MdAutocomplete>;
  _MdPrefixRejector_14_3:import14.Wrapper_MdPrefixRejector;
  _MdAutocomplete_14_4:import38.Wrapper_MdAutocomplete;
  _query_MdOption_14_0:import28.QueryList<any>;
  _text_15:any;
  _anchor_16:any;
  /*private*/ _vc_16:import15.ViewContainer;
  _TemplateRef_16_5:any;
  _NgFor_16_6:import39.Wrapper_NgFor;
  _text_17:any;
  _text_18:any;
  _el_19:any;
  compView_19:import2.AppView<import20.MdInputContainer>;
  _MdInputContainer_19_3:import27.Wrapper_MdInputContainer;
  _query_MdInputDirective_19_0:import28.QueryList<any>;
  _query_MdPlaceholder_19_1:import28.QueryList<any>;
  _query_MdHint_19_2:import28.QueryList<any>;
  _text_20:any;
  _el_21:any;
  _DefaultValueAccessor_21_3:import29.Wrapper_DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_21_4:any[];
  _FormControlName_21_5:import30.Wrapper_FormControlName;
  _NgControl_21_6:any;
  _MdInputDirective_21_7:import27.Wrapper_MdInputDirective;
  _NgControlStatus_21_8:import26.Wrapper_NgControlStatus;
  _text_22:any;
  _text_23:any;
  _el_24:any;
  compView_24:import2.AppView<import20.MdInputContainer>;
  _MdInputContainer_24_3:import27.Wrapper_MdInputContainer;
  _query_MdInputDirective_24_0:import28.QueryList<any>;
  _query_MdPlaceholder_24_1:import28.QueryList<any>;
  _query_MdHint_24_2:import28.QueryList<any>;
  _text_25:any;
  _el_26:any;
  _DefaultValueAccessor_26_3:import29.Wrapper_DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_26_4:any[];
  _FormControlName_26_5:import30.Wrapper_FormControlName;
  _NgControl_26_6:any;
  _MdInputDirective_26_7:import27.Wrapper_MdInputDirective;
  _NgControlStatus_26_8:import26.Wrapper_NgControlStatus;
  _text_27:any;
  _text_28:any;
  _text_29:any;
  _anchor_30:any;
  /*private*/ _vc_30:import15.ViewContainer;
  _TemplateRef_30_5:any;
  _NgIf_30_6:import40.Wrapper_NgIf;
  _text_31:any;
  _anchor_32:any;
  /*private*/ _vc_32:import15.ViewContainer;
  _TemplateRef_32_5:any;
  _NgIf_32_6:import40.Wrapper_NgIf;
  _text_33:any;
  _el_34:any;
  compView_34:import2.AppView<import36.MdButton>;
  _MdPrefixRejector_34_3:import14.Wrapper_MdPrefixRejector;
  _MdButton_34_4:import41.Wrapper_MdButton;
  _MdButtonCssMatStyler_34_5:import41.Wrapper_MdButtonCssMatStyler;
  _el_35:any;
  _text_36:any;
  _text_37:any;
  _text_38:any;
  _text_39:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_BankAccountTabComponent0,renderType_BankAccountTabComponent,import7.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import8.ChangeDetectorStatus.CheckOnce,nodeDebugInfos_BankAccountTabComponent0);
  }
  createInternal(rootSelector:string):import9.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n    ',this.debug(0,0,0));
    this._el_1 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','contactTabContainer'),this.debug(1,1,4));
    this._text_2 = this.renderer.createText(this._el_1,'\n      ',this.debug(2,1,37));
    this._el_3 = import3.createRenderElement(this.renderer,this._el_1,'div',new import3.InlineArray2(2,'style','height: 15px'),this.debug(3,2,6));
    this._text_4 = this.renderer.createText(this._el_1,'\n            ',this.debug(4,2,38));
    this._el_5 = import3.createRenderElement(this.renderer,this._el_1,'form',import3.EMPTY_INLINE_ARRAY,this.debug(5,3,12));
    this._FormGroupDirective_5_3 = new import25.Wrapper_FormGroupDirective((null as any),(null as any));
    this._ControlContainer_5_4 = this._FormGroupDirective_5_3.context;
    this._NgControlStatusGroup_5_5 = new import26.Wrapper_NgControlStatusGroup(this._ControlContainer_5_4);
    this._text_6 = this.renderer.createText(this._el_5,'\n\n        ',this.debug(6,3,75));
    this._el_7 = import3.createRenderElement(this.renderer,this._el_5,'div',new import3.InlineArray2(2,'class','contact-form-row'),this.debug(7,5,8));
    this._FormGroupDirective_7_3 = new import25.Wrapper_FormGroupDirective((null as any),(null as any));
    this._ControlContainer_7_4 = this._FormGroupDirective_7_3.context;
    this._NgControlStatusGroup_7_5 = new import26.Wrapper_NgControlStatusGroup(this._ControlContainer_7_4);
    this._text_8 = this.renderer.createText(this._el_7,'\n          ',this.debug(8,5,71));
    this._el_9 = import3.createRenderElement(this.renderer,this._el_7,'md-input-container',new import3.InlineArray2(2,'floatPlaceholder','always'),this.debug(9,6,10));
    this.compView_9 = new import27.View_MdInputContainer0(this.viewUtils,this,9,this._el_9);
    this._MdInputContainer_9_3 = new import27.Wrapper_MdInputContainer();
    this._query_MdInputDirective_9_0 = new import28.QueryList<any>();
    this._query_MdPlaceholder_9_1 = new import28.QueryList<any>();
    this._query_MdHint_9_2 = new import28.QueryList<any>();
    this._text_10 = this.renderer.createText((null as any),'\n            ',this.debug(10,6,56));
    this._el_11 = import3.createRenderElement(this.renderer,(null as any),'input',new import3.InlineArray16(14,'aria-autocomplete','list','aria-multiline','false','autocomplete','off','formControlName','accountType','mdInput','','placeholder','Account Type','role','combobox'),this.debug(11,7,12));
    this._vc_11 = new import15.ViewContainer(11,9,this,this._el_11);
    this._MdAutocompleteTrigger_11_5 = new import37.Wrapper_MdAutocompleteTrigger(new import16.ElementRef(this._el_11),this.parentView.injectorGet(import42.Overlay,this.parentIndex),this._vc_11.vcRef,this.parentView.injectorGet(import43.Dir,this.parentIndex,(null as any)),this.parentView.injectorGet(import44.NgZone,this.parentIndex),this._MdInputContainer_9_3.context);
    this._DefaultValueAccessor_11_6 = new import29.Wrapper_DefaultValueAccessor(this.renderer,new import16.ElementRef(this._el_11));
    this._NG_VALUE_ACCESSOR_11_7 = [
      this._MdAutocompleteTrigger_11_5.context,
      this._DefaultValueAccessor_11_6.context
    ]
    ;
    this._FormControlName_11_8 = new import30.Wrapper_FormControlName(this._ControlContainer_7_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_11_7);
    this._NgControl_11_9 = this._FormControlName_11_8.context;
    this._MdInputDirective_11_10 = new import27.Wrapper_MdInputDirective(new import16.ElementRef(this._el_11),this.renderer,this._NgControl_11_9);
    this._NgControlStatus_11_11 = new import26.Wrapper_NgControlStatus(this._NgControl_11_9);
    this._text_12 = this.renderer.createText((null as any),'    \n          ',this.debug(12,7,121));
    this.compView_9.create(this._MdInputContainer_9_3.context);
    this._text_13 = this.renderer.createText(this._el_7,'\n          ',this.debug(13,8,31));
    this._el_14 = import3.createRenderElement(this.renderer,this._el_7,'md-autocomplete',import3.EMPTY_INLINE_ARRAY,this.debug(14,9,10));
    this.compView_14 = new import38.View_MdAutocomplete0(this.viewUtils,this,14,this._el_14);
    this._MdPrefixRejector_14_3 = new import14.Wrapper_MdPrefixRejector(this.parentView.injectorGet(import12.MATERIAL_COMPATIBILITY_MODE,this.parentIndex,(null as any)));
    this._MdAutocomplete_14_4 = new import38.Wrapper_MdAutocomplete();
    this._query_MdOption_14_0 = new import28.QueryList<any>();
    this._text_15 = this.renderer.createText((null as any),'\n            ',this.debug(15,9,63));
    this._anchor_16 = this.renderer.createTemplateAnchor((null as any),this.debug(16,10,12));
    this._vc_16 = new import15.ViewContainer(16,14,this,this._anchor_16);
    this._TemplateRef_16_5 = new import33.TemplateRef_(this,16,this._anchor_16);
    this._NgFor_16_6 = new import39.Wrapper_NgFor(this._vc_16.vcRef,this._TemplateRef_16_5,this.parentView.injectorGet(import45.IterableDiffers,this.parentIndex),this.ref);
    this._text_17 = this.renderer.createText((null as any),'\n          ',this.debug(17,12,24));
    this.compView_14.create(this._MdAutocomplete_14_4.context);
    this._text_18 = this.renderer.createText(this._el_7,'\n          ',this.debug(18,13,28));
    this._el_19 = import3.createRenderElement(this.renderer,this._el_7,'md-input-container',new import3.InlineArray2(2,'floatPlaceholder','always'),this.debug(19,14,10));
    this.compView_19 = new import27.View_MdInputContainer0(this.viewUtils,this,19,this._el_19);
    this._MdInputContainer_19_3 = new import27.Wrapper_MdInputContainer();
    this._query_MdInputDirective_19_0 = new import28.QueryList<any>();
    this._query_MdPlaceholder_19_1 = new import28.QueryList<any>();
    this._query_MdHint_19_2 = new import28.QueryList<any>();
    this._text_20 = this.renderer.createText((null as any),'\n            ',this.debug(20,14,56));
    this._el_21 = import3.createRenderElement(this.renderer,(null as any),'input',new import3.InlineArray8(6,'formControlName','accountName','mdInput','','placeholder','Account Name'),this.debug(21,15,12));
    this._DefaultValueAccessor_21_3 = new import29.Wrapper_DefaultValueAccessor(this.renderer,new import16.ElementRef(this._el_21));
    this._NG_VALUE_ACCESSOR_21_4 = [this._DefaultValueAccessor_21_3.context];
    this._FormControlName_21_5 = new import30.Wrapper_FormControlName(this._ControlContainer_7_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_21_4);
    this._NgControl_21_6 = this._FormControlName_21_5.context;
    this._MdInputDirective_21_7 = new import27.Wrapper_MdInputDirective(new import16.ElementRef(this._el_21),this.renderer,this._NgControl_21_6);
    this._NgControlStatus_21_8 = new import26.Wrapper_NgControlStatus(this._NgControl_21_6);
    this._text_22 = this.renderer.createText((null as any),'         \n          ',this.debug(22,15,84));
    this.compView_19.create(this._MdInputContainer_19_3.context);
    this._text_23 = this.renderer.createText(this._el_7,'\n          ',this.debug(23,16,31));
    this._el_24 = import3.createRenderElement(this.renderer,this._el_7,'md-input-container',new import3.InlineArray2(2,'floatPlaceholder','always'),this.debug(24,17,10));
    this.compView_24 = new import27.View_MdInputContainer0(this.viewUtils,this,24,this._el_24);
    this._MdInputContainer_24_3 = new import27.Wrapper_MdInputContainer();
    this._query_MdInputDirective_24_0 = new import28.QueryList<any>();
    this._query_MdPlaceholder_24_1 = new import28.QueryList<any>();
    this._query_MdHint_24_2 = new import28.QueryList<any>();
    this._text_25 = this.renderer.createText((null as any),'\n            ',this.debug(25,17,56));
    this._el_26 = import3.createRenderElement(this.renderer,(null as any),'input',new import3.InlineArray8(6,'formControlName','bankName','mdInput','','placeholder','Bank Name'),this.debug(26,18,12));
    this._DefaultValueAccessor_26_3 = new import29.Wrapper_DefaultValueAccessor(this.renderer,new import16.ElementRef(this._el_26));
    this._NG_VALUE_ACCESSOR_26_4 = [this._DefaultValueAccessor_26_3.context];
    this._FormControlName_26_5 = new import30.Wrapper_FormControlName(this._ControlContainer_7_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_26_4);
    this._NgControl_26_6 = this._FormControlName_26_5.context;
    this._MdInputDirective_26_7 = new import27.Wrapper_MdInputDirective(new import16.ElementRef(this._el_26),this.renderer,this._NgControl_26_6);
    this._NgControlStatus_26_8 = new import26.Wrapper_NgControlStatus(this._NgControl_26_6);
    this._text_27 = this.renderer.createText((null as any),'         \n          ',this.debug(27,18,78));
    this.compView_24.create(this._MdInputContainer_24_3.context);
    this._text_28 = this.renderer.createText(this._el_7,'\n        ',this.debug(28,19,31));
    this._text_29 = this.renderer.createText(this._el_5,'\n\n        ',this.debug(29,20,14));
    this._anchor_30 = this.renderer.createTemplateAnchor(this._el_5,this.debug(30,22,8));
    this._vc_30 = new import15.ViewContainer(30,5,this,this._anchor_30);
    this._TemplateRef_30_5 = new import33.TemplateRef_(this,30,this._anchor_30);
    this._NgIf_30_6 = new import40.Wrapper_NgIf(this._vc_30.vcRef,this._TemplateRef_30_5);
    this._text_31 = this.renderer.createText(this._el_5,'\n\n        ',this.debug(31,29,14));
    this._anchor_32 = this.renderer.createTemplateAnchor(this._el_5,this.debug(32,31,8));
    this._vc_32 = new import15.ViewContainer(32,5,this,this._anchor_32);
    this._TemplateRef_32_5 = new import33.TemplateRef_(this,32,this._anchor_32);
    this._NgIf_32_6 = new import40.Wrapper_NgIf(this._vc_32.vcRef,this._TemplateRef_32_5);
    this._text_33 = this.renderer.createText(this._el_5,'\n\n        \n\n        \n        ',this.debug(33,38,14));
    this._el_34 = import3.createRenderElement(this.renderer,this._el_5,'button',new import3.InlineArray4(4,'md-button','','type','button'),this.debug(34,43,8));
    this.compView_34 = new import41.View_MdButton0(this.viewUtils,this,34,this._el_34);
    this._MdPrefixRejector_34_3 = new import14.Wrapper_MdPrefixRejector(this.parentView.injectorGet(import12.MATERIAL_COMPATIBILITY_MODE,this.parentIndex,(null as any)));
    this._MdButton_34_4 = new import41.Wrapper_MdButton(new import16.ElementRef(this._el_34),this.renderer);
    this._MdButtonCssMatStyler_34_5 = new import41.Wrapper_MdButtonCssMatStyler();
    this._el_35 = import3.createRenderElement(this.renderer,(null as any),'p',import3.EMPTY_INLINE_ARRAY,this.debug(35,43,61));
    this._text_36 = this.renderer.createText(this._el_35,'Submit',this.debug(36,43,64));
    this.compView_34.create(this._MdButton_34_4.context);
    this._text_37 = this.renderer.createText(this._el_5,'\n\n\n\n\n      ',this.debug(37,43,83));
    this._text_38 = this.renderer.createText(this._el_1,'\n\n      ',this.debug(38,48,13));
    this._text_39 = this.renderer.createText(parentRenderNode,'  \n    \n    ',this.debug(39,50,12));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_5,new import3.InlineArray8(6,'ngSubmit',(null as any),'submit',(null as any),'reset',(null as any)),this.eventHandler(this.handleEvent_5));
    this._FormGroupDirective_5_3.subscribe(this,this.eventHandler(this.handleEvent_5),true);
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_7,new import3.InlineArray4(4,'submit',(null as any),'reset',(null as any)),this.eventHandler(this.handleEvent_7));
    var disposable_2:Function = import3.subscribeToRenderElement(this,this._el_9,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_9));
    var disposable_3:Function = import3.subscribeToRenderElement(this,this._el_11,new import3.InlineArray8(8,'focus',(null as any),'blur',(null as any),'input',(null as any),'keydown',(null as any)),this.eventHandler(this.handleEvent_11));
    var disposable_4:Function = import3.subscribeToRenderElement(this,this._el_19,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_19));
    var disposable_5:Function = import3.subscribeToRenderElement(this,this._el_21,new import3.InlineArray8(6,'input',(null as any),'blur',(null as any),'focus',(null as any)),this.eventHandler(this.handleEvent_21));
    var disposable_6:Function = import3.subscribeToRenderElement(this,this._el_24,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_24));
    var disposable_7:Function = import3.subscribeToRenderElement(this,this._el_26,new import3.InlineArray8(6,'input',(null as any),'blur',(null as any),'focus',(null as any)),this.eventHandler(this.handleEvent_26));
    var disposable_8:Function = import3.subscribeToRenderElement(this,this._el_34,new import3.InlineArray8(8,'click',(null as any),'mousedown',(null as any),'focus',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_34));
    this._query_MdInputDirective_9_0.reset([this._MdInputDirective_11_10.context]);
    this._MdInputContainer_9_3.context._mdInputChild = this._query_MdInputDirective_9_0.first;
    this._query_MdPlaceholder_9_1.reset(([] as any[]));
    this._MdInputContainer_9_3.context._placeholderChild = this._query_MdPlaceholder_9_1.first;
    this._query_MdInputDirective_19_0.reset([this._MdInputDirective_21_7.context]);
    this._MdInputContainer_19_3.context._mdInputChild = this._query_MdInputDirective_19_0.first;
    this._query_MdPlaceholder_19_1.reset(([] as any[]));
    this._MdInputContainer_19_3.context._placeholderChild = this._query_MdPlaceholder_19_1.first;
    this._query_MdInputDirective_24_0.reset([this._MdInputDirective_26_7.context]);
    this._MdInputContainer_24_3.context._mdInputChild = this._query_MdInputDirective_24_0.first;
    this._query_MdPlaceholder_24_1.reset(([] as any[]));
    this._MdInputContainer_24_3.context._placeholderChild = this._query_MdPlaceholder_24_1.first;
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._anchor_16,
      this._text_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._text_28,
      this._text_29,
      this._anchor_30,
      this._text_31,
      this._anchor_32,
      this._text_33,
      this._el_34,
      this._el_35,
      this._text_36,
      this._text_37,
      this._text_38,
      this._text_39
    ]
    ),[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5,
      disposable_6,
      disposable_7,
      disposable_8
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import31.MdAutocompleteTrigger) && (11 === requestNodeIndex))) { return this._MdAutocompleteTrigger_11_5.context; }
    if (((token === import21.DefaultValueAccessor) && (11 === requestNodeIndex))) { return this._DefaultValueAccessor_11_6.context; }
    if (((token === import22.NG_VALUE_ACCESSOR) && (11 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_11_7; }
    if (((token === import23.FormControlName) && (11 === requestNodeIndex))) { return this._FormControlName_11_8.context; }
    if (((token === import24.NgControl) && (11 === requestNodeIndex))) { return this._NgControl_11_9; }
    if (((token === import20.MdInputDirective) && (11 === requestNodeIndex))) { return this._MdInputDirective_11_10.context; }
    if (((token === import19.NgControlStatus) && (11 === requestNodeIndex))) { return this._NgControlStatus_11_11.context; }
    if (((token === import20.MdInputContainer) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._MdInputContainer_9_3.context; }
    if (((token === import33.TemplateRef) && (16 === requestNodeIndex))) { return this._TemplateRef_16_5; }
    if (((token === import34.NgFor) && (16 === requestNodeIndex))) { return this._NgFor_16_6.context; }
    if (((token === import12.MdPrefixRejector) && ((14 <= requestNodeIndex) && (requestNodeIndex <= 17)))) { return this._MdPrefixRejector_14_3.context; }
    if (((token === import32.MdAutocomplete) && ((14 <= requestNodeIndex) && (requestNodeIndex <= 17)))) { return this._MdAutocomplete_14_4.context; }
    if (((token === import21.DefaultValueAccessor) && (21 === requestNodeIndex))) { return this._DefaultValueAccessor_21_3.context; }
    if (((token === import22.NG_VALUE_ACCESSOR) && (21 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_21_4; }
    if (((token === import23.FormControlName) && (21 === requestNodeIndex))) { return this._FormControlName_21_5.context; }
    if (((token === import24.NgControl) && (21 === requestNodeIndex))) { return this._NgControl_21_6; }
    if (((token === import20.MdInputDirective) && (21 === requestNodeIndex))) { return this._MdInputDirective_21_7.context; }
    if (((token === import19.NgControlStatus) && (21 === requestNodeIndex))) { return this._NgControlStatus_21_8.context; }
    if (((token === import20.MdInputContainer) && ((19 <= requestNodeIndex) && (requestNodeIndex <= 22)))) { return this._MdInputContainer_19_3.context; }
    if (((token === import21.DefaultValueAccessor) && (26 === requestNodeIndex))) { return this._DefaultValueAccessor_26_3.context; }
    if (((token === import22.NG_VALUE_ACCESSOR) && (26 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_26_4; }
    if (((token === import23.FormControlName) && (26 === requestNodeIndex))) { return this._FormControlName_26_5.context; }
    if (((token === import24.NgControl) && (26 === requestNodeIndex))) { return this._NgControl_26_6; }
    if (((token === import20.MdInputDirective) && (26 === requestNodeIndex))) { return this._MdInputDirective_26_7.context; }
    if (((token === import19.NgControlStatus) && (26 === requestNodeIndex))) { return this._NgControlStatus_26_8.context; }
    if (((token === import20.MdInputContainer) && ((24 <= requestNodeIndex) && (requestNodeIndex <= 27)))) { return this._MdInputContainer_24_3.context; }
    if (((token === import17.FormGroupDirective) && ((7 <= requestNodeIndex) && (requestNodeIndex <= 28)))) { return this._FormGroupDirective_7_3.context; }
    if (((token === import18.ControlContainer) && ((7 <= requestNodeIndex) && (requestNodeIndex <= 28)))) { return this._ControlContainer_7_4; }
    if (((token === import19.NgControlStatusGroup) && ((7 <= requestNodeIndex) && (requestNodeIndex <= 28)))) { return this._NgControlStatusGroup_7_5.context; }
    if (((token === import33.TemplateRef) && (30 === requestNodeIndex))) { return this._TemplateRef_30_5; }
    if (((token === import35.NgIf) && (30 === requestNodeIndex))) { return this._NgIf_30_6.context; }
    if (((token === import33.TemplateRef) && (32 === requestNodeIndex))) { return this._TemplateRef_32_5; }
    if (((token === import35.NgIf) && (32 === requestNodeIndex))) { return this._NgIf_32_6.context; }
    if (((token === import12.MdPrefixRejector) && ((34 <= requestNodeIndex) && (requestNodeIndex <= 36)))) { return this._MdPrefixRejector_34_3.context; }
    if (((token === import36.MdButton) && ((34 <= requestNodeIndex) && (requestNodeIndex <= 36)))) { return this._MdButton_34_4.context; }
    if (((token === import36.MdButtonCssMatStyler) && ((34 <= requestNodeIndex) && (requestNodeIndex <= 36)))) { return this._MdButtonCssMatStyler_34_5.context; }
    if (((token === import17.FormGroupDirective) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 37)))) { return this._FormGroupDirective_5_3.context; }
    if (((token === import18.ControlContainer) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 37)))) { return this._ControlContainer_5_4; }
    if (((token === import19.NgControlStatusGroup) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 37)))) { return this._NgControlStatusGroup_5_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.debug(5,3,18);
    const currVal_5_0_0:any = this.context.bankAccountTabForm;
    this._FormGroupDirective_5_3.check_form(currVal_5_0_0,throwOnChange,false);
    this._FormGroupDirective_5_3.ngDoCheck(this,this._el_5,throwOnChange);
    this.debug(5,3,12);
    this._NgControlStatusGroup_5_5.ngDoCheck(this,this._el_5,throwOnChange);
    this.debug(7,5,38);
    const currVal_7_0_0:any = this.context.bankAccountTabForm;
    this._FormGroupDirective_7_3.check_form(currVal_7_0_0,throwOnChange,false);
    this._FormGroupDirective_7_3.ngDoCheck(this,this._el_7,throwOnChange);
    this.debug(7,5,8);
    this._NgControlStatusGroup_7_5.ngDoCheck(this,this._el_7,throwOnChange);
    this.debug(9,6,30);
    const currVal_9_0_0:any = 'always';
    this._MdInputContainer_9_3.check_floatPlaceholder(currVal_9_0_0,throwOnChange,false);
    this._MdInputContainer_9_3.ngDoCheck(this,this._el_9,throwOnChange);
    this.debug(11,7,54);
    const currVal_11_0_0:any = this._MdAutocomplete_14_4.context;
    this._MdAutocompleteTrigger_11_5.check_autocomplete(currVal_11_0_0,throwOnChange,false);
    this._MdAutocompleteTrigger_11_5.ngDoCheck(this,this._el_11,throwOnChange);
    this.debug(11,7,12);
    this._DefaultValueAccessor_11_6.ngDoCheck(this,this._el_11,throwOnChange);
    this.debug(11,7,91);
    const currVal_11_2_0:any = 'accountType';
    this._FormControlName_11_8.check_name(currVal_11_2_0,throwOnChange,false);
    this._FormControlName_11_8.ngDoCheck(this,this._el_11,throwOnChange);
    this.debug(11,7,27);
    const currVal_11_3_0:any = 'Account Type';
    this._MdInputDirective_11_10.check_placeholder(currVal_11_3_0,throwOnChange,false);
    this._MdInputDirective_11_10.ngDoCheck(this,this._el_11,throwOnChange);
    this.debug(11,7,12);
    this._NgControlStatus_11_11.ngDoCheck(this,this._el_11,throwOnChange);
    this.debug(14,9,10);
    this._MdPrefixRejector_14_3.ngDoCheck(this,this._el_14,throwOnChange);
    this._MdAutocomplete_14_4.ngDoCheck(this,this._el_14,throwOnChange);
    this.debug(16,10,59);
    const currVal_16_0_0:any = this.context.accountTypes;
    this._NgFor_16_6.check_ngForOf(currVal_16_0_0,throwOnChange,false);
    this._NgFor_16_6.ngDoCheck(this,this._anchor_16,throwOnChange);
    this.debug(19,14,30);
    const currVal_19_0_0:any = 'always';
    this._MdInputContainer_19_3.check_floatPlaceholder(currVal_19_0_0,throwOnChange,false);
    this._MdInputContainer_19_3.ngDoCheck(this,this._el_19,throwOnChange);
    this.debug(21,15,12);
    this._DefaultValueAccessor_21_3.ngDoCheck(this,this._el_21,throwOnChange);
    this.debug(21,15,54);
    const currVal_21_1_0:any = 'accountName';
    this._FormControlName_21_5.check_name(currVal_21_1_0,throwOnChange,false);
    this._FormControlName_21_5.ngDoCheck(this,this._el_21,throwOnChange);
    this.debug(21,15,27);
    const currVal_21_2_0:any = 'Account Name';
    this._MdInputDirective_21_7.check_placeholder(currVal_21_2_0,throwOnChange,false);
    this._MdInputDirective_21_7.ngDoCheck(this,this._el_21,throwOnChange);
    this.debug(21,15,12);
    this._NgControlStatus_21_8.ngDoCheck(this,this._el_21,throwOnChange);
    this.debug(24,17,30);
    const currVal_24_0_0:any = 'always';
    this._MdInputContainer_24_3.check_floatPlaceholder(currVal_24_0_0,throwOnChange,false);
    this._MdInputContainer_24_3.ngDoCheck(this,this._el_24,throwOnChange);
    this.debug(26,18,12);
    this._DefaultValueAccessor_26_3.ngDoCheck(this,this._el_26,throwOnChange);
    this.debug(26,18,51);
    const currVal_26_1_0:any = 'bankName';
    this._FormControlName_26_5.check_name(currVal_26_1_0,throwOnChange,false);
    this._FormControlName_26_5.ngDoCheck(this,this._el_26,throwOnChange);
    this.debug(26,18,27);
    const currVal_26_2_0:any = 'Bank Name';
    this._MdInputDirective_26_7.check_placeholder(currVal_26_2_0,throwOnChange,false);
    this._MdInputDirective_26_7.ngDoCheck(this,this._el_26,throwOnChange);
    this.debug(26,18,12);
    this._NgControlStatus_26_8.ngDoCheck(this,this._el_26,throwOnChange);
    this.debug(30,22,38);
    const currVal_30_0_0:any = (this.context.bankAccountTabForm.controls['accountType'].value == 'UK');
    this._NgIf_30_6.check_ngIf(currVal_30_0_0,throwOnChange,false);
    this._NgIf_30_6.ngDoCheck(this,this._anchor_30,throwOnChange);
    this.debug(32,31,38);
    const currVal_32_0_0:any = (this.context.bankAccountTabForm.controls['accountType'].value == 'Non-UK');
    this._NgIf_32_6.check_ngIf(currVal_32_0_0,throwOnChange,false);
    this._NgIf_32_6.ngDoCheck(this,this._anchor_32,throwOnChange);
    this.debug(34,43,8);
    this._MdPrefixRejector_34_3.ngDoCheck(this,this._el_34,throwOnChange);
    if (this._MdButton_34_4.ngDoCheck(this,this._el_34,throwOnChange)) { this.compView_34.markAsCheckOnce(); }
    this._MdButtonCssMatStyler_34_5.ngDoCheck(this,this._el_34,throwOnChange);
    this._vc_11.detectChangesInNestedViews(throwOnChange);
    this._vc_16.detectChangesInNestedViews(throwOnChange);
    this._vc_30.detectChangesInNestedViews(throwOnChange);
    this._vc_32.detectChangesInNestedViews(throwOnChange);
    if (!throwOnChange) {
      if (this._query_MdHint_9_2.dirty) {
        this._query_MdHint_9_2.reset(([] as any[]));
        this._MdInputContainer_9_3.context._hintChildren = this._query_MdHint_9_2;
        this._query_MdHint_9_2.notifyOnChanges();
      }
      if (this._query_MdOption_14_0.dirty) {
          this._query_MdOption_14_0.reset([this._vc_16.mapNestedViews(View_BankAccountTabComponent1,(nestedView:View_BankAccountTabComponent1):any => {
            return [nestedView._MdOption_0_3.context];
        })]);
        this._MdAutocomplete_14_4.context.options = this._query_MdOption_14_0;
        this._query_MdOption_14_0.notifyOnChanges();
      }
      if (this._query_MdHint_19_2.dirty) {
        this._query_MdHint_19_2.reset(([] as any[]));
        this._MdInputContainer_19_3.context._hintChildren = this._query_MdHint_19_2;
        this._query_MdHint_19_2.notifyOnChanges();
      }
      if (this._query_MdHint_24_2.dirty) {
        this._query_MdHint_24_2.reset(([] as any[]));
        this._MdInputContainer_24_3.context._hintChildren = this._query_MdHint_24_2;
        this._query_MdHint_24_2.notifyOnChanges();
      }
      this.debug(11,7,12);
      if ((this.numberOfChecks === 0)) { this._MdAutocompleteTrigger_11_5.context.ngAfterContentInit(); }
      this.debug(9,6,10);
      if ((this.numberOfChecks === 0)) { this._MdInputContainer_9_3.context.ngAfterContentInit(); }
      this.debug(19,14,10);
      if ((this.numberOfChecks === 0)) { this._MdInputContainer_19_3.context.ngAfterContentInit(); }
      this.debug(24,17,10);
      if ((this.numberOfChecks === 0)) { this._MdInputContainer_24_3.context.ngAfterContentInit(); }
    }
    this._NgControlStatusGroup_5_5.checkHost(this,this,this._el_5,throwOnChange);
    this._NgControlStatusGroup_7_5.checkHost(this,this,this._el_7,throwOnChange);
    this._MdInputContainer_9_3.checkHost(this,this.compView_9,this._el_9,throwOnChange);
    this._MdAutocompleteTrigger_11_5.checkHost(this,this,this._el_11,throwOnChange);
    this._MdInputDirective_11_10.checkHost(this,this,this._el_11,throwOnChange);
    this._NgControlStatus_11_11.checkHost(this,this,this._el_11,throwOnChange);
    this._MdAutocomplete_14_4.checkHost(this,this.compView_14,this._el_14,throwOnChange);
    this._MdInputContainer_19_3.checkHost(this,this.compView_19,this._el_19,throwOnChange);
    this._MdInputDirective_21_7.checkHost(this,this,this._el_21,throwOnChange);
    this._NgControlStatus_21_8.checkHost(this,this,this._el_21,throwOnChange);
    this._MdInputContainer_24_3.checkHost(this,this.compView_24,this._el_24,throwOnChange);
    this._MdInputDirective_26_7.checkHost(this,this,this._el_26,throwOnChange);
    this._NgControlStatus_26_8.checkHost(this,this,this._el_26,throwOnChange);
    this._MdButton_34_4.checkHost(this,this.compView_34,this._el_34,throwOnChange);
    this._MdButtonCssMatStyler_34_5.checkHost(this,this.compView_34,this._el_34,throwOnChange);
    this.compView_9.internalDetectChanges(throwOnChange);
    this.compView_14.internalDetectChanges(throwOnChange);
    this.compView_19.internalDetectChanges(throwOnChange);
    this.compView_24.internalDetectChanges(throwOnChange);
    this.compView_34.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this._vc_11.destroyNestedViews();
    this._vc_16.destroyNestedViews();
    this._vc_30.destroyNestedViews();
    this._vc_32.destroyNestedViews();
    this.compView_9.destroy();
    this.compView_14.destroy();
    this.compView_19.destroy();
    this.compView_24.destroy();
    this.compView_34.destroy();
    this._MdAutocompleteTrigger_11_5.ngOnDestroy();
    this._FormControlName_11_8.ngOnDestroy();
    this._MdInputDirective_11_10.ngOnDestroy();
    this.debug(11,7,12);
    this.debug(9,6,10);
    this.debug(16,10,12);
    this.debug(14,9,10);
    this._FormControlName_21_5.ngOnDestroy();
    this._MdInputDirective_21_7.ngOnDestroy();
    this.debug(21,15,12);
    this.debug(19,14,10);
    this._FormControlName_26_5.ngOnDestroy();
    this._MdInputDirective_26_7.ngOnDestroy();
    this.debug(26,18,12);
    this.debug(24,17,10);
    this._FormGroupDirective_7_3.ngOnDestroy();
    this.debug(7,5,8);
    this.debug(30,22,8);
    this.debug(32,31,8);
    this.debug(34,43,8);
    this._FormGroupDirective_5_3.ngOnDestroy();
  }
  visitProjectableNodesInternal(nodeIndex:number,ngContentIndex:number,cb:any,ctx:any):void {
    if (((nodeIndex == 9) && (ngContentIndex == 0))) {  }
    if (((nodeIndex == 9) && (ngContentIndex == 1))) {
      cb(this._text_10,ctx);
      cb(this._vc_11.nativeElement,ctx);
      this._vc_11.visitNestedViewRootNodes(cb,ctx);
      cb(this._text_12,ctx);
    }
    if (((nodeIndex == 9) && (ngContentIndex == 2))) {  }
    if (((nodeIndex == 9) && (ngContentIndex == 3))) {  }
    if (((nodeIndex == 9) && (ngContentIndex == 4))) {  }
    if (((nodeIndex == 14) && (ngContentIndex == 0))) {
      cb(this._text_15,ctx);
      cb(this._vc_16.nativeElement,ctx);
      this._vc_16.visitNestedViewRootNodes(cb,ctx);
      cb(this._text_17,ctx);
    }
    if (((nodeIndex == 19) && (ngContentIndex == 0))) {  }
    if (((nodeIndex == 19) && (ngContentIndex == 1))) {
      cb(this._text_20,ctx);
      cb(this._el_21,ctx);
      cb(this._text_22,ctx);
    }
    if (((nodeIndex == 19) && (ngContentIndex == 2))) {  }
    if (((nodeIndex == 19) && (ngContentIndex == 3))) {  }
    if (((nodeIndex == 19) && (ngContentIndex == 4))) {  }
    if (((nodeIndex == 24) && (ngContentIndex == 0))) {  }
    if (((nodeIndex == 24) && (ngContentIndex == 1))) {
      cb(this._text_25,ctx);
      cb(this._el_26,ctx);
      cb(this._text_27,ctx);
    }
    if (((nodeIndex == 24) && (ngContentIndex == 2))) {  }
    if (((nodeIndex == 24) && (ngContentIndex == 3))) {  }
    if (((nodeIndex == 24) && (ngContentIndex == 4))) {  }
    if (((nodeIndex == 34) && (ngContentIndex == 0))) { cb(this._el_35,ctx); }
  }
  createEmbeddedViewInternal(nodeIndex:number):import2.AppView<any> {
    if ((nodeIndex == 16)) { return new View_BankAccountTabComponent1(this.viewUtils,this,16,this._anchor_16,this._vc_16); }
    if ((nodeIndex == 30)) { return new View_BankAccountTabComponent2(this.viewUtils,this,30,this._anchor_30,this._vc_30); }
    if ((nodeIndex == 32)) { return new View_BankAccountTabComponent3(this.viewUtils,this,32,this._anchor_32,this._vc_32); }
    return (null as any);
  }
  handleEvent_5(eventName:string,$event:any):boolean {
    this.debug(5,3,12);
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._FormGroupDirective_5_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngSubmit')) {
      const pd_sub_0:any = ((<any>this.context.onSubmit()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_7(eventName:string,$event:any):boolean {
    this.debug(7,5,8);
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._FormGroupDirective_7_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_9(eventName:string,$event:any):boolean {
    this.debug(9,6,10);
    this.compView_9.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._MdInputContainer_9_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_11(eventName:string,$event:any):boolean {
    this.debug(11,7,12);
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._MdAutocompleteTrigger_11_5.handleEvent(eventName,$event) && result);
    result = (this._DefaultValueAccessor_11_6.handleEvent(eventName,$event) && result);
    result = (this._MdInputDirective_11_10.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_19(eventName:string,$event:any):boolean {
    this.debug(19,14,10);
    this.compView_19.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._MdInputContainer_19_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_21(eventName:string,$event:any):boolean {
    this.debug(21,15,12);
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_21_3.handleEvent(eventName,$event) && result);
    result = (this._MdInputDirective_21_7.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_24(eventName:string,$event:any):boolean {
    this.debug(24,17,10);
    this.compView_24.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._MdInputContainer_24_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_26(eventName:string,$event:any):boolean {
    this.debug(26,18,12);
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_26_3.handleEvent(eventName,$event) && result);
    result = (this._MdInputDirective_26_7.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_34(eventName:string,$event:any):boolean {
    this.debug(34,43,8);
    this.compView_34.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._MdButton_34_4.handleEvent(eventName,$event) && result);
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.onSubmit()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}