export class Contact {
    constructor(contactType = "", salutation = "", preferredName = "", dateOfBirth = "", firstName = "", middleName = "", lastName = "", gender = "", maritalStatus = "", dateOfDeath = "", nationality = "", primaryEmail = "", secondaryEmail = "", mobilePhone = "", homePhone = "", workPhone = "", smoker = false, goodHealth = false, medicalConditions = false, occupation = "", occupationTitle = "", employerName = "", tEmployment = 0, ntEmployment = 0, tSelfEmployedY1 = 0, ntSelfEmployedY1 = 0, tSelfEmployedY2 = 0, ntSelfEmployedY2 = 0, tPension = 0, ntPension = 0, tStatePension = 0, ntStatePension = 0, tStateBenefit = 0, ntStateBenefit = 0, tOther = 0, ntOther = 0, monthlyPolicyExpenditure = 0, monthlyEssentialExpenditure = 0, monthlyDiscretionaryExpenditure = 0, emergencyFundsAvailable = 0, emergencyFundsRecommended = 0, futureCircumstances = "", taxRate = 0, taxResident = false, taxDomicile = false, taxResidenceDate = "", taxNI = 0, taxWillChange = false, accountId = "", createdAt = new Date()) {
        this.contactType = contactType;
        this.salutation = salutation;
        this.preferredName = preferredName;
        this.dateOfBirth = dateOfBirth;
        this.firstName = firstName;
        this.middleName = middleName;
        this.lastName = lastName;
        this.gender = gender;
        this.maritalStatus = maritalStatus;
        this.dateOfDeath = dateOfDeath;
        this.nationality = nationality;
        this.primaryEmail = primaryEmail;
        this.secondaryEmail = secondaryEmail;
        this.mobilePhone = mobilePhone;
        this.homePhone = homePhone;
        this.workPhone = workPhone;
        this.smoker = smoker;
        this.goodHealth = goodHealth;
        this.medicalConditions = medicalConditions;
        this.occupation = occupation;
        this.occupationTitle = occupationTitle;
        this.employerName = employerName;
        this.tEmployment = tEmployment;
        this.ntEmployment = ntEmployment;
        this.tSelfEmployedY1 = tSelfEmployedY1;
        this.ntSelfEmployedY1 = ntSelfEmployedY1;
        this.tSelfEmployedY2 = tSelfEmployedY2;
        this.ntSelfEmployedY2 = ntSelfEmployedY2;
        this.tPension = tPension;
        this.ntPension = ntPension;
        this.tStatePension = tStatePension;
        this.ntStatePension = ntStatePension;
        this.tStateBenefit = tStateBenefit;
        this.ntStateBenefit = ntStateBenefit;
        this.tOther = tOther;
        this.ntOther = ntOther;
        this.monthlyPolicyExpenditure = monthlyPolicyExpenditure;
        this.monthlyEssentialExpenditure = monthlyEssentialExpenditure;
        this.monthlyDiscretionaryExpenditure = monthlyDiscretionaryExpenditure;
        this.emergencyFundsAvailable = emergencyFundsAvailable;
        this.emergencyFundsRecommended = emergencyFundsRecommended;
        this.futureCircumstances = futureCircumstances;
        this.taxRate = taxRate;
        this.taxResident = taxResident;
        this.taxDomicile = taxDomicile;
        this.taxResidenceDate = taxResidenceDate;
        this.taxNI = taxNI;
        this.taxWillChange = taxWillChange;
        this.accountId = accountId;
        this.createdAt = createdAt;
    }
}
//# sourceMappingURL=Contact.js.map